### ISSUE TITLE
Secure Desktop (Windows) + Secure Input (Mac) Feature against Software Keylogger

### ISSUE THREAD

**Issue by JimLoose** [veracrypt/VeraCrypt#10]
A lot of OS give us tools and protections for secure input of passwords:
https://blog.agilebits.com/2014/08/21/watch-what-you-type-1passwords-defenses-against-keystroke-loggers/ like the:
- Secure Desktop function of Windows
- Secure Input function of Mac OS

It would be great to have these implemented! :+1: 

Thank you for your work!

**Comment by idrassi** [comment]
Protecting against keyloggers make more sens when the protected resource is remote (like a web-mail or a could service). In cases where the protected resource is local to the system, it is almost certain that, if a keylogger is present, other parts of the malware associated with it will be running and they will access the protected resource easily, bypassing any password protection.

That's why VeraCrypt, and TrueCrypt before it, never implemented any protection against keylogger and other malware types. There is even a dedicated chapter about this in the documentation: https://veracrypt.codeplex.com/wikipage?title=Malware

That being said, it will eventually be implemented at some point since it is more secure anyway, but for the reasons I explained above, it has low priority now compared to the other remaining tasks.

**Comment by idrassi** [comment]
VeraCrypt now supports Secure Desktop password entry on Windows since version 1.20 (it must be activated in the Preferences). It has also been extended to include PIN entry for smart card (https://github.com/veracrypt/VeraCrypt/commit/7f2981f25720053b10ed935e1b7f7d8331df0e95).

For Mac OSX, no plan to add it for now. I will update this issue if it is implemented.

**Comment by JimLoose** [comment]
hey stalebot can you please reopen this issue?
