### ISSUE TITLE
Assertion failed while backing up and restoring volume header

### ISSUE THREAD

**Issue by Overlord23** [veracrypt/VeraCrypt#100]
I'm running VeraCrypt 1.18 on Ubuntu Mate 14.04.5.
I needed to backup the volume header of a container; after typing the outer volume password, I got the following error:

```
An assertion failed!
 ../src/generic/choicdgg.cpp(511): assert "sel >= 0 && (unsigned)sel < m_listbox->GetCount()" failed in SetSelection(): Invalid initial selection

```

After selecting **Continue**, the backup operation ended successfully.

To check the backup integrity, I restored immediately the backup on a copy of the same container; the operation has been completed but I got the exact same error.

In the following file you can see the backtrace error [backtrace.txt](https://github.com/veracrypt/VeraCrypt/files/490514/backtrace.txt)

**Comment by BluBb-mADe** [comment]
can confirm that under newest arch with gnome3 with veracrypt 1.19 via pacman

**Comment by all3fox** [comment]
being repeatedly hit by this on AtchLinux with veracrypt 1.21 via pacman trying to open a simple encrypted file.

My story is somewhat longer: two days ago my volume refused to open with the standard "Operation failed due to one or more of the following" (which usually means you've messed up typing your password). I've retyped my password several times (double checking CapsLock and language layout), then lastly used the "Display password" to verify it with my own eyes. It checked out.

So, I went ahead to `Volume Tools -> Restore Volume Header`. At this point I was immediately hit by this backtrace, so I though there is something wrong with the header indeed. Unfortunately, I did not create external header copies, so I used the `Restore volume header from the backup embedded in the volume`. After having moved my mouse around, I was told that the header was restored (and a warning about old passwords). So, I tried to open the file once again with the same password as before and it worked. I've taken a look at about 20 files and they all were fine.

Today, I've been hit by the same issue again, went to restore the header and still can't open the file.
