### ISSUE TITLE
PBKDF2-HMAC-BLAKE2s

### ISSUE THREAD

**Issue by wendig0x** [veracrypt/VeraCrypt#1000]
Hi!

Are you sure you are using this construct correctly /src/Common/Pkcs5.c ?

PBKDF2 needs a PRF, not a hash function. A PRF is a kind of keyed hash, which SHA1 and SHA256 are not, as they have only one input. You can securely turn them into a PRF by using HMAC, which was explicitly designed to mitigate some risks related to the construction underlying SHA1 and SHA-2 (and other Merkle–Damgård hashes).

In other words, PBKDF2 is commonly used with HMAC-SHA1 and HMAC-SHA256 as PRFs: it cannot be used with SHA1 or SHA256 alone.

If you want to use BLAKE2, there is no reason to use HMAC at all, because BLAKE2 is not a Merkle–Damgård construction. Even more, BLAKE2 was designed to natively operate as a PRF, unlike SHA1 and SHA256.

**Comment by idrassi** [comment]
Thank you for your observations and question on the choice to use PBKDF2-HMAC-BLAKE2S in VeraCrypt.

I agree that Blake2s is already a PRF and theoretically, we could use it directly without HMAC. However, my decision to employ HMAC-BLAKE2S instead is guided by several factors.
Firstly, there is nothing wrong (from security point of view) with the use HMAC with BLAKE2S. Additionaly, HMAC offers a kind of insurance against potential cryptographic vulnerabilities in Blake2s keyed mode which are not known today, thanks to the time-tested and well-understood security properties of HMAC.

Secondly, HMAC-Blake2s usage makes PBKDF2 slower than the case of Blake2s keys mode. This makes PBKDF2-HMAC-BLAKE2S a better choice for VeraCrypt than PBKDF2-BLAKE2S since we slowner provides higher level of resistance against brute-force attacks.

Thirdly, integrating Blake2s with HMAC provides easier integration into existing VeraCrypt archirecture.

I hope this clairifies the choice of PBKDF2-HMAC-BLAKE2. Of course, I remain open to any elements that I may have overlooked and which may bring up security issues that I didn't take into account.
