### ISSUE TITLE
Windows 10 - When Booting Automatic System Repair Message

### ISSUE THREAD

**Issue by hasanalizxc** [veracrypt/VeraCrypt#101]
Dear,

I encrypted my WORK pc with System Partition Encryption because i couldn't choose whole drive encryption. And then it finished. I rebooted my pc and encountered "automatic system repair" message and afraid. Because all my life is in that pc and i don't know what is the problem?

Help me please.

**Comment by idrassi** [comment]
Hi,

Are you using EFI system encryption or MBR?
What is the brand of your machine? There have been reports on ACER and HP machines where the motherboard resets EFI boot configuration after a power off which removes VeraCrypt EFI bootloader.
In such situations, you have to use the Rescue Disk in order to decrypt your system. In case of EFI, just unzip the content of the Rescue Disk zip file in a USB disk and boot on it and then use the decrypt operation. And if you didn't backup the Rescue Disk zip file, you can get it by booting on a Linux live CD and accessing your encrypted system using VeraCrypt on Linux as shown here: https://www.youtube.com/watch?v=4xJrVGzAk0Y
In all cases, your data are not lost and you can retrieve them.

**Comment by OfficialMuffin** [comment]
HI, I know this is a late reply I was wondering if you have ever got this sorted because I am having the same problem except that I have found a temporary workaround. I need a permanent fix for this which I cannot seem to find anywhere.

**Comment by idrassi** [comment]
Hi,

The latest version 1.23 released few days ago fixes this problem so you
should give it a try.

**Comment by OfficialMuffin** [comment]
Hi,

I have indeed have the 1.23 version installed. I still have the same problem.
I am having to use BOOTICE software to boot the encrypted parition at start. This is annoying as Windows changes the boot option at the next boot.

Thanks,
OfficialMuffin

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by idrassi** [comment]
This is strange as it should not happen now.
To help investigate this, can you please check the files
"EFI\Microsoft\Boot\bootmgfw.efi", "EFI\Microsoft\Boot\bootmgfw_ms.vc",
"EFI\Boot\bootx64.efi" and "EFI\Boot\original_bootx64.vc_backup" in the
EFI system partition and report their sizes and timestamps.
On Windows, you can access the EFI system partition by launching a
command prompt as an administrator and typing: "mountvol B: /s" and then
going to B: to look for the above files.

Normally, bootmgfw.efi and bootx64.efi should have the same size as
"EFI\VeraCrypt\DcsBoot.efi".

**Comment by tvleavitt** [comment]
I had this same problem, HP Envy booting into "Automatic Repair" and failing, but bootable by manual selection of the DcsBoot.efi file after hitting ESC and F9 and navigating to it... was running 1.23BETA4, when I installed 1.23 release (Sept. 12) it fixed the problem. Not sure if it was the new version, or the new install resetting EFI default, but I'm happy (so is client).

**Comment by hasanalizxc** [comment]
> Hi, The latest version 1.23 released few days ago fixes this problem so you should give it a try.

I will try Idris but first i need solve my babie's pictures. Please read issue 201. I need your help..

**Comment by OfficialMuffin** [comment]
Is it safe to decrypt and then encrypt your drive after reinstallation of veracrypt
