### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by mynameherebro** [veracrypt/VeraCrypt#105]
An option that auto-loads Veracrypt password dialog box when an encrypted volume in plugged into system. This would be nice not having to open veracrypt and mounting the disk every time it gets plugged in.

Thank You in advanced 

MiSK

**Comment by idrassi** [comment]
This option already exists: mount your disk, add it to favorites and check the option "Mount selected volume when its host device gets connected" and then click ok to save the favorite configuration.

Once done, everytime the disk is connected, VeraCrypt will prompt for its password.

Also, since the disk path can change, it is better to check the option "Use Volume ID to mount favorite" in the favorite dialog.

Below is a screenshot. I'm closing this issue since it is already implemented. Feel free to reopen if you have issues.

![VeraCryptFavoriteAutomountInsertion](https://i.imgur.com/Pjuz1V0.png)
