### ISSUE TITLE
Error: TestFailed at VeraCrypt::RandomNumberGenerator::Test:266

### ISSUE THREAD

**Issue by cstffx** [veracrypt/VeraCrypt#1050]
When we compile VeraCrypt in Linux (Kubuntu 22.04)  we get:

``Error: TestFailed at VeraCrypt::RandomNumberGenerator::Test:266``

each time we try to create a new volume. 

I discovered this issue when I tried to use Core/RandomNumberGenerator in the source code of my application. 
I discovered too that  the error comes from this function: 

```c++
void RandomNumberGenerator::Test ()
	{
		shared_ptr <Hash> origPoolHash = PoolHash;
		PoolHash.reset (new Blake2s());

		Pool.Zero();
		Buffer buffer (1);
		for (size_t i = 0; i < PoolSize * 10; ++i)
		{
			buffer[0] = (byte) i;
			AddToPool (buffer);
		}

		if (Crc32::ProcessBuffer (Pool) != 0x9ae2fff8)
			throw TestFailed (SRC_POS);

		buffer.Allocate (PoolSize);
		buffer.CopyFrom (PeekPool());
		AddToPool (buffer);

		if (Crc32::ProcessBuffer (Pool) != 0x391135a7)
			throw TestFailed (SRC_POS);

		PoolHash = origPoolHash;
	}
```

Each time we call ``Crc32::ProcessBuffer (Pool)`` the returned value is different if the algorithm is  ``Blake2s`` for the ``PoolHash``. Others algorithms seems to produce the same value no matter how many time we execute the program. 
Of course the value is always different of ``0x9ae2fff8``. 

I'm getting the same error both command line and visual interface.

**Comment by Jertzukka** [comment]
Commit prior to 36795a688fd1d5bb9f497970938d9fcb08cfc330 is the last known good one. I believe the change [here](https://github.com/veracrypt/VeraCrypt/commit/36795a688fd1d5bb9f497970938d9fcb08cfc330#diff-be12488293299af015c17d13ab9b38bd16de22bd1306c187d69b5d6bbdd3ba05) from Ripemd160 to Blake2s causes the Test to always throw.

The same error pops up on GUI version, but you can bypass it by just hitting OK and then trying "Create volume" again and it won't stop you. 

ping @idrassi

**Comment by idrassi** [comment]
This issue seems to be linked to how the compiler builds Blake2s implementation.
In the test method, VeraCrypt uses the given hash function to perform hasing of a random pool of 320 bytes. The CRC32 of this pool has deterministic values at different stages of the algorithm that depend on the used hash function.

So, it is clear that Blake2s code is the culprit here since it is the only one triggering this behavior.

I was able to reproduce the problem at my end and a quick check shows that the issue happens even after removing SSE4.1 and SSSE3 optimized code. So the issue happens even with the generic C implementation of Blake2s.

VeraCrypt uses Blake2s C code from https://github.com/BLAKE2/BLAKE2 project without modifications. I will check if new update from Blake2s will fix this behavior and if not I will debug further Blake2s implementation. Not really a VeraCrypt issue but we have no choice as Blake2s is meant to replace RIPEMD160.
I will let you know.

**Comment by idrassi** [comment]
After further analysis, it turns out that the issue is caused by lack of explicit hash initialization in the `RandomNumberGenerator::HashMixPool` method which caused `blake2s_final` calls to fail because Blake2s doesn't allow further processing with the same context if a digest was returned. This in turn caused `PoolHash->GetDigest `call to fail, leaving `digest` variable with uninitialized content.

On some machines, the uninitialized content of digest variable will have the same value on each run while on other machines digest will have random value on each run. That's why I could not see this issue initially.

The other hash algorithm don't have this constraint and that's why they didn't exhibit this issue.

I have pushed a commit to fix this issue: https://github.com/veracrypt/VeraCrypt/commit/f4b310b23f276744a1616137810c2135c7d5f736

Thank you for the report.

I will also do extra changes to the `RandomNumberGenerator::HashMixPool` to align it with the Windows implementation and the pool mixing algorithm described in VeraCrypt documentation because current implementation has some deviations (current implementation still provides requires diffusion property).
