### ISSUE TITLE
Sierra problems

### ISSUE THREAD

**Issue by karolyi** [veracrypt/VeraCrypt#106]
Coming from https://github.com/osxfuse/osxfuse/issues/326:

OSX Sierra, MacFuse 3.5.2, VeraCrypt 1.19-Beta, and I have the following error when trying to mount a volume:

![image](https://cloud.githubusercontent.com/assets/987055/19398238/edf60f82-924b-11e6-8e04-fde8c213d377.png)

I could not get more detailed information, unfortunately.

**Comment by idrassi** [comment]
Hi,

What version of 1.19-BETA are you using? Yesterday, I published 1.19-BETA3 that removes dependency towards MacFUSE compatibility layer.
I just did a test on a clean OSX Sierra machine with OSXFuse 3.5.2 installed without MacFUSE compatibility layer and it worked without a problem.

Can you please do the following the procedure and see if it solves your problem:
- Uninstall OSXFuse using the uninstall script present in OSXFuse dmg file.
- Reboot.
- Install OSXFuse 3.5.2 without selecting MacFUSE compatibility layer since it is not needed anymore.
- Reboot
- Download and install the latest VeraCrypt 1.19-BETA from https://sourceforge.net/projects/veracrypt/files/VeraCrypt%20Nightly%20Builds/
- Mount your volume

**Comment by karolyi** [comment]
Thx, it works after executing the steps you provided. I was using the latest beta, downloaded today.

**Comment by idrassi** [comment]
Thank you for the confirmation. Closing this ticket.
