### ISSUE TITLE
TRIM not working on Non-system SSD partition even when TRIM is enabled in Veracrypt driver settings

### ISSUE THREAD

**Issue by gashtal** [veracrypt/VeraCrypt#1102]
I have one non-system SSD partition that is encrypted using Veracrypt. However, despite enabling "Allow TRIM command for non-system SSD partition/drive" in Veracrypt's driver options, The "Optimize Drives" option in Windows says "Optimization not available" on that partition, while a Bitlocker-enabled partition on the same SSD can be TRIMed without any issues.

Running `defrag /L` manually on the partition claims that the free space has been trimmed, but the the same output is shown even if "Allow TRIM command for non-system SSD partition/drive" is _disabled_ in Veracrypt and hence, it doesn't seem like the command is actually doing anything and read/write speeds on that particular drive are still abysmal. Output of the command is shown below:

```
C:\WINDOWS\system32>defrag E: /L

Invoking retrim on (E:)...


The operation completed successfully.

Post Defragmentation Report:

        Volume Information:
                Volume size                 = 1.62 TB
                Free space                  = 84.43 GB

        Retrim:
                Total space trimmed         = 84.43 GB
```

# Expected behavior
With "Allow TRIM command for non-system SSD partition/drive" enabled in Veracrypt driver options, Windows "Optimize Drives" should show that the non-system SSD partitions can be optimized, just like Bitlocker-enabled partitions on the same SSD.

# Observed behavior
Windows "Optimize Drives" shows that the non-system SSD partitions cannot be optimized ("Optimization not available").

# Steps to reproduce
1. Create a non-system partition on an SSD and encrypt it with Veracrypt
2. Enable "Allow TRIM command for non-system SSD partition/drive" in Veracrypt driver options
3. Right click on the mounted drive letter and go to Properties > Tools > Optimize
4. "Optimize Drives" window will say "Optimization not available" for that drive and won't allow running TRIM on it.

# Screenshots
Drive C and E are on the same SSD. Drive C is encrypted with Bitlcoker, E is encrypted with Veracrypt. TRIM works fine on C, but not on E:

**Note:** The "Last analyzed date" was updated after I ran `defrag E: /L` manually on that drive.

![TRIM](https://github.com/veracrypt/VeraCrypt/assets/27990818/60a29810-e727-451d-bba7-e79c5b886a9c)

# Your Environment

**VeraCrypt version:** 1.25.9
**Operating system and version:** Windows 10 22H2
**System type:** 64-bit

**Comment by thericle** [comment]
What worked for me was to also enable "Allow Windows Disk Defragmenter to defragment non-system partition/drive" below the one you mentioned. It is probably because Windows optimization is a mix of TRIM and defragmentation. (see also: https://www.hanselman.com/blog/the-real-and-complete-story-does-windows-defragment-your-ssd)

**Comment by gashtal** [comment]
@thericle Thank you for the response. Enabling that option you mentioned indeed resolved the problem. Though now it is not clear to me as to what the purpose of the "Allow TRIM command for non-system SSD partition/drive" option is since trim can be run manually on the drive from command line, whether that option is enabled or not. Maybe these two options should be merged into one to avoid confusion in the future.

**Comment by idrassi** [comment]
@gashtal I'm glad to see that the issue was resolved with the help of the community. To clarify things further, let me provide some insights on how the TRIM command works and interacts with Windows and VeraCrypt.

1. Enabling Both Options in VeraCrypt:

The "Allow TRIM command for non-system SSD partition/drive" option in VeraCrypt directly gives permissions for the TRIM command to be used. However, VeraCrypt's implementation of TRIM is not directly tied to Windows' "Optimize Drives" interface, which is why it might not register that TRIM is enabled just by checking this option.

When you also enable the "Allow Windows Disk Defragmenter to defragment non-system partition/drive" option, it opens up the communication between VeraCrypt and Windows' Defragmenter/Optimize Drives tool, which includes TRIM for SSDs. This is why enabling both options allows Windows to recognize that TRIM is available for the VeraCrypt volume.

2. The Defrag Command Line Behavior:

The defrag /L command you ran is designed to invoke the TRIM command on the specified volume. However, when run on a VeraCrypt volume with the TRIM option disabled, the command doesn't actually perform TRIM; instead, it attempts to, sees no error (as the command itself is valid), and reports a successful operation.

The command's output is somewhat misleading in this case. "Total space trimmed" refers to the total space that would have been trimmed if the operation had actually been performed. It's not a confirmation that the space has been trimmed, especially if TRIM is disabled for the volume in VeraCrypt.

As you've found, enabling both options in VeraCrypt allows Windows' defragmentation tool to properly perform TRIM on your SSD partition. Regarding the two options potentially being merged, that's a design consideration and it may be useful to some users to have separate control over these functionalities.

Be aware that using TRIM with encrypted volumes may have some implications on the data security as explained in the documentation: https://veracrypt.fr/en/Trim%20Operation.html

**Comment by bughunter2** [comment]
I was experiencing this problem, but in a slightly different way.

Thought I'd post both my problem and the solution:

**Problem:**

Note that I ran the `defrag /o` command as an administrator.

```
> defrag /o D:

Invoking retrim on EXAMPLE (D:)...


The file move failed. (0x89000016)
```

These VeraCrypt options were enabled at the time:

"Allow TRIM command for non-system SSD partition/drive"

"Allow Windows Disk Defragmenter to defragment non-system partition/drive"

**Solution:**

The Windows built-in `SYSTEM` account was NOT listed in the NTFS ACL permissions. Giving the `SYSTEM` account permissions on the drive fixed it for me. Specifically, giving `Modify` access for `This folder and files` on the root drive was sufficient to let `defrag /o` succeed, since a temporarily file gets created in the root of the drive during the defrag invocation.

**Comment by ducalex** [comment]
> This is why enabling both options allows Windows to recognize that TRIM is available for the VeraCrypt volume.

I think the documentation should be updated to mention that both checkboxes are needed on Windows.

I was lucky to find this closed issue to resolve my problem, but not everybody will!
