### ISSUE TITLE
Documentation on veracrypt.eu out of date

### ISSUE THREAD

**Issue by Jertzukka** [veracrypt/VeraCrypt#1105]
Currently veracrypt.eu/index.html redirects you to veracrypt.fr which is up-to-date, but any search engine for me (Google, DuckDuckGo) will give https://veracrypt.eu/en/Documentation.html as the first search result for "Veracrypt documentation" search query. This site is out of date.

I'd suggest setting up redirection for any page under veracrypt.eu to .fr domain or to keep .eu up-to-date.

**Comment by idrassi** [comment]
Thank you for poiting out this issue. I have synchronized veracrypt.eu documentation with the official one. 
veracrypt.eu is meant to be a mirror so that it serves as a backup in case veracrypt.fr is down. With time, I learnt that search engine have tendency to give more priority to veracrypt.eu because the .eu extension is more generic than the .fr extension which is usually associated with french content.

I will put in place a procedure for better synchronization
