### ISSUE TITLE
Securely erase master key in RAM on Windows shutdown for fully encrypted drives

### ISSUE THREAD

**Issue by sfu82** [veracrypt/VeraCrypt#1159]
Hello,

Maybe I'm wrong, but from what I've read it seems to me that for fully encrypted disks, when shutting down the computer, the private key is not removed from RAM

This leaves a window of opportunity for an attacker to perform a cold boot attack, which can range from several minutes to several hours, preventing an effective "kill switch" in the event of an emergency.

After doing some research I found that there is a program that does this on Linux https://www.kicksecure.com/wiki/Ram-wipe
But I couldn't find anything for Windows

I don't know how complicated it would be to implement this for Windows, maybe near impossible given that the OS is not open source, or it would require crashing it by directly deleting the key from the RAM, to shut it down safely?

**Comment by sfu82** [comment]
I also found this https://en.wikipedia.org/wiki/TRESOR

**Comment by idrassi** [comment]
Hi @sfu82,

You're correct in identifying the potential risk of a cold boot attack, where sensitive data like encryption keys left in RAM could potentially be read after system shutdown. In the context of VeraCrypt, there are measures put in place to mitigate this risk.

- Erasure of System Volume's Master Key: By default, the VeraCrypt driver erases the master key of the system volume during the shutdown process. This step is specifically targeted to remove any trace of the encryption key from memory. The related code can be found [here](https://github.com/veracrypt/VeraCrypt/blob/be5c28c4816189dad5af92ab61d22910b2d00769/src/Driver/DriveFilter.c#L991). Note that in some cases, this action might lead to a BSOD, which is why I've made this functionality configurable to accommodate users who don't wish to have this additional layer of security.

- Erasure of Non-system Volumes' Master Key: When the Windows shutdown process is initiated, all non-system volumes are dismounted. This dismounting process also triggers the erasure of their respective master keys, ensuring any sensitive data they hold is scrubbed from memory.

- RAM Encryption: This is a specific countermeasure to protect against cold boot attacks. When enabled, the master keys of all encrypted volumes, including the system volume, are encrypted based on a key derived from a large memory area (1 MiB). Due to the inherent decay properties of RAM cells, at least one cell in this area will be cleared after just one second of shutdown, making it impossible to correctly derive the RAM encryption keys. A comprehensive technical discussion about RAM encryption is available in this [forum post](https://sourceforge.net/p/veracrypt/discussion/technical/thread/3961542951/#663e).

So, while there are inherent challenges to completely securing a system due to the proprietary nature of some OSes like Windows, I've wored to integrate as many preventative measures as possible in VeraCrypt. By  enabling RAM encryption, you can significantly bolster your defense against cold boot attacks.

**Comment by idrassi** [comment]
P.S. One important note to mention: RAM encryption is disabled by default in VeraCrypt. To enable it, you need to navigate through the software's menus. Please follow this path: "Settings" -> "Performance/Driver Configuration". Here's a screenshot for your reference:

![image](https://github.com/veracrypt/VeraCrypt/assets/4698669/98e64d2e-f90a-41aa-91ab-174a71057bd1)

**Comment by sfu82** [comment]
> Hi @sfu82,
> 
> You're correct in identifying the potential risk of a cold boot attack, where sensitive data like encryption keys left in RAM could potentially be read after system shutdown. In the context of VeraCrypt, there are measures put in place to mitigate this risk.
> 
> * Erasure of System Volume's Master Key: By default, the VeraCrypt driver erases the master key of the system volume during the shutdown process. This step is specifically targeted to remove any trace of the encryption key from memory. The related code can be found [here](https://github.com/veracrypt/VeraCrypt/blob/be5c28c4816189dad5af92ab61d22910b2d00769/src/Driver/DriveFilter.c#L991). Note that in some cases, this action might lead to a BSOD, which is why I've made this functionality configurable to accommodate users who don't wish to have this additional layer of security.
> * Erasure of Non-system Volumes' Master Key: When the Windows shutdown process is initiated, all non-system volumes are dismounted. This dismounting process also triggers the erasure of their respective master keys, ensuring any sensitive data they hold is scrubbed from memory.
> * RAM Encryption: This is a specific countermeasure to protect against cold boot attacks. When enabled, the master keys of all encrypted volumes, including the system volume, are encrypted based on a key derived from a large memory area (1 MiB). Due to the inherent decay properties of RAM cells, at least one cell in this area will be cleared after just one second of shutdown, making it impossible to correctly derive the RAM encryption keys. A comprehensive technical discussion about RAM encryption is available in this [forum post](https://sourceforge.net/p/veracrypt/discussion/technical/thread/3961542951/#663e).
> 
> So, while there are inherent challenges to completely securing a system due to the proprietary nature of some OSes like Windows, I've wored to integrate as many preventative measures as possible in VeraCrypt. By enabling RAM encryption, you can significantly bolster your defense against cold boot attacks.

Thanks for the confirmation that the master key is removed from RAM on shutdown and the reference to the code, I just saw that it was announced for the release of version 1.24

I thought that the RAM encryption was only based on an obfuscation strategy because I had seen this article https://blog.elcomsoft.com/2021/06/breaking-veracrypt-obtaining-and-extracting-on-the-fly-encryption-keys/

So I hadn't enabled it, now I understand and just enabled it, it can probably also protect against some software's core dumps if they captured a small part of the private key, since it's longer. I've disabled Windows core dumps (BSOD), but since all software has unrestricted RAM read access, we're never sure (in addition to other log-based attack techniques), that's why full system disk encryption is a good option, in addition to additional encryption of files (on the system disk or not)

It would be really great to have a "protected part" of RAM that only VeraCrypt can access, but I know that's unrealistic due to the way Windows is designed (maybe it's possible to do this, but it must be a real challenge, otherwise you would have done it already)

**Comment by midnightcruising** [comment]
> P.S. One important note to mention: RAM encryption is disabled by default in VeraCrypt. To enable it, you need to navigate through the software's menus. Please follow this path: "Settings" -> "Performance/Driver Configuration". Here's a screenshot for your reference:
> 
> ![image](https://user-images.githubusercontent.com/4698669/256972398-98e64d2e-f90a-41aa-91ab-174a71057bd1.png)

Curious, is there a reason that RAM encryption isn't on the stable version on Linux?

I ask because I'm trying to find a way to write to RAM directly on Linux and I am lost on how to write to RAM, let alone encrypt keys in RAM.
