### ISSUE TITLE
"Error: The character can't be parsed during volume encryption"

### ISSUE THREAD

**Issue by iamrrv01** [veracrypt/VeraCrypt#1166]
When attempting to encrypt a volume with VeraCrypt, the password input fails, displaying an error message stating "The character can't be parsed." This is likely caused by special characters in the password being misinterpreted during the encryption process.

# Expected behavior
The expected behavior is that VeraCrypt should accept the provided password, including special characters, without any parsing issues, and successfully encrypt the volume.

# Observed behavior
Instead of the expected behavior, when attempting to encrypt the volume, VeraCrypt displays an error message stating "The character can't be parsed." This indicates that there is an issue with how the password, particularly special characters, is being processed by VeraCrypt during encryption.

# Steps to reproduce
1. Prepare a text file named "veracrypt_password.txt" in the same directory as the batch script.
2. In "veracrypt_password.txt," enter a password that contains special characters (e.g., "&", "<", ">", "|", "!"). Save the file.
3. Execute the batch script, which includes the following code:

```
set "veracrypt_password="
for /f %%i in (veracrypt_password.txt) do set "veracrypt_password=%%~i"

echo The password is: %veracrypt_password%

rem Step 4: Encrypt the disk with VeraCrypt settings
set "aes_algorithm=AES"

veracrypt /v \Device\Harddisk%disk_number%\Partition1 /aenc=!aes_algorithm! /p "%veracrypt_password%" /fs=ntfs /quick /q /s
```
1. Observe the execution of the script and the output.

2. The script may display an error message such as "The character can't be parsed" during the VeraCrypt encryption attempt.

# Screenshots
![image](https://github.com/veracrypt/VeraCrypt/assets/51211511/629106dd-c849-443e-a074-68f82067b613)

# Your Environment

Please tell us more about your environment

**VeraCrypt version:** 1.25.9

**Operating system and version:**  Windows 11 Version, Build 22621

**System type:**  64-bit

**Comment by idrassi** [comment]
Hi,

Thank you for the detailed report. It appears there are a couple of concerns we need to address with the provided batch script:

1. **Special Characters Handling in Batch**:
 
The reported issue seems to stem from the way special characters are being handled in the batch script. In batch scripts, characters like `&`, `<`, `>`, `|`, and `!` have special meanings and need to be treated carefully.

Here's a modified version of your code snippet:

```batch
setlocal enabledelayedexpansion
set "veracrypt_password="
for /f %%i in (veracrypt_password.txt) do set "veracrypt_password=%%~i"

echo The password is: !veracrypt_password!

rem Step 4: Encrypt the disk with VeraCrypt settings
veracrypt /v \Device\Harddisk%disk_number%\Partition1 /aenc=!aes_algorithm! /p "!veracrypt_password!" /fs=ntfs /quick /q /s
```
By enabling `setlocal enabledelayedexpansion` and using the !variable! notation, this version should handle special characters appropriately.

2. **Unsupported Switches**:

I noticed that you're using switches `/aenc` and `/fs` in your script. These switches are not supported by either VeraCrypt.exe or VeraCrypt Format.exe. Therefore, even after addressing the special characters issue, the script will not work due to these unsupported switches.

Please adjust your script with the suggested changes and review the way you are calling VeraCrypt executables.

**Comment by iamrrv01** [comment]
Hi Idrassi, 
Thank you very much for pointing out the problems in the snippet. However, I wonder if can also point me the right direction to perform steps as I am really having trouble understanding how does veracrypt parse command line!

Steps I want to execute:
1. Select the target harddisk, volume and partition
2. Create a non-system partition/drive (Standard Veracrypt volume)
3. selecting the volume 
4. set password
5. Select the encryption algorithm and hash
6. format file system as NTFS and quick format it.

My current snippet is:

```
setlocal enabledelayedexpansion
set "veracrypt_password="
for /f %%i in (veracrypt_password.txt) do set "veracrypt_password=%%~i"

echo The password is: !veracrypt_password!

rem Step 4: Encrypt the disk with VeraCrypt settings
veracrypt /v \Device\Harddisk1\Partition2 /encryption=AES /p "!veracrypt_password!" /filesystem=ntfs /quick
```

**Comment by idrassi** [comment]
I understand your want to script the creation of a volume but there are certain elements that you need to consider:

1. **Windows Constraints**:
   - `VeraCrypt.exe`: Meant only for mounting volumes on Windows, not creating them.
   - `VeraCrypt Format.exe`: Command-line on Windows supports only file container creation, not disk encryption. Thus, it's not possible to accomplish your desired steps via a batch script on Windows. It's technically feasible to add support for disks in the command line of "VeraCrypt Format," but it requires significant work and, currently, there's not enough demand for this feature. 

2. **Admin Privileges Requirement**:
Encrypting a disk or partition inherently requires administrative privileges due to the low-level access needed for the operation. Consequently, even if you were to use a script, that script must be executed with elevated permissions which means running the script with User Account Control (UAC) admin rights.

3. **Linux Possibility**:
If scripting this process is crucial, you might want to consider using Linux. On Linux, the `veracrypt` executable handles both mounting and creating volumes, including encrypting disks.

I hope this clarifies things to you.
