### ISSUE TITLE
RandomNumberGenerator does not necessarily read stated 32 bytes from /dev/random

### ISSUE THREAD

**Issue by lujobi** [veracrypt/VeraCrypt#1187]
@lavode, @simonstuder noticed that currently, the Random number generator does not necessarily read the promised 32 bytes from `/dev/random`. Supposedly this is fixed in [VeraCrypt_1.24-Update7](https://github.com/veracrypt/VeraCrypt/releases/tag/VeraCrypt_1.24-Update7). However, these changes do not bring the desired effect. 

# Expected behavior
As written in the comment  `src/Core/RandomNumberGenerator.cpp:L52` "ensure that we have read at least 32 bytes from /dev/random before allowing it to fail gracefully".

# Observed behavior
Taking a look at `src/Core/RandomNumberGenerator.cpp:L53`:
```cpp
//...
while (true)
{
	int rndCount = read (random, buffer, buffer.Size());
	throw_sys_sub_if ((rndCount == -1) && errno != EAGAIN && errno != ERESTART && errno != EINTR, L"/dev/random");
	if (rndCount == -1 && (!DevRandomSucceeded || (DevRandomBytesCount < 32)))
	{
		// wait 250ms before querying /dev/random again
		::usleep (250 * 1000);
	}
	else
	{
		if (rndCount != -1)
		{
			// We count returned bytes untill 32-bytes treshold reached
			if (DevRandomBytesCount < 32)
				DevRandomBytesCount += rndCount;
			DevRandomSucceeded = true;
		}
		break;
	}
}
//...
```

As per [read(2) — Linux manual page](https://man7.org/linux/man-pages/man2/read.2.html) `read` returns the bytes read to the buffer.
Suppose `rndCount` equals to 3 after the first read. Via a small detour, the code flow reaches the break statement having only read 3 bytes from `/dev/random`.

We assume that the intended implementation would look similar to the following suggestion:

```cpp
//...
DevRandomBytesCount = 0;
while (true)
{
	int rndCount = read (random, buffer + DevRandomBytesCount, buffer.Size() - DevRandomBytesCount);
	throw_sys_sub_if ((rndCount == -1) && errno != EAGAIN && errno != ERESTART && errno != EINTR, L"/dev/random");
	if (rndCount == -1)
		::usleep (250 * 1000);
	else
	{
		DevRandomBytesCount += rndCount; 
		if (DevRandomBytesCount >= 32)
			break;
	}
}
```

# Your Environment
n.a.

**Comment by idrassi** [comment]
Thank you for bringing up this issue and for the detailed analysis.

First, let me clarify the original design intentions:

- `DevRandomSucceeded`: This flag indicates whether we've successfully read from /dev/random at least once during the lifetime of the random generator. Once set to true, it remains true.
- `DevRandomBytesCount`: This variable keeps a cumulative tally of the bytes read from /dev/random. The aim is to ensure that at least 32 bytes are read across the random generator's lifetime, not necessarily in a single call.

The existing code logic reflects these aims:
```cpp
if (rndCount == -1 && (!DevRandomSucceeded || (DevRandomBytesCount < 32)))
{
    ::usleep (250 * 1000);  // Wait 250ms before re-attempting to read from /dev/random
}
```

The code will only retry reading from /dev/random if either the read has never succeeded before (!DevRandomSucceeded) or if fewer than 32 bytes have been read (DevRandomBytesCount < 32).

This design aims to balance security and performance. It's important to note that VeraCrypt uses multiple sources of entropy, not just /dev/random, to ensure robust randomness.

However, I understand the importance of allowing users greater control in this aspect. Therefore, I propose to offer users three choices:

- Current Implementation: Read at least one byte from /dev/random on each call, and only retry if less than 32 bytes have been read during the lifetime of the random generator.
- Intermediate Solution: Force the first read operation from /dev/random to fetch at least 32 bytes, ignoring any subsequent read failures. This will only potentially slow down the initial call.
- Your Proposal: Enforce that every read operation from /dev/random must return at least 32 bytes. This offers maximum security but may result in delays due to low system entropy.

What are your thoughts on this approach?

**Comment by Lavode** [comment]
@idrassi appreciate the timely feedback. :)

With your explanation of what the design goal is we agree that the code does do what it sets out to do. However we believe in this case the conditional expression can be simplified a bit.

Assume `AddSystemDataToPool` is invoked and the first read of `/dev/random` failed, thus `rndCount == -1`. Then this is the full space of possibilities:

| Succeded once during lifetime? | Read x bytes during lifetime | Retry read? |
| ------------------------------ | ---------------------------- | ----------- |
| TRUE                           | < 32                         | TRUE        |
| TRUE                           | >= 32                        | FALSE       |
| FALSE                          | < 32                         | TRUE        |
| FALSE                          | >= 32                        | TRUE        |

Of these possibilities, the last one cannot be reached in a real execution: It is impossible to have read at least 32 bytes from `/dev/random` without having succeeded at least once. More formally, `!DevRandomSucceeded` implies `DevRandomBytesCount < 32`. Thus we are left with this:

| Succeded once during lifetime? | Read x bytes during lifetime | Retry read? |
| ------------------------------ | ---------------------------- | ----------- |
| TRUE                           | < 32                         | TRUE        |
| TRUE                           | >= 32                        | FALSE       |
| FALSE                          | < 32                         | TRUE        |

That is the condition  `(!DevRandomSucceeded || (DevRandomBytesCount < 32))` simplifies to  `DevRandomBytesCount < 32`.

Thus the below ought to be equivalent:
```cpp
	if (rndCount == -1 && (DevRandomBytesCount < 32))
	{
		// wait 250ms before querying /dev/random again
		::usleep (250 * 1000);
	}
	else
	{
		if (rndCount != -1)
		{
			// We count returned bytes untill 32-bytes threshold reached
			if (DevRandomBytesCount < 32)
				DevRandomBytesCount += rndCount;
		}
		break;
	}
```

Arguably it might be easier to mentally parse this by handling the 'happy cases' (read succeeded, or read failed but we have enough randomness) first:
```cpp
    if (rndCount != -1) {
        // We count returned bytes untill 32-bytes threshold reached
        if (DevRandomBytesCount < 32)
            DevRandomBytesCount += rndCount;
        break;
    }
    else if (DevRandomBytesCount >= 32) {
        // /dev/random failed gracefully, we have enough bytes
        break;
    }
    else {
        // wait 250ms before querying /dev/random again
        ::usleep (250 * 1000);
    }
```

Regarding your proposals: I'm not sure there's a large enough benefit to allow users to customize this low-level detail to justify making the code more complex. All three possibilities seem perfectly reasonable, given a) it's not the only source of entropy and b) on the vast majority of modern Unix devices `/dev/random` is non-blocking anyway, so this is an edge case at most.

As such I'd just advise to pick whatever tradeoff seems sane to you, and go with it.

**Comment by idrassi** [comment]
@Lavode: Thank you for your detailed analysis, and for your thoughtful response.

First, your observation about the conditional expression is absolutely correct.This was a great catch and serves to make the code simpler and easier to read. I'm in favor of implementing your suggested change to streamline the logic and make it more transparent.

As for your comments about my previous proposals for user-controlled options, I appreciate your nuanced view. I also agree that adding further complexity to allow for user-customizable entropy sources might not necessarily be warranted.

I'm inclined to go ahead and implement your proposed simplification.
Would you like to create a Pull Request for your changes, or shall I go ahead and implement them?

**Comment by wendig0x** [comment]
@idrassi I think the ability to hard-customize for power users is essential. Maybe we should add one button that opens the possibility of fine-tuning?

**Comment by Lavode** [comment]
Sorry, was kept busy. Thanks for changing it. :+1:
