### ISSUE TITLE
Icons corruption on macOS ventura

### ISSUE THREAD

**Issue by sardanap** [veracrypt/VeraCrypt#1218]
On macOS ventura 13.6 slot icons do not display properly

screenshot here:

<img width="688" alt="Screenshot 2023-10-01 at 23 37 42" src="https://github.com/veracrypt/VeraCrypt/assets/4921759/2f8843da-565e-470d-8a33-bf28d6a3d142">

VeraCrypt version 1.26.7

**Comment by Jertzukka** [comment]
It looks like only the top part that should be hidden by the bitmap mask is the only part visible. The code regarding this hasn't been touched since 9 years, so the culprit would most likely be the upgrade of wxWidgets to the latest Stable.

It looks like there has been a change in how wxWidget's OSX version handles the mask (see https://github.com/wxWidgets/wxWidgets/commit/8403b79ad71693cbff3e8c5005fee33cafb48eff), so when we create the bitmap mask, we probably need to separate this part for OSX and change it to `(image.ConvertToMono (255, 255, 255), 1)` possibly?

https://github.com/veracrypt/VeraCrypt/blob/5b5af85dbf47d962a5a2c0c13c9e64ae995c3810/src/Main/Resources.cpp#L192-L193

Unfortunately I don't have a MacOS system to test and troubleshoot this further.

**Comment by sardanap** [comment]
i'm able to compile it for macOS and i can test it.

If you post here a patch i can try it

**Comment by Jertzukka** [comment]
This is my (un)educated guess on the fix:
```
diff --git a/src/Main/Resources.cpp b/src/Main/Resources.cpp
index d9a787a5..e65b5026 100644
--- a/src/Main/Resources.cpp
+++ b/src/Main/Resources.cpp
@@ -190,7 +190,11 @@ namespace VeraCrypt
 		image.Resize (wxSize (16, 12), wxPoint (0, 0));
 
 #	ifdef __WXGTK__
+#		ifdef TC_MACOSX
+		return wxBitmap (image, 1);
+#		else
 		return wxBitmap (image.ConvertToMono (0, 0, 0), 1);
+#		endif
 #	else
 		return wxBitmap (image);
 #	endif
```
Copy this into a text file, save it as mask.patch and run `git apply mask.patch` in the git root. I appreciate if you're able to compile and test the patch to see whether it works.

**Comment by sardanap** [comment]
It does not work, i think it's because WXGTK is a linux-only thing.
Given my limited abilities with c++ here is a supposedly working "fix"
`diff --git a/src/Main/Resources.cpp b/src/Main/Resources.cpp
index d9a787a5..58030c1e 100644
--- a/src/Main/Resources.cpp
+++ b/src/Main/Resources.cpp
@@ -189,7 +189,7 @@ namespace VeraCrypt
                wxImage image (stream);
                image.Resize (wxSize (16, 12), wxPoint (0, 0));
 
-#      ifdef __WXGTK__
+#      if defined  __WXGTK__ || defined TC_MACOSX
                return wxBitmap (image.ConvertToMono (0, 0, 0), 1);
 #      else
                return wxBitmap (image);`

**Comment by sardanap** [comment]
It does not work and i think it's because WXGTK is a linux-only thing.
Given my limited c++ abilities here is a "it works for me" fix


diff --git a/src/Main/Resources.cpp b/src/Main/Resources.cpp
index d9a787a5..58030c1e 100644
--- a/src/Main/Resources.cpp
+++ b/src/Main/Resources.cpp
@@ -189,7 +189,7 @@ namespace VeraCrypt
                wxImage image (stream);
                image.Resize (wxSize (16, 12), wxPoint (0, 0));
 
-#      ifdef __WXGTK__
+#      if defined  __WXGTK__ || defined TC_MACOSX
                return wxBitmap (image.ConvertToMono (0, 0, 0), 1);
 #      else
                return wxBitmap (image);

**Comment by idrassi** [comment]
Thank you @Jertzukka for pinpointing the problematic code. And kudos to @sardanap for refining and testing the patch! This is teamwork at its finest 👍

It appears that earlier versions of wxWidgets had platform-specific behaviors between Linux and macOS. Now they've standardized their implementation across all platforms and so this regression happened.

@sardanap: would you kindly create a PR with your fix?
