### ISSUE TITLE
[SOLVED] VeraCrypt crashes on Linux KDE Neon 5.27 at the end of compilation when using big file system (more than 4 GB, not "Fat")

### ISSUE THREAD

**Issue by NitramO-YT** [veracrypt/VeraCrypt#1234]
VeraCrypt crashes on Linux KDE Neon 5.27 at the end of compilation when using big file system (more than 4 GB, not "Fat")

# Expected behavior
It should finish compiling correctly and work normally...

# Observed behavior
It crashes.

# Steps to reproduce
1. Open VeraCrypt.
2. Click on "Make a volume".
3. Follow the steps and chose a big volume size when asked (like 10Gb).
4. Check "Yes" when it ask if you will have files of size over 4Gb.
5. Click "Next".
6. Let "Linux Ext3" (or Ext4 or even NTFS).
7. Check "I will mount the volume on other platforms".
8. Click "Next" and then format it.
9. Here is the crash!

# Screenshots
![image](https://github.com/veracrypt/VeraCrypt/assets/61696199/0cdcbee3-d5fd-4fb1-9b42-1897a87bba8f)

# Your Environment

Please tell us more about your environment

**VeraCrypt version:** 1.26.7

**Operating system and version:** Linux KDE Neon 5.27 (Plasma 5.27.8, Kernel 6.2.0-34-generic, 64 Bit)

**System type:** 64-bit

**Comment by idrassi** [comment]
I installed a fresh Linux KDE Neon 5.27, and then I installed VeraCrypt using the Ubuntu 22.04 .deb package. Afterwards, I launched VeraCrypt from the KDE search bar and followed your exact steps to create a 10GiB file container. When the progress bar for volume creation reached 100%, a dialog appeared requesting the administrator password. Once entered, the volume creation finished successfully.

Based on your screenshot, the administrator password was not requested, and you experienced a crash directly.

Since I cannot reproduce this issue, there must be some specific elements in your configuration that trigger the problem, and we need to identify them.

Is the account you are using part of the sudo group? For instance, can you run commands using sudo from Konsole?
Did you use the same .deb package as I did?
Are there any other specifics I might have missed?

**Comment by NitramO-YT** [comment]
OMG Yes, thank you, it was only the version, i don't even know which one i had and don't remember how i installed it, but i removed everything related to Veracrypt and installed the Ubuntu 22.04 .deb package, and now it works, thanks!

**Comment by ticklemyIP** [comment]
@idrassi I had the same issue on Fedora Workstation 38 and still have it on the latest TailsOS release. I have installed/extracted both via the generic installer before. This error occured on both when trying to create a volume and trying to unlock one. Using `sudo` solved the issue on Fedora.

It is possible that the generic installer (not the CentOS 8/Fedora 38 `.dnf`) tries to use the Debian (and Ubuntu) specific `sudoers` group for root, meanwhile Fedora uses the `wheel` group? After uninstalling the generic, then installing the `.dnf` package on Fedora, it works fine.

The TailsOS issue might relate to whether or not the user set up and Administrator password at the beginning. I did not have one set up when testing the generic installer on Tails. Might be worth trying.

**Comment by idrassi** [comment]
Thank you @ticklemyIP for the detailed feedback. There seems to be an issue with the sudo use by VeraCrypt in the latest version, because I also received a similar report on Sourceforge affecting Linux Mint: https://sourceforge.net/p/veracrypt/discussion/technical/thread/97a6d5759c/

What's amazing is that I cannot reproduce it on Ubuntu/Debian. I have already conducted tests on CentOS without any issues, but I will try again on a clean VM.

**Comment by idrassi** [comment]
Thanks to details shared by the user on the Sourceforge forum, I was able to understand the cause of the crash: it is due to the use of the generic GTK2 installer on GTK3-based Linux distributions.

Actually, in the generic installer archive, there are two GUI installer files:

- veracrypt-1.26.7-setup-gui-x64
- veracrypt-1.26.7-setup-gtk3-gui-x64

The first installer is for the legacy GTK2, while the second installer is for the newer GTK3 (as indicated in its name).

Newest CentOS/Fedora/TailsOS distributions are based on GTK3, and therefore, one should be using the GTK3 installer. Since all modern Linux distributions now use GTK3, the GTK2 installer is reserved for legacy systems.

The crash occurs due to an issue affecting GTK2 calls on GTK3 systems. This use case isn't part of VeraCrypt's official testing, which is why I never detected it.

So, the solution is simple: just use the GTK3 generic installer, and the crash will be resolved!

**Comment by rafaelazvdo** [comment]
> So, the solution is simple: just use the GTK3 generic installer, and the crash will be resolved!

I had the same problem on Linux Mint 21.2, I use Veracrypt from the executable saved on a flash drive and the executable file generated by the veracrypt-1.26.7-setup-gui-x64 installer always gave problems when trying to create new volumes and even mount existing volumes, but using the installer for gtk3, the executable ran normally from the flash drive.
