### ISSUE TITLE
Winload.efi missing Windows 8.1 can't boot or mount.

### ISSUE THREAD

**Issue by RobInOut** [veracrypt/VeraCrypt#124]
I need some help.

I encrypted my system volume (windows 8.1 GPT) and did not backup the rescue disk file. I passed the test successfully and shutdown my PC couple hours later. I rebooted my PC 1 hour after to find this message :
[imgur.com/BySsUF7.jpg](url)

"winload.efi is missing or corrupt". Since I'm on Windows 8.1 (fast startup is enabled by default) also I can't open the CMD since I can't restart while holding shift... So I download a Windows 8 bootable image and tried to repair my computer and open CMD and try to shutdown fully the PC but it would not recognize the command.

I booted linux mint on another usb and  tried to open Veracrypt with the primary partition of Windows and it was not allowing me since Windows is hibernate. I tried this : http://superuser.com/questions/1115813/cannot-mount-veracrypt-partition-on-linux-mint-metadata-kept-in-windows-cache

and no help. 

I can't afford to lose the data :( please help me

**Comment by RobInOut** [comment]
Edit : Got access to my data I will post how very soon but I can't seem to boot from the Rescue Disk . I unzipped the folder into my USB and put like this : C:/Efi and tried to boot it but it;s not detecting an OS

**Comment by idrassi** [comment]
This is a typical problem for some machine brands  (e.g Acer, HP) where the BIOS removes VeraCrypt entry from boot menu and it forces the system to boot using Windows loader. Of course, this causes the problem that you have since the system partition is encrypted and its content can not be access by Windows loader.

That's why VeraCrypt forces a shutdown during Pre-Test to detect such cases but I guess you rebooted manually without shutting down and that's why the problem appeared after your shutdown the machine.

Concerning the Rescue Disk, does it display its menu with available options or you just can't boot on it?
Are you sure the USB when you unzipped the Rescue Disk is formatted using FAT32? if it is NTFS, it is normal that it doesn't work.

**Comment by RobInOut** [comment]
It was Fat32 and it could not even detect anything. Thank god I got access to everything and formatted and put windows 7. No problems at all with windows 7 right?

**Comment by idrassi** [comment]
It's strange that the boot USB disk could not detected. Usually, you can always overwrite the boot using the BIOS menu by going to the boot order panel and choose the USB disk there.
If the Rescue Disk USB is not visible, this means that there is some other issue related to USB boot with your machine.

As for Windows 7, did you install it on UEFI mode or did you format your disk using MBR?
Classic MBR boot doesn't suffer from this issue since all motherboards I know of let you choose freely the MBR bootloader you want to install.

**Comment by RobInOut** [comment]
I formatted it in MBR. I hope I am good to go?!

**Comment by lurepheonix** [comment]
Guys. How come you restored access to your data? Having the same issue.
Windows 10, UEFI. Cannot even mount/use the system partition with command line.
