### ISSUE TITLE
Automatically start script on mount/unmount 

### ISSUE THREAD

**Issue by snakems** [veracrypt/VeraCrypt#131]
I propose to do so:
VeraCrypt after successfully mounting search script in container's root **mount.bat**/**mount.sh** and if exists run it.
Before unmounting search script in container's root **unmount.bat**/**unmount.sh** and if exists run it.

**Comment by dmitryd** [comment]
I have a use case for this feature. There can be sensitive information on encrypted drives that can be used buy word processing applications, etc. This leaves traces in temporary directories in autorecovery directories. Such information has to be cleaned up. Having an unmount script may help. May be, path to the script can be specified in the disk header for better security.

**Comment by nedex** [comment]
Also because of this: [apple's 'quicklook' cache may leak encrypted data](https://objective-see.com/blog/blog_0x30.html)
Launching a script with `qlmanage -r cache` may be interesting.

+1

**Comment by dmitryd** [comment]
There is a whole set of clean up actions that have do be done in macOS in order to clean all traces of opened files. macOS will record a lot of information about the mounted drive and its files:

- Name of the mounted VeraCrypt volume
- Location of the volume directory (if it is on the internal disk)
- Paths to all open files from the VeraCrypt volume (so if you have `/Volumes/FreedomForSyria/AboutChemicalAttacks.doc`, it will be recorded by macOS and it can be found that you worked on it)
- Thumbnails of all images, videos and PDFs

And sometimes other information. So it needs a thorough clean up script after unmounting VeraCrypt volume in macOS.

**Comment by chscherrer** [comment]
I would love to run a script or executable after mounting. My sync program always gets stuck, because running before mounting. This shouldn't be too difficult to implement?

**Comment by Foresteam** [comment]
Isn't this implemented still?
