### ISSUE TITLE
Add Ubuntu 24.04 LTS Binary

### ISSUE THREAD

**Issue by justanotherscript** [veracrypt/VeraCrypt#1335]

**Comment by idrassi** [comment]
Ubuntu 24.04 packages are available at https://veracrypt.fr/en/Downloads.html

Ubuntu 24.04 packages are available at https://veracrypt.fr/en/Downloads.html and also on Github Release.

Ubuntu 24.04 packages now depend directly on libgtk3 because the wxWidgets version that ships with Ubuntu 24.04 causes the VeraCrypt GUI to crash in text mode (`veracrypt --text`). This bug was fixed in wxWidgets 3.2.5. So, the binaries for Ubuntu 24.04 are linked statically with wxWidgets to work around this issue.
