### ISSUE TITLE
Hidden partition detection.

### ISSUE THREAD

**Issue by hardhub** [veracrypt/VeraCrypt#139]
Please correct me if I am wrong.

VeraCrypt documentation (on codeplex) says that hidden partition will not be overwritten.
So data of hidden volume will not be lost...

But in this case it will eat space... so to detect if disk contains hidden volume we need simply check available space. With filling whole disk with junk data we can estimate how much data can be written to it and how much is "missing". This missing size will be size of hidden volume (or multiple hidden volumes).

Is it not true?

**Comment by mhogomchungu** [comment]
It is not true.

There are two volumes,the outer volume and the inner/hidden volume.

The hidden volume starts from somewhere in the middle of the drive and covers the rest of the drive and it is not aware of the outer volume.

The outer volumes starts from the beginning of the drive and covers THE WHOLE drive,including the hidden volume. The outer volume is completely unaware of the hidden volume.

It is not possible to know if a volume has a hidden volume simply by looking at it or simply by unlocking the outer volume and then looking around. Unlocking ONLY an outer volume and filling it up will silently destroy the hidden volume because,again,the outer volume has no knowledge of the existence of the hidden volume.VeraCrypt itself will have no knowledge of the hidden volume and hence will make no attempts to protect it.

To protect the hidden volume,you have to unlock both the outer volume and the hidden volume and VeraCrypt internally will keep track of all writes to the outer volume and will reject all write attempts to areas in the outer volume that are inside the  hidden volume area and this is how the hidden volume will be protected.

The only way to detect and protect a hidden volume is to unlocking it and it is not possible to detect it simply by looking at an unlocked drive or looking at an unlocked outer volume.

**Comment by hardhub** [comment]
> Unlocking ONLY an outer volume and filling it up will silently destroy the hidden

From docs: 
> Note that you can save data to the decoy system partition anytime without any risk that the hidden volume will get damaged (because the decoy system is not installed in the outer volume — see below).

So it is still not solved...

**Comment by mhogomchungu** [comment]
My explanation above are in agreement with veracrypt documentation here[1].

You seem to get your documentation from here[2]

I have attached below image for convenience since its already on documentation page [2].

Well,if you are running the decoy operating system and you store data on the decoy operation system partition,then you will not run the risk of damaging the second partition where a normal veracrypt volume resides together with the hidden operation system.

The two partitions are visible and its possible for data to "flow over" to the second partition and damage it when the first one is full.

If you unlock the outer veracrypt volume on the second partition and write too much data on it,then you will run a risk of damaging the hidden volume on that partition that contains the hidden operating system(This scenario is the one i explained in my first comment).

![image_034](https://cloud.githubusercontent.com/assets/3496115/23905925/a1fcc4b4-08dd-11e7-9e69-8ebf848a5bfd.png)



[1] https://veracrypt.codeplex.com/wikipage?title=Hidden%20Volume

[2] https://veracrypt.codeplex.com/wikipage?title=VeraCrypt%20Hidden%20Operating%20System

**Comment by hardhub** [comment]
Nice image, it is clear now... 
Decoy operating system is not in outer volume.
But maybe docs should strongly specify that using of outer volume can damage hidden volume.
