### ISSUE TITLE
failed update Fedora veracrypt broken dependencies 

### ISSUE THREAD

**Issue by gh4rv5** [veracrypt/VeraCrypt#1419]
trying to run "dnf update" the system can't go on because of the broken dependencies:
```
Error: 
 Problem: problem with installed package veracrypt-1.26.14-1.x86_64
  - veracrypt-1.26.14-1.x86_64 from @System  does not belong to a distupgrade repository
  - nothing provides libwx_baseu-3.0.so.0()(64bit) needed by veracrypt-1.26.7-1.x86_64 from rpmsphere
  - nothing provides libwx_baseu-3.0.so.0(WXU_3.0)(64bit) needed by veracrypt-1.26.7-1.x86_64 from rpmsphere
  - nothing provides libwx_gtk3u_core-3.0.so.0()(64bit) needed by veracrypt-1.26.7-1.x86_64 from rpmsphere
  - nothing provides libwx_gtk3u_core-3.0.so.0(WXU_3.0)(64bit) needed by veracrypt-1.26.7-1.x86_64 from rpmsphere
  - nothing provides libwx_gtk3u_core-3.0.so.0(WXU_3.0.5)(64bit) needed by veracrypt-1.26.7-1.x86_64 from rpmsphere
  - nothing provides libwx_gtk3u_adv-3.0.so.0()(64bit) needed by veracrypt-1.26.7-1.x86_64 from rpmsphere
  - nothing provides libwx_gtk3u_adv-3.0.so.0(WXU_3.0)(64bit) needed by veracrypt-1.26.7-1.x86_64 from rpmsphere
(try to add '--skip-broken' to skip uninstallable packages)

```
even trying to add the "--skip-broken" option, the message is the same

"sudo dnf update" or "sudo dnf distrosync" or "sudo dnf distrosyn --skip-broken"

**VeraCrypt version:** veracrypt-1.26.14-1.x86_64

**Operating system and version:** Linux Fedora Workstation 40 64-bit

**Comment by idrassi** [comment]
The official VeraCrypt RPM package [veracrypt-1.26.14-CentOS-8-x86_64.rpm](https://launchpad.net/veracrypt/trunk/1.26.14/+download/veracrypt-1.26.14-CentOS-8-x86_64.rpm) doesn't contain any references to wxWidgets libraries since it is statically linked against them, and the RPM package doesn’t include them (you can run `ldd /usr/bin/veracrypt` to confirm this on your side).

Moreover, I have just installed Fedora 40 on a VM, installed the VeraCrypt package, and then ran `sudo dnf update`. It was able to update the system without any errors or warnings about wxWidgets libraries like the ones mentioned in your report.

Although the package mentions CentOS 8, it is definitely compatible with Fedora 40.

Therefore, either you are not using the official VeraCrypt RPM package, or something else on your Fedora machine has caused issues with dependencies.

I encourage you to remove the VeraCrypt package you currently have installed and then install the official one from the VeraCrypt website.

**Comment by idrassi** [comment]
I have created an official build of VeraCrypt for Fedora 40 and the links are available on the official download page: [https://veracrypt.fr/en/Downloads.html](https://veracrypt.fr/en/Downloads.html).

The RPM packages are also available on the GitHub release page for version 1.26.14:

- [veracrypt-1.26.14-Fedora-40-x86_64.rpm](https://github.com/veracrypt/VeraCrypt/releases/download/VeraCrypt_1.26.14/veracrypt-1.26.14-Fedora-40-x86_64.rpm) ([PGP Signature](https://github.com/veracrypt/VeraCrypt/releases/download/VeraCrypt_1.26.14/veracrypt-1.26.14-Fedora-40-x86_64.rpm.sig))
- [veracrypt-console-1.26.14-Fedora-40-x86_64.rpm](https://github.com/veracrypt/VeraCrypt/releases/download/VeraCrypt_1.26.14/veracrypt-console-1.26.14-Fedora-40-x86_64.rpm) ([PGP Signature](https://github.com/veracrypt/VeraCrypt/releases/download/VeraCrypt_1.26.14/veracrypt-console-1.26.14-Fedora-40-x86_64.rpm.sig))

I will close this issue. Please feel free to reopen if you encounter any problems with the official VeraCrypt rpm packages.

**Comment by gh4rv5** [comment]
Thank you @idrassi !
I tested the new package and it seems the system can be updated by doing "dnf update", but if I run "dnf distrosync", I got the exactly same error I've shown in the first message.

**Comment by KaJakKrzysztof** [comment]
Links above provide bad packages:

[veracrypt-1.26.14-Fedora-40-x86_64.rpm](https://github.com/veracrypt/VeraCrypt/releases/download/VeraCrypt_1.26.14/veracrypt-1.26.14-Fedora-40-x86_64.rpm) ([PGP Signature](https://github.com/veracrypt/VeraCrypt/releases/download/VeraCrypt_1.26.14/veracrypt-1.26.14-Fedora-40-x86_64.rpm.sig))
    [veracrypt-console-1.26.14-Fedora-40-x86_64.rpm](https://github.com/veracrypt/VeraCrypt/releases/download/VeraCrypt_1.26.14/veracrypt-console-1.26.14-Fedora-40-x86_64.rpm) ([PGP Signature](https://github.com/veracrypt/VeraCrypt/releases/download/VeraCrypt_1.26.14/veracrypt-console-1.26.14-Fedora-40-x86_64.rpm.sig))
    
 After installing first, GUI is installed.
 After trying to install second without uninstalling first:
 
sudo dnf install 'https://launchpad.net/veracrypt/trunk/1.26.14/+download/veracrypt-console-1.26.14-Fedora-40-x86_64.rpm'
Last metadata expiration check: 2:48:39 ago on Sun 06 Oct 2024 09:18:40 PM CEST.
veracrypt-console-1.26.14-Fedora-40-x86_64.rpm                                                                                                                                 13 MB/s | 7.8 MB     00:00
Package veracrypt-1.26.14-1.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!


So after uninstalling first just to test whats in second, the second installs and provides GUI instead of console
