### ISSUE TITLE
Linux: Build results in binary with executable stack

### ISSUE THREAD

**Issue by lachs0r** [veracrypt/VeraCrypt#146]
rpmlint’s complaint sums it up:
The `veracrypt` binary declares the stack as executable.  Executable stack is usually an error as it is only needed if the code contains GCC trampolines or similar constructs which uses code on the stack.  One common source for needlessly executable stack cases are object files built from assembler files which don't define a proper `.note.GNU-stack` section.

Needless to say no security-relevant application should ever have an executable stack.

**Comment by idrassi** [comment]
Thank you for pointing this out.
This was caused by the fact that crypto assembly files were missing the GNU-stack note.
The following commit fixes this issue: https://github.com/veracrypt/VeraCrypt/commit/ba1fbb688edf7db0edf3ea9d24a95d5a5ef2260c

Feel free to reopen the issue in case you still encounter it.
