### ISSUE TITLE
RHEL6 doesn't support creating volumes greater than 2Tb

### ISSUE THREAD

**Issue by thorntonr** [veracrypt/VeraCrypt#149]
KernelCryptoServiceTestFailed -- seems to be the error thrown on RHEL6 if we try to create a veracrypt volume greater than 2Tb.

Having a 50Tb raid array means that we're restricted to lots of small 2TB encrypted file systems instead of a single 50Tb encrypted volume.   The 2.6.32 kernel is all that RHEL6 provides so help there.  The -m=nokernelcrypto option doesn't seem to help the volume creation.

**Comment by idrassi** [comment]
This looks to be a filesystem limitation since disabling Kernel crypto doesn't help.
You are certainly using Ext2 or Ext3 as the filesystem for your raid and the maximum file size for Ext2/3 is 2TiB as described in this Redhat documentation entry: https://access.redhat.com/solutions/1532

Please feel free to repopen this issue if this is not the case.

**Comment by thorntonr** [comment]
Searching back through emails on the issue from back in April we were using  --filesystem=ntfs
