### ISSUE TITLE
Where is the Windows installer ?

### ISSUE THREAD

**Issue by uihdff** [veracrypt/VeraCrypt#154]
Why isn't github hosting an installer for Windows like sourceforge.net ?

Codeplex is shutting down so they can't be relied to support the installer there.

**Comment by sergeevabc** [comment]
Let’s move from Sourceforge to Github, shall we?
Also version 1.20.2 is missing here.

**Comment by uihdff** [comment]
Is it correct to say you can't build Veracrypt for Windows unless you own MS Visual C++ ?

**Comment by idrassi** [comment]
The main hosting for binaries is Launchpad (this is where all download links at https://www.veracrypt.fr/en/Downloads.html are pointing).
Sourceforge serves as backup hosting thanks to its various mirrors.
There are currently no plans to host binaries also on Github.

By the way, as you certainly noticed, VeraCrypt website is now located at veracrypt.fr .

**Comment by sergeevabc** [comment]
@idrassi, where is portable version? I see no such link at https://www.veracrypt.fr/en/Downloads.html

**Comment by idrassi** [comment]
The documentation explains how to create a portable VeraCrypt for Windows from official installer: https://www.veracrypt.fr/en/Portable%20Mode.html
Also the license inherited from TrueCrypt requires accepting the license terms because unzipping the binaries archive, so we can't distribute a simple zip with the binaries although it is technically possible.
In the future, a better solution is to have a self-extracting exe that requires accepting the license first. Windows built-in utility iexpress allows doing this but the resulting UI is poor. Don't hesitate to sharing any tools that do this better.

**Comment by sergeevabc** [comment]
@idrassi, oh, I keep on forgetting there is *extract* option within installer. It’s worth mentioning on Downloads page.

![](https://vgy.me/aFGORF.png)
