### ISSUE TITLE
[improvement] Inform user to recreate rescue disk after upgrade.

### ISSUE THREAD

**Issue by ghost** [veracrypt/VeraCrypt#177]
0. Install 1.20.
1. Restart PC.
2. VC will ask about changelog.
3. If the user encypted their system drive,

Expected result:
Show message "Don't forget to recreate rescue disk. Do you want to do it now?".

Actual result:
none.

**Comment by idrassi** [comment]
Thanks. 
The Rescue Disk recreation prompt is actually done when installing new version but there was an issue that caused this to not be displayed when installing 1.20. Fixed in https://github.com/veracrypt/VeraCrypt/commit/37aeeaf2041ce85db1a36cdf5a2018cdf33bfe60

Displaying the prompt after reboot is a better approach. It requires adding new message and requesting its translation. Too late for 1.21 release but it will be done in next version.

**Comment by idrassi** [comment]
I have implemented the prompt to recreate Rescue Disk after first boot following upgrade (https://github.com/veracrypt/VeraCrypt/commit/3dfd4a533264807898a2d1b58f113ba48ee6f13d).
You can see it working using the latest 1.22-BETA installer available at https://sourceforge.net/projects/veracrypt/files/VeraCrypt%20Nightly%20Builds/

Thank you for suggesting this.
