### ISSUE TITLE
Website / Release location confusion

### ISSUE THREAD

**Issue by lambdaupb** [veracrypt/VeraCrypt#183]
The many websites and release channels are pretty confusing.

https://www.idrix.fr/Root/content/category/7/32/46//#Downloads
 links to https://veracrypt.codeplex.com/wikipage?title=Downloads
which only has release 1.19 and codeplex says its shutting down.

Bitbucket has release downloads also up to 1.19.
GitHub has releases up to 1.20, but only source.

SourceForge at https://sourceforge.net/projects/veracrypt/files/?source=navbar
has what seems to be all releases.

But GitHub seems to be the main point of activity.

Also for some reason www.veracrypt.fr resolves to NXDOMAIN with google DNS (8.8.8.8) and my browser throws an error. But it works with `dig +trace www.veracrypt.fr` and any other public resolver I tried. I tried the Google DNS flush cache thing, but no change yet.

Maybe this needs some better structuring.
Codeplex should be visibly marked as defunct and link to a better location (github or the website).

**Comment by jrgriffi** [comment]
Sourceforge is missing the Windows installer for 1.20. I also cannot get the IP of www.veracrypt.fr. I have used google and root servers and none return the address. If the address was properly published it should have replicated by now.

**Comment by idrassi** [comment]
DNS configuration of veracrypt.fr is OK and it didn't change for more than a year. See https://www.whatsmydns.net/#A/veracrypt.fr
The issue happens with Google DNS and after some analysis it turns out that there is an issue in DNSSEC configuration that is managed by our hosting company [OVH](https://www.ovh.com) (we delegate DNS handling to OVH): http://dnsviz.net/d/veracrypt.fr/dnssec/.
All our other domains hosted by OVH have no DNSSEC issue, only veracrypt.fr is affected (e.g. http://dnsviz.net/d/veracrypt.eu/dnssec/ and http://dnsviz.net/d/veracrypt.de/dnssec/)
I'm waiting for OVH feedback on this.

Concerning the missing 1.20 Windows installer, it was pulled out because of a stability issue with older CPU configuration that was causing BSODs. These issues have now been solved and the fixes pushed to Git repositories but I'm still waiting for driver signature from Microsoft: usually it takes less than an hour but this time I have been waiting since yesterday and I even resubmitted again few hours ago but no change. This is the blocking point for 1.21 release.

Apart from the chaotic handling of 1.20 caused by late minutes issues, external factors explains the other problems and hopefully these can be solved soon.

**Comment by idrassi** [comment]
OVH has fixed the DNSSEC issue (it was caused by a schedelude Afnic registrar maintainance) and now Google DNS correctly resolves.

I have update VeraCrypt links at IDRIX wensite to point to veracrypt.fr instead of Codeplex.

I have published the third Release Candidates for 1.21 at https://sourceforge.net/projects/veracrypt/files/VeraCrypt%20Nightly%20Builds/ for those beta testers.

**Comment by jrgriffi** [comment]
Thank you for the quick response idriassi. That would explain it as I use DNSSEC. I can confirm that it is resolving now that they have fixed the issue. Thank you for the detailed update on the releases as well.

**Comment by lambdaupb** [comment]
Thanks for the quick investigation into the DNS issue!

I'll close this issue for now, since with the website up, it is a lot less confusing.
