### ISSUE TITLE
v1.1f -> v1.13 after reboot, this error pop up.

### ISSUE THREAD

**Issue by espress0** [veracrypt/VeraCrypt#19]
---------------------------
VeraCrypt
---------------------------
The system cannot find the path specified.

Source: MainDialogProc:5874
---------------------------
OK   
---------------------------

**Comment by idrassi** [comment]
Obviously, no one can help you without giving more details.

This error happens when VeraCrypt can not find the file that you specified in its command line.
Here is the code in question: https://github.com/veracrypt/VeraCrypt/blob/master/src/Mount/Mount.c#L5875

Basically, a file name / device name was specified in the command line and VeraCrypt can't find it.

I suspect that you are using a script to mount volumes at logon and in this script you are using an unsupported syntax were the parameters can be placed directly after their switch (for example /le instead of /l e).

Can you please post the command line you are using to mount volumes are boot?

In general, try to give more information to help solve your issue. Just posting an error message without any context is not helpful at all.

Since in the title you are talking about reboot, I guess you have some favorite configured to be mounted at logon and VeraCrypt is unable to find the specified file container or partition.

Please, if you want us to help, give more details: are you using system encryption or not? Do you favorites configured? What type of favorites do you have? Did you check if the volumes are available? etc...

**Comment by espress0** [comment]
> device name was specified in the command line and VeraCrypt can't find it

My bad. Looks like the volume serial was changed when I reconnect my HDD.
