### ISSUE TITLE
Submit VeraCrypt to Windows Store

### ISSUE THREAD

**Issue by Apostropher** [veracrypt/VeraCrypt#202]
I would like to be able to use VeraCrypt from Windows 10 S.

Please consider submitting VeraCrypt into the Windows Store.

**Comment by ag-n** [comment]
I don't think this is possible while keeping the same features, as UWP apps are tightly isolated and can only use a very restricted API. VeraCrypt runs some code in kernel space if I remember correctly.

**Comment by Apostropher** [comment]
The new Desktop Bridge by Microsoft should make this very simple:

https://developer.microsoft.com/en-us/windows/bridges/desktop
https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-root

**Comment by ag-n** [comment]
Possible maybe, but I have doubts about the "very simple" part. VC isn't a regular desktop app, it uses kernel code and "driver tricks" from what I've read, and even the Desktop Bridge doesn't help with that. [On this page](https://docs.microsoft.com/fr-fr/windows/uwp/porting/desktop-to-uwp-prepare), I can see several entries (admin privileges, kernel-mode driver) that would prevent VC from migrating.

Also, it would likely require a separate build process, because of the modifications needed to work with Desktop Bridge (if at all possible) and the recent version of .NET Framework required. That would be a lot of additional work, and a new build process for each release. I don't think it's realistic with the project's current resources.
