### ISSUE TITLE
Create a 'release' folder on GitHub.

### ISSUE THREAD

**Issue by espress0** [veracrypt/VeraCrypt#22]
https://sourceforge.net/projects/veracrypt/

1. Github has a RSS feed.
2. Sourceforge will install a crapware on your work. Many OSS devs are leaving SF.
3. (related to 2) I didn't trust SF. Maybe they'll change checksum*.txt's value silently.

So, please consider releasing your work on here too.

**Comment by idrassi** [comment]
I don't want to spend too much time repeating my self...
I have already answer the sourceforge issue here and how it compares to Github: https://veracrypt.codeplex.com/discussions/642232#PostDetailsCell_1436934

Just a note: VeraCrypt binaries are digitally signed (PGP for all + embedeed Authenticode signature for the Windows installer). As explained in VeraCrypt documentation, binaries intigrity should be checked only using these: https://veracrypt.codeplex.com/wikipage?title=Digital%20Signatures

checksums are never to be trusted when downloaded from the same source, they are merely there for quicker verification purposes.

Last remark: as I explained in several posts, every VeraCrypt release comes with a bundle that includes all files and their signatures, and that is available for download on Sourceforge and Codeplex (for version 1.13 its name is VeraCrypt_1.13_Bundle.7z) and I publish the PGP signature and checksums of this bundle files on PastBin and Reddit, along side Sourceforge, Codeplex and Bitbucket.
This protects against any entity modify its content even of VeraCrypt PGP is compromized since the modification dates of PastBin and Reddit posts will need to be also modified.

This approach is explained in this post of VeraCrypt Facebook page: https://www.facebook.com/veracrypt/posts/1536516923269293
