### ISSUE TITLE
Help for Android compile!

### ISSUE THREAD

**Issue by Humilton** [veracrypt/VeraCrypt#222]
I am going to compile it on android, can you give me some help ?

**Comment by kleuter** [comment]
VeraCrypt is not for Android, it's a Desktop app

**Comment by Humilton** [comment]
Can it be compiled on embed Linux such as OpwnWRT?

**Comment by elFua** [comment]
I had a go at trying to compile zulucrypt-cli on android under termux - it supports veracrypt, truecrypt and luks, but the configure script failed halfway through because of missing headers for fuse, and possibly other dependencies which probably are not yet available in the termux repos. I didn't feel like spending more time trying to fix the missing dependencies, but in theory it might be possible. Probably extra effort will be required to disable (or fix) the volume mounting code.

**Comment by notetiene** [comment]
As far as I know FUSE isn't (officially) supported on Android.  In part because of the kernel used and also because of some interfaces specific to Android.

In order to support FUSE, you would have to load a kernel module and that means you've got to root your device.

I know someone tried to port libfuse to Android, but I'm not aware of any successful attempt.  See: https://github.com/Vayu/libfuse-android

**Comment by elFua** [comment]
@notetiene:
Android is using `fuse` internally, and I understand that the emulated sdcard is mounted via fuse:

```bash
#cat /proc/filesystems
nodev   sysfs
nodev   rootfs
nodev   tmpfs
nodev   bdev
nodev   proc
nodev   cgroup
nodev   cpuset
nodev   debugfs
nodev   sockfs
nodev   pipefs
nodev   ramfs
nodev   configfs
nodev   devpts
        ext3
        ext2
        ext4
        vfat
        msdos
        exfat
nodev   ecryptfs
nodev   cifs
        fuseblk
nodev   fuse
nodev   fusectl
nodev   pstore
nodev   selinuxfs
nodev   functionfs
```
There are apps which are capable of mounting android partitions without root such as the paid version of [EDS](https://play.google.com/store/apps/details?id=com.sovworks.eds.android), so I assume there must be way to do it.

**Comment by notetiene** [comment]
@elFua True. I haven't done Android development in a while and I'm not using it enough too use those features.

**Comment by notetiene** [comment]
@elFua Probably reverse engineering the APK could tell a lot.  If the APK is using a Shell, a simple string search could give us hints.

**Comment by elFua** [comment]
@notetiene: good idea, will try to poke around; I also see that EDS requires root for mounting and attempts to change SELinux contexts and apparently fails.
Also, according to [this](https://stackoverflow.com/questions/42348061/fuse-on-android) and [this](https://github.com/Vayu/libfuse-android/blob/android/example/hello_ll.c) fuse mounting is doable although with some restrictions.
