### ISSUE TITLE
Self Destruct Password for VeraCrypt container/drives 

### ISSUE THREAD

**Issue by MrElInvisible** [veracrypt/VeraCrypt#225]
tag: discussion, tag: feature-request
https://sourceforge.net/p/veracrypt/discussion/features/thread/632d265a/
---

So, today is 2017 and I would like to use this feature too.

I've already read above Sourceforge and CodePlex, and I don't like "hot-key" method because
this doesn't work on some extreme senario.

Imagine if the attacker steal your notebook while you are away for toilet. Then they will capture you
and force you to tell you a password. You simply can't push that "hot-key" because your hands are tied up.

I really suggest "destruction password" method, because instead of pressing the key, you have a chance
to tell the attacker "self-destruct password" instead of real one. Veracrypt should NOT show confirmation
dialog, such as "Do you really wanna wipe up".

Next, how to do this.
@veracrypt mentioned about "3rd header". Instead of creating a new header, why not "expand" current header?

Current volume header(normal volume header):
hashed=array(
realpasswordhash=passworddaily
hidden=secretkeyofdisk
destruct=xxxxxxxxxyyyyyyyyy <--- add new string to current header. If the user disabled "self-destruct", then fill it with random bytes.
);

When the password was input, VC will:
1. check for realpass, ---passed?---> then mount normal;exit;
2. check for hiddenkey, ---> mount hidden;exit;
3. check for destruct. ---> raise password missed error;exit;
4. if h(pw)==destruct; then DESTROY HEADER; silently show "Password incorrect" error;exit;

When the step 4 was reached, no one can mount this disk/container because the header is completely destroyed by RND bytes.

**Comment by Eyremba** [comment]
The problem is that a VeraCrypt Volume can NOT wipe itself.
So VeraCrypt would have to wipe if when the destruction password is used.
However, an attacker could just create his own brute-forcing tool for VeraCrypt which does not implement this wipe function....

So it would maybe only work when you are forced to open the Volume, similar like the Hidden Volume system.

**Comment by trumpet205** [comment]
Hidden Volume is enough in the event of being tortured for password.

Besides, if VeraCrypt does what you propose, attackers can either clone header/volume beforehand, or as Eyremba has said, compile their own version of VeraCrypt that does nothing for "destruction password."

A so called self-destruction password would achieve absolutely nothing.

**Comment by AngelFalse** [comment]
Nice idea, but when an attacker have physically GOT your drive/container, it doesn't matter if it have a software-based self destructive mechanism. They can clone the full disk/copy the container as much as they want. I'd rather advise you to re-design your HDD firmware (to self-destruct when a full disk clone is found in action) or design some software to monitor your container (to destruct when full file-copy is found in action).
You can have your veracrypt rebuild to insert a code that destroy your disk/container when password mismatch blahblahblah, but since verscrypt is an open-source project, attackers can simply chose not to your rebuilt version of veracrypt.
The biggest problem is that, the disk/file is only a CONTAINER, A SET OF DATA, not an EXECUTABLE BINARY. DATA IS DATA, and BINARY IS BINARY, data cannot DO ANY THING, it can only be THE OBLECT OF READ OPERATION AND WRITE OPERATION.  You cannot tell a disk to "distruct when the password is incorrect", the only way you can do this IS TO OPEN THE DISK AND PLANT SOME NITROGLYCERIN AND A TRIGGER IN IT(LOL).
