### ISSUE TITLE
Mounting partition with pre-boot authentication fails

### ISSUE THREAD

**Issue by SQ-SEN** [veracrypt/VeraCrypt#233]
Mounting a encrypted (Windows) partition in Linux failes with "Partition device required."

Device: /dev/nvme0n1p3
Veracrypt 1.21

ls -al /dev/nvme0n1p3
brw-rw---- 1 root disk 259, 3 Nov  9 11:14 /dev/nvme0n1p3

The same issue also happens if I try to mount a partition inside a hdd image. I suggest removing the check and always mount the partition if valid data is found, regardless of the device type.

**Comment by gv5470** [comment]
@SQ-SEN Hello,
What causes the error is an incorrect deduction of the host drive name of the partition (VeraCrypt guesses /dev/nvme0n1p instead of the right one, /dev/nvme0n1). I am working on a fix for this (first workaround here: https://github.com/veracrypt/VeraCrypt/pull/214).

As for your suggestion to remove the check, I'm afraid it is not that simple. In the case of system encryption, the volume header is indeed stored at the end of the host drive first track, which is located **outside** the windows system partition. Therefore if VeraCrypt can't figure out the block device name of the entire drive, it is unable to access this volume header, and thus can't decrypt anything.

Do you have an image of the entire HDD, or one separate image per partition?

**Comment by SQ-SEN** [comment]
Maybe just ask ask for the main device if it cannot be guessed automatically or offer an option to input it in the first place in advanced options or on the command line. 

The dd image is the whole disc, I use kpartx to create loopback mapper devices for each partition.
The manual input option should also solve the issue with mounting a dd image. You could point to /dev/loop0 or /mnt/imagefile.dd to access the whole disc when trying to mount /dev/mapper/loop0p1

**Comment by gv5470** [comment]
I was considering to try and implement such an option to manually input the host drive. I should get in touch with @idrassi before adding an option to the UI though.

Meanwhile I'm trying to improve the autodetection of the parent drive name using sysfs. This way it should solve both problems (mounting from nvme and from loop device). If you're willing to test it, clone the patch-233 branch from my personal fork (https://github.com/gv5470/VeraCrypt/tree/patch-233) and build the VeraCrypt executable.

**Comment by idrassi** [comment]
@gv5470 I have checked your sysfs method and it looks good for handling the special cases reliably.

Can you please create a pull request for it without requiring the previous "nvme" patch?
I can also manually import your patch while keeping you are its author.

Thank you for your contribution.

**Comment by gv5470** [comment]
Hi, thanks for taking the time to review my patch! I have created the pull request.

**Comment by mr-gittes** [comment]
I get the same error "Partition device required" when trying to mount a loop partition device "dev/mapper/loop0p3" from a (Windows) disk .img file with the Veracrypt CLI in Linux (ver. 1.25.7). The VC volume is on that partition 3 of the disk image and has no errors.

I am using the CLI since the GUI gives no option to select the loop devices for mounting and selecting the .img file directly in the GUI gives the same error! (as well b.t.w. when trying to mount a identical copy/clone of that VC partition (no .img)...).

Strangely mounting the volume from the original (Windows) disk in Linux works without problems!
