### ISSUE TITLE
OpenSuse 14.2: How to add repository via zipper

### ISSUE THREAD

**Issue by Echolon** [veracrypt/VeraCrypt#236]
Hi,

I need to install VeraCrypt at my university PC, the system is running OpenSuse 14.2. 
The fact it is network administrated system and I have no root access, I need to install and add the repository first via zipper (as I understood) - does anyone know how it works because it cannot find a veracrypt package :/

Kind regards

**Comment by gv5470** [comment]
Hello,
I personally never used OpenSuse nor Zypper, but I'm assuming you want to install veracrypt in your home directory, is that correct? If that is the case, you can simply run the installer and choose "Extract .tar Package file" instead of "Install VeraCrypt", which should put a .tar.gz archive in the /tmp directory. Simply extract it then inside a folder where you have write access.

Three caveats however:
- You have to make sure that all of VeraCrypt dependencies are installed as well (the major ones being wxWidgets and FUSE). This would be done automatically by installing a Zypper package, unfortunately I am not aware of anyone having done the work of putting VeraCrypt in a Zypper package (but I could have missed it).
- Even if you manage to install VeraCrypt without being root, you *will* need root privileges for some operations, such as mounting or dismounting a volume.
- From a security/confidentiality point of view, use of VeraCrypt on a system where you don't have administrator rights is discouraged (see the [documentation](https://www.veracrypt.fr/en/Using%20VeraCrypt%20Without%20Administrator%20Privileges.html)).

**Comment by Echolon** [comment]
> but I'm assuming you want to install veracrypt in your home directory, is that correct?

Yes - but my computer is maintained from a 'root server' - sorry for being imprecise, I'm not such a Linux expert as I'd like to be. Thus, they first need to add a repository to their administrating system.... puhh.. sorry. I'm gonna ask a colleague again, what they especially need to know. They definitely cannot use the single .tar file and install from scratch :/

Anyway, thanks!

**Comment by Echolon** [comment]
Hi,

I spoke with my colleague. As he told me they need this Zypper package you were talking about:

> This would be done automatically by installing a Zypper package, unfortunately I am not aware of anyone having done the work of putting VeraCrypt in a Zypper package (but I could have missed it).

So, if anyone could do it that would be great - otherwise maintainers can close this threat.

Thank you for continuing developing on VeraCrypt!
