### ISSUE TITLE
Can I decrypt my files with another software?

### ISSUE THREAD

**Issue by ProgrammingLife** [veracrypt/VeraCrypt#239]
I crypted my files with VeraCrypt (AES, SHA512) in a single file on public partition. Can I decrypt it with another software, for instance, OpenSSL? Or it's not possible?

**Comment by AngelFalse** [comment]
No, of course you cannot decrypt it with OpenSSL. OpenSSL and VeraCrypt is not even one type of software. But, of course if you clone this software's code and rebuild one on your own name, and (if you call that "another" software) of course you can use that to decrypt the files, because they use the same encryption procedure. (And of course you can rewrite all the code to realize the same procedure if you want)

Don't ask me how the heck did I get the idea of copying code, build it, and call it a NEW SOFTWARE, THEY do it all the time, even when they are found to copy the WHOLE BSD CORE CODE and announced it as "HOMEBREW", FxxK.

**Comment by grolongo** [comment]
If you end up on Linux and can't install VeraCrypt for some reason, you can use cryptsetup to decrypt a VeraCrypt volume.

Example:

```
cryptsetup --open --type tcrypt --veracrypt /path/to/container.hc foo
mount /dev/mapper/foo /mnt/bar
```

You can get further examples and more detailed options for hidden volumes, keyfiles, etc on the Archlinux Wiki if you want.
