### ISSUE TITLE
Secure Desktop is not used on password entry when container is mounted via command line

### ISSUE THREAD

**Issue by marecabo** [veracrypt/VeraCrypt#246]
What I did:
- Activated "Use Secure Desktop on password entry" in Settings > Preferences
- Invoked password entry window by executing the following command: 
`start "VeraCrypt" "C:\Program Files\VeraCrypt\VeraCrypt.exe" /volume "<absolute-path-to-container>" /letter V /explore /history n /cache n /wipecache /quit`

What happened:
 - The password entry window appears, but the desktop is not darkened/secured.

Windows 10 Version 1709 x64, VeraCrypt 1.21 x64

**Comment by idrassi** [comment]
You need to use the switch `/secureDesktop` in order to force the password entry to be displayed in the Secure Desktop because `/quit` makes VeraCrypt not use the program preferences (you can use `/quit preferences` to load the preferences but it will override the settings defined in the command line)

The `/secureDesktop` switch is new to 1.21 and it is documented in the User Guide. shipped by VeraCrypt installer. It was missing in the online documentation and I have just fixed it.

Closing this issue. Please feel free to comment or reopen if needed.

**Comment by marecabo** [comment]
I only looked in the online documentation. Thank you for this explanation and your work on VeraCrypt!
