### ISSUE TITLE
Veracrypt have this security problem?

### ISSUE THREAD

**Issue by freesoft0000** [veracrypt/VeraCrypt#253]
https://diablohorn.com/2017/12/12/attacking-encrypted-systems-with-qemu-and-volatility/

**Comment by idrassi** [comment]
The article deals with "transparent full disk encryption" which don't require any user interaction. This means that the password is on the system itself or in an external device with no authentication (a bad idea anyway).

The author suppose that he has access to the correct password so that he can monitor the boot process of the system. His objective is to analyze a type of obfuscation used in some systems and he is not breaking the encryption.
So, there is no security problem as far as VeraCrypt is concerned. The author shows how one can workaround some techniques used in systems to limit the functionalities offered by Windows.
