### ISSUE TITLE
Linking from source fails on Fedora 27

### ISSUE THREAD

**Issue by giacecco** [veracrypt/VeraCrypt#270]
I'm getting this doing `make`. I'm compiling from source (ea94096df71a7100d3c0f707898d9760f624da32) to avoid [another Fedora issue found post-1.21](https://github.com/veracrypt/VeraCrypt/issues/198). It does not look like some library is missing. Please help, thanks!

```
(...)
Linking veracrypt

(process:14010): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(process:14010): GLib-GObject-CRITICAL **: g_signal_handlers_disconnect_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(process:14010): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(process:14010): GLib-GObject-CRITICAL **: g_signal_handlers_disconnect_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
$
```

**Comment by idrassi** [comment]
These are not link errors but rather simple GTK asserts and warnings caused by the underlying wxWidgets VeraCrypt is using. These asserts are displayed after link is successful because we run a self test in text mode.

These warning and asserts are harmless for VeraCrypt usage and we can’t do anything about them anyway since they are coming from wxWidgets.
