### ISSUE TITLE
Truecrypt Mode mount option default setting is not used

### ISSUE THREAD

**Issue by fad1** [veracrypt/VeraCrypt#271]
VeraCrypt does not appear to use the TC mount option checkbox value. It's always on.

**Comment by eb0815** [comment]
I read in other comments that this is particular to the MacOS version. I can attest to the bug being there. VC version 1.21 from July 9, 2017.

**Comment by idrassi** [comment]
The TrueCrypt Mode checkbox is always on only if the file container name ends with the .tc extension.
This was done by design to help TrueCrypt users easily mounted their legacy volumes.

If you don’t want TrueCrypt Mode to be checked, then you will need to remove/change the .tc extension of the file container name.

If you are using the .tc extension as an obfuscation way against attackers, then manually unchecking TrueCrypt Mode should be part of your usage scenario.

**Comment by eb0815** [comment]
Re idrassi - good point. I did not find a predefined veracrypt extension, but doing this manually for, e.g., ".vc" yields the desired results.
