### ISSUE TITLE
Windows 10 fast startup - Volumes stay mounted

### ISSUE THREAD

**Issue by leonard84** [veracrypt/VeraCrypt#273]
When [fast startup](https://www.cnet.com/how-to/what-is-windows-10s-fast-startup/) is enabled, windows will persist veracrypt's state this seems to include everything including key material, since the volumes stay mounted. This happens even if all auto-dismount options are checked including forced dismount.

I suspect that this might also compromise the key material, since the state is persisted to disk.

**Comment by idrassi** [comment]
This issue has been know since Windows 8.1 (aka Hybrid Shutdown) and the official VeraCrypt documentation mention it alongside a recommendation to disable it: https://www.veracrypt.fr/en/Issues%20and%20Limitations.html

Currently it is not possible to detect Hybrid Shutdown since Windows doesn’t send any of the usual notification messages and there is no documented way to implement such détection on user mode applications. I believe this is by design from the part of Microsoft so I don’t think it will possible to implement automatic dismount when Hybrid Shutdown occurs.

Thus, the only solution is disable this feature as recommended in the documentation.
