### ISSUE TITLE
VeraCrypt 1.21 - Not responding - Windows 10

### ISSUE THREAD

**Issue by ozzi-** [veracrypt/VeraCrypt#295]
I just installed VeraCrypt 1.21 a few days ago.
I migrated my TC volumes, all worked fine, I setup everything to mount 3 HD volumes on logon.
Since today when i start VeraCrypt I get the "Not responding" Windows behavior. Restarting does not help.
However, when I use the taskbar icon, I can mount my drives.

**Comment by ozzi-** [comment]
Uninstall, reboot, install and adding favorite volumes again fixed the problem (for now)

**Comment by idrassi** [comment]
Strange issue.
Do you see password dialog before VeraCrypt is freezer or it is not responding from the beginning?
Are you using the option to enter password in secure desktop?

**Comment by ozzi-** [comment]
Okay so after the second reboot I started having the same problem again. 
Now I just booted and they are already mounted. How does this happen? Without a password...

It freezes instantly and yes im using secure desktop.

**Comment by idrassi** [comment]
The fact that volumes remain mounted after boot is caused by a Windows 10 feature called fast startup: when you shutdown Windows, it doesn’t Shutdown in reality but instead it goes into a special sleep mode so that when you power on the machine, all programs are still running as if no Shutdown occurred. That’s why the volume remain mounted.
For security reasons, it is advised to disable fast startup feature in Windows to avoid leaking volumes keys especially if system encryption is not used.

Concerning the freeze issue, it looks like the password dialing is displayed in the secure desktop but the secure desktop had lost focus for some reason and so you don’t see it. VeraCrypt is freezed because it is waiting for the password dialog to finish which never happens since you cannot see it.

This should not happen since we explicitly switch to the secure desktop. In your case, something is forcing Windows to switch back to the normal desktop during logon.

I will try to see how we can workaround this. Probably by switching to secure desktop if we detect that it is not the current desktop.

**Comment by ozzi-** [comment]
Hi idrassi
Thanks for your input concerning fast startup, I was not aware of this feature and I do agree that it is a horrible idea in the security context. Since turning it off, VeraCrypt does not freeze any more, therefore reinforcing your assumption.
I guess fast boot has VeraCrypt confused about its or the state of Windows, therefore waiting for Secure Desktop (which is a nice feature by the way! Glad I migrated from TrueCrypt).

Ill be glad to test any kind of patches.

**Comment by idrassi** [comment]
@ozzi- : I have done some changes on the secure desktop implementation
to make it more robust and I have uploaded an installer for 1.22-BETA6
that contains this:
https://sourceforge.net/projects/veracrypt/files/VeraCrypt%20Nightly%20Builds/.
If you could do test on your side to check if it behaves better, that
would be great.

Concerning the fast startup issue, I'm thinking of adding a feature to
detect fast startup and warn users about it.

**Comment by ozzi-** [comment]
Okay I installed BETA6, funny enough Windows 10 just reactivated Fast Boot, so I am glad there might be a fix. I will let you know when I gathered enough experience with this release. 
@ Fast Startup detection -> reading HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Power\Hiberboot  suffices.

**Comment by ozzi-** [comment]
Okay I can confirm that BETA6 is working like a charm! Cool

**Comment by ozzi-** [comment]
Okay it seems that the first favourite volume on boot displays the regular prompt, when I click ESC the others come with the protected prompt. Weird. I tried removing the first from favourites and readding it, to no avail.

**Comment by idrassi** [comment]
@ozzi- : the behavior you have confirms my suspecions that the
SwitchDesktop Windows API is failing on your machine during session
opening process. In the new implementation SecureDesktop in 1.22,
VeraCrypt handles correctly SwitchDesktop failures and it waits a
maximum of 5 seconds for it to succeed. If it is still failing after 5
seconds, VeraCrypt then uses regular desktop to display password prompt
in order to avoid freezing the application.

Everything is pointing towards some software running in your machine
that starts before VeraCrypt when session is opened and which blocks
secure desktop switching for a certain time. After a while, this
software unlocks desktop switching and that's why the second favorites
is able to use SecureDesktop.

This is a very special case and one solution would be to wait more than
5 seconds until the unknown software let us use secure desktop but this
would make the user experience poor and it will be seen as if it is the
fault of VeraCrypt.

The best approach would be to analyze the startup sequence of your
machine in order to find which software is launching at boot and when
session opens in order to identify the application that is blocking
VeraCrypt from using its secure desktop.

**Comment by ozzi-** [comment]
Thanks! Ill try 1.22 and otherwise check my setup.
