### ISSUE TITLE
Feature Request: preserve timestamp when NO modifications are made

### ISSUE THREAD

**Issue by sir106** [veracrypt/VeraCrypt#296]
PROBLEM: 
I want to modify veracrypt containers on serveral devices. 

I can't synchronize containers between two computers (e.g. with resilio sync) - the timestamp is ALWAYS changed. Even when nothing has been modified. Would be great, if timestamp is only changed, when there are real changes inside the container.

Sometimes I only open the container to retrieve some data. the current behaviour is resulting in possible data loss and/or to much data transfered.

ENHANCEMENT:
only modify timestamp of the container when files inside are changed.

**Comment by idrassi** [comment]
VeraCrypt only modifies file container time stamp when data is written to the container.

What happens is that sometimes Windows will write data in the background to mounted volume even of you don’t change anything in the volume. For example, Explorer will update cached thumbnails.

That’s why you think that VeraCrypt has modified time stamp on its own.

You can see if any data was written to the volume by selecting it on VeraCrypt UI and clicking the button “Volume Information”: the last raw indicates how much data was written since mount. It this value is zero, then VeraCrypt will not change time stamp.

At VeraCrypt level, it is impossible to distinguish between write operations done in the background by Windows and write operations triggered by the user.

**Comment by lambdaupb** [comment]
Filesystems write a status flag onto the disk at mount time to be able to know if a disk was unmounted cleanly.
It resets this flag to "clean" on unmount.
This unfortunately means there is a small write operation on each mount and therefore an updated modification time.
