### ISSUE TITLE
an inquiry about translation

### ISSUE THREAD

**Issue by initbar** [veracrypt/VeraCrypt#30]
When editing the translation of `/Translation/*.xml` files, do you prefer us to directly commit our translations into the pull requests, or through external TrueCrypt resource(s) (i.e. `Crowdin`)?

**Comment by idrassi** [comment]
It is OK to use pull requests but since I can not check the validity of the translation, I ask users to send encrypted email to veracrypt@idrix.fr with information that will help validate that the person in question have indeed the ability to perform the translation.

This is important to avoid having issue and to maintain the quality of the translation inherited from TrueCrypt.

Is this OK for you?

As you can see in the XML files inherited from TrueCrypt, the authors are identified by their real names. In VeraCrypt, anonymous translations can be accepted but the authors should identify themselves through encrypted email and their names will not be put in the XML file.

I started experimenting with Transifex (https://www.transifex.com/idrix/veracrypt/) but I will try Crowdin as well.

**Comment by initbar** [comment]
That sounds good with me :) I've updated it with my real name.
