### ISSUE TITLE
Can't mount folder on OSX 10.13.5 with error "No such file or directory"

### ISSUE THREAD

**Issue by jncharon** [veracrypt/VeraCrypt#332]
Hello team,

When I mount any container, I've got the following error : 
No such file or directory : /var/folders/....../ 
VeraCrypt::FileSystemPath::GetType:45

<img width="532" alt="capture" src="https://user-images.githubusercontent.com/7594444/42001790-65ed6c12-7a65-11e8-8bda-ce897525ee69.png">

I'm running VeraCrypt 1.22 on OSX 10.13.5 with OsxFuse 3.8.1

**Comment by idrassi** [comment]
This seems to be caused by changes in osxfuse 3.8.x.
Does running VeraCrypt as superuser using sudo fix the problem?

**Comment by jncharon** [comment]
Yes, running the binary contained in the app package as root does solve the problem !

**Comment by idrassi** [comment]
osxfuse 3.8.0 works correctly under OSX 10.13.5 but osxfuse 3.8.1 Pre-release causes this issue.
So it is clear that this is a bug/regression in osxfuse 3.8.1 Pre-release because there is no reason for it to require us to be superuser on OSX 10.13.5.

Hopefully the final osxfuse 3.8.1 will not have this issue.

**Comment by jncharon** [comment]
I Uninstalled osxfuse 3.8.1 and reinstalled the 3.8.0 version, this solves the issue.
This is definitely an upstream bug in osxfuse.
Thanks for your help !
