### ISSUE TITLE
Passwords longer than 64 characters allowed on windows but not on linux

### ISSUE THREAD

**Issue by nshtg** [veracrypt/VeraCrypt#340]
Since there was no warning while setting up the volumes on windows I am now stuck on Linux with 15TB of data encrypted with 128 characters paswords - Which I can not decrypt or change on linux since the limit of 64 characters is being enforced there.

Not a very good solution in my opionion. Any workaround ideas that do not involve reinstalling windows for the purpose of changing passwords?

**Comment by cookieenabled** [comment]
@nshtg

Seriously? Since when VC can encrypt the disk using 65+ password?
VC creation wizard only accept 64 length.

**Comment by nshtg** [comment]
I have multiple encrypted disks that I created on windows (using veracrypt) with 128 character keys... Has been working forever, just not on linux.

**Comment by cookieenabled** [comment]
I thought maximum length is 64... If 128 is okay then I will change all password to maximum length.

@nshtg
Did you tried command line?
https://www.veracrypt.fr/en/Command%20Line%20Usage.html

```
$ veracrypt /v /path/to/disk.file /p "your very long password"
```

@idrassi What is the _official_ maximum length?

**Comment by nshtg** [comment]
I tried using the commandline on **linux** but that is restricted to 64 characters aswell.

**Comment by cookieenabled** [comment]
@nshtg

On Windows, iirc Veracrypt GUI never accept 65+ password (simply can't input more than 64 length)

I don't know _how_ to encrypt a disk using 65+(128 in your case) password, but this glitch should be patched.
(do you have reproduce-able step?)


> do not involve reinstalling windows

I assume you only have one computer. If your friends / workplace computer is Windows, you can install Veracrypt as "Portable" mode.

Or, you could use VirtualBox. Install VirtualBox on your Linux PC, install Windows 7 and Veracrypt on a virtual machine, then connect to USB... surely this will take a few hours.

**Comment by idrassi** [comment]
VeraCrypt passwords have a maximum length of 64 bytes (a Unicode character can be encoded over several bytes so maximum length in terms of characters can be shorted than 64 but if only ASCII characters are used, then the maximum length is 64 characters).

VeraCrypt UI on Windows truncated passwords longer than 64 characters whereas on Linux the UI refuses to accept such passwords. This différence of behavior has many reasons. First, historical reason because TrueCrypt used to truncate passwords silently in all cases but in VeraCrypt we started enforcing the limit everywhere except for copy-past under Windows. This exception is due to the complexity of implementing copy-past validation under Windows and so in this special case we just truncate the password.

Going back to your problem, just truncate your password to the first 64 characters and you will be able to mount your disks.
