### ISSUE TITLE
Mount in linux only mounts to /dev/mapper/veracrypt1 and not to given directory

### ISSUE THREAD

**Issue by Cyber1000** [veracrypt/VeraCrypt#348]
- Debian
- Veracrypt 1.22

Mounting with: 
veracrypt -tc -t --filesystem=none {truecrypt_file} {myMountpoint}

At the end it is not mounted on myMountpoint, but I can manually mount "mount /dev/mapper/veracrypt1 {myMountpoint}" and this works.

If I have understood the commmand line correctly I shouldn't need this manual step. Am I right or am I missing something?

Thanks,
Cyber1000

**Comment by idrassi** [comment]
Specifying "none" for the --filesystem switch makes VeraCrypt skip the
mount operation. That's why you need to perform the mount manually in
your case. If you replace "none" by "auto" it will work as expected.

If the user tells VeraCrypt that there is no filesystem in the volume,
then it considers that the user will access the device mapper directly
in order to perform custom operations (e.g. cloning decrypted disk).

**Comment by Cyber1000** [comment]
Sorry my fault, seems quite conclusive that "none" does nothing :-)
Works! Thanks for your answer!
