### ISSUE TITLE
Add option to not use bootsector for GPT/EFI only discs, ie. No legacy install option

### ISSUE THREAD

**Issue by jam3st** [veracrypt/VeraCrypt#356]
I accidentally killed my windows system partition because I forgot that sectors 4 - 68 were being used by veracrypt. I did this by manually repartioning my ESP partition to make it bigger to add a linux kernel. I looked at the backup options and realised that there is only 512 bytes needs to get the key header, the one that contains the salt in the top 64 bytes and the reamining 448 contain the encrypted header information and key.

Is it possible to have an GPT only install where the file is contained in the ESP\Veracrypt boot partition and if so would you accept patches for this?

**Comment by idrassi** [comment]
Yes, it is possible to do a modification to read the header from a file
instead of the disk sectors. Reading from disk sectors is more secure
and more reliable than reading a file from EFI filesystem but it can be
added as an option for the user to choose with fallback to sectors
reading if the file can not be found.

Patches are welcomed if someone want to implement this.
