### ISSUE TITLE
Linux GUI: Open menu is not closed automatically when moving program window

### ISSUE THREAD

**Issue by Atalanttore** [veracrypt/VeraCrypt#359]
A open menu is not closed automatically when moving the program window on Ubuntu 18.04 (Gnome 3).

Steps to reproduce the following screenshot:

1. Open a menu from the menu bar
2. Move the program window

![veracrypt_open-menu](https://user-images.githubusercontent.com/628474/45266953-8a4f1280-b463-11e8-9a0f-5226f87506e8.png)

**Comment by idrassi** [comment]
I can not reproduce this behavior on vanilla Ubuntu 18.04 with official
VeraCrypt binary. As soon as I click on the title bar to move the main
Windows, the menu disappears.
Did you download VeraCrypt from veracrypt.fr?
Is there a special trick to move the Windows without clicking on the
title bar? I could not find any way to make the menu persist when I
click with the mouse on the title bar.

**Comment by Atalanttore** [comment]
Ubuntu 18.04 returned to X.Org as default display server though Ubuntu 17.10 uses Wayland. I've upgraded from 17.10 to 18.04 and Wayland is still being used on my machine. Maybe that's the reason for the different behavior.

I've installed VeraCrypt via package management to get automatic updates.

**Comment by idrassi** [comment]
Ok, thank you for the clarification.

Is it possible for you to test using the official binary from
veracrypt.fr? I don't have a configuration like yours to test and I want
to check if this behavior is caused by the Ubuntu specific build in the
launchpad repository which uses extra patches to adapt to Ubuntu Unity.
Thank you.

**Comment by Atalanttore** [comment]
I've used the manual installer without automatic updates from the official [veracrypt-1.23-setup.tar.bz2](https://launchpad.net/veracrypt/trunk/1.23/+download/veracrypt-1.23-setup.tar.bz2) binary. This problem seems to be gone, but other problems (e.g. #355, #358) still exist.

**Comment by unit193** [comment]
Howdy,

The patch in the PPA version should only affect the systray menu, as the patch adds support for indicators.  I've since then updated the version in the PPA, so when changing to upstream's installer you also jumped versions.  There's a possibility that since (IIRC) the setup file bundles wxwidgets, you are hitting an issue with system vs bundled wxwidgets.

I tried to reproduce your error with 1.23 but I could not.  However, I am on an Xfce4/Xubuntu bionic install, not GNOME (and certainly not using Wayland.)
