### ISSUE TITLE
Volume creation security issue?

### ISSUE THREAD

**Issue by emkey08** [veracrypt/VeraCrypt#365]
VeraCrypt 1.22 (64 Bit), Windows 10 (64 Bit, build 17134)

When creating an encrypted file container from the command line by invoking "VeraCrypt Format.exe", large blocks of the created volume file aren't encrypted but zeroed out instead. See attached screenshot for further details.

Am I missing something? Shouldn't the resulting file be completely encrypted?

![veracrypt](https://user-images.githubusercontent.com/802512/45680938-86468300-bb3c-11e8-8bf0-24a3993dd721.png)

**Comment by idrassi** [comment]
Thank you for reporting this.

When creating a file container using command line, we use quick format
for the target filesystem in order to speedup creation process since in
command line case there is no operation progress feedback. Quick
formatting is turn doesn't overwrite all sectors of the newly created
volume and so when examining its storage, zeroes can be seen in parts
that were not touched by the formatting process.

The fact that zeroes are visible on the storage doesn't mean that data
is not encrypted. It only gives an indication to an attacker which parts
of the container potentially contain data and which parts don't contain
data.

Nevertheless, this is an information leak and I will add an option to
control the use of quick format from command link instead of it being
always enabled.

**Comment by emkey08** [comment]
Thank you very much for addressing this.

Regarding command line progress feedback, you may consider to write some sort of well specified progress information to stdout. The calling process could then obtain progress information. As an example, progressively write 1000 dot chars to stdout, one for each permille of progress.

**Comment by idrassi** [comment]
I have added a new switch /quick to enable quick format and I have
disabled quick format by default:
https://github.com/veracrypt/VeraCrypt/commit/0557cac9cf416c02624321c197ffba7067d9b83b

You can test using binary for new version 1.23-Hotfix-1 available at
https://sourceforge.net/projects/veracrypt/files/VeraCrypt%20Nightly%20Builds/
