### ISSUE TITLE
&amp in right to left languages

### ISSUE THREAD

**Issue by pkka** [veracrypt/VeraCrypt#372]
what is this symbol (&amp) in the middle of translation files. and how to deal with it in right to left languages?

**Comment by Van-Fouran** [comment]
Some languages like XML and HTML encode special characters in text context. This prevents the executing program from interpreting those symbols.
For example &amp is the &-Sign. Because & in XML is a special character you have to encode it.

For more details please see https://www.w3schools.com/html/html_entities.asp and https://www.w3.org/standards/xml/core
