### ISSUE TITLE
Is Veracrypt Closed?

### ISSUE THREAD

**Issue by hasanalizxc** [veracrypt/VeraCrypt#387]
Dear Idrassi,

I know you and Enigma2 from the beginning of this project. We were talking in discussion forums (old one, now archived). We were talking in Github issues. We were talking with e-mail. I was talking with Enigma2. What happened to you and you don't answer a question on Github and e-mails. There is 211 issues and no one answer these. No one help us. Is Veracrypt closed?

Could you please make us this situation? We started to suspect. Is "someone" trying to "gag" you?

Thanks.

**Comment by idrassi** [comment]
Hi,

I apologize to the Github community for not being reactive lately, especially for long time followers like you. These days I’m more active on Sourceforge forums than here and as you can check there I have been handling some issues that are time consuming from the technical point of view (e.g. ReFS BSOD with Win10 1809 and some upgrade failure for Win10 1809).

With the growing number of feedback form users, it is becoming difficult for me to answer all questions and emails. As you certainly know, VeraCrypt does not generate revenue (apart from low donations) which is good for its independence but it means that revenue must be generated by other projects and so there are periods where there is less time available for VeraCrypt day to day handling.

That being said, I will do my best in the coming days to give feedback on the pending Github issues.

**Comment by hasanalizxc** [comment]
Hi Idrassi,

Thank you for your reply. I really had suspected (government or secret-agency brute force) from this situation. I appreciate you and your work.

I can understand your status on this project. I know this project is trying to raise on it's foot with low donations but please understand us because there are lots of questions and no one answer those.

We are looking forward you in a short time.

**Comment by idrassi** [comment]
Thank you again for following the project so closely.

I resumed replying on Github issues. Don’t hesitate to post a list of important points that you think I should address more urgently. That will be helpful since it takes a very long time to go through all posts and assess the importance of each one of them.

**Comment by francwalter** [comment]
Just for curiousness: did the NSA do an approach to you, @idrassi since you created VeraCrypt?
Trying to infiltrate you?

Very appreciate your work, thanks!!!
frank

**Comment by Eyremba** [comment]
> Just for curiousness: did the NSA do an approach to you, @idrassi since you created VeraCrypt?
Trying to infiltrate you?

I think if they would have tried this, he wouldn't have noticed it.

**Comment by hasanalizxc** [comment]
Please open [this page](https://www.veracrypt.fr/en/FAQ.html)

And find _government_ word with Ctrl+F

I believe to Idrassi forever..

**Comment by idrassi** [comment]
To make things clear, I was not approached by the NSA or any other 3 letters agency. The closest thing that I had with any government entity is when I was asked by the French ANSSI to do a presentation about VeraCrypt and its technical aspects. The presentation was no different from other presentations I did in other public events (like in OSSIR https://www.ossir.org/paris/supports/2016/2016-05-10/VeraCrypt-IDRIX-presentation.pdf) and although we had discussions about legal aspects of strong encryption export, there was no request or interference from there side on the course of the project or its integrity.

Obviously, the project is followed by authorities because of its capabilities and they have probably done their homework on us to seek information about our background and motivations but we have nothing to hide and I personnally consider this to be normal when you go public.

For the infiltration question, I don’t really understand its meaning in our context. The VeraCrypt team is small so there is nothing to infiltrate at human level. If the question is about electronic infiltration, this is possible but it will have no effect on the integrity of the project thanks to various measures put in place to protect its source code and binary builds.
Like many IT security professionals, we are regularly subjected to electronic attacks using various vectors (which sometimes include dubious human contacts) and we do the maximum to protect ourselves and our customers assets. Since the start of VeraCrypt, attacks rate increased significantly and this makes us lose more time and resources but they remain manageable without significant disturbances to the VeraCrypt project or the other business activities.

To finish, I will reiterate what is mentioned in the FAQ and which was referenced by @hasanalizxc: there is no backdoor in VeraCrypt and we will never implement one even if we are asked to do so, and in case there is a law or any legal requirement in France that forces us to add a backdoor than I will simply shutdown the project rather than betraying users trust.
