### ISSUE TITLE
Error creating hidden OS

### ISSUE THREAD

**Issue by superbulka** [veracrypt/VeraCrypt#391]
Hello, I have this configuration:
=========================
Lenovo Ideapad 700-15ISK
Intel Core i-7
NVMe Samsung SSD 970PRO 1TB
Win 7 Pro X64
Veracrypt 1.23-Hotfix-2
=========================
The disk is divided into 2 parts: 297 and 656 gigabytes.
When creating a hidden OS, the program copies the current OS into a hidden partition. This copying is completed, the system speaker beeps and the message is displayed: 
"Copying completed.
Write error: 128 Drive: 0 Sector: 0
Enter password for hidden system: "

https://i.ibb.co/MpncD2m/photo-2018-12-16-22-44-14.jpg

After entering the password, the hidden OS is loaded (translation via Google translator from Russian):
ERROR: unknown status.
(If you inform us of a related error, include information in the report: AfterWMInitTasks:10114)

https://i.ibb.co/tLBQYf6/photo-2018-12-16-22-44-21.jpg

I ask for help. Google didn't solve the problem. :(

**Comment by superbulka** [comment]
!!!
UPD.  Replaced Samsung ssd on Sata disk Western Digital 1TB. Copying the hidden system was completed without any problems. Does this mean that VeraCrypt does not support NVMe Samsung SSD 970PRO 1TB?

**Comment by idrassi** [comment]
Thank you for this detailed report.
After analysis, the root cause of the issue is that there was a failure while updating the MBR sector on the SSD disk and the error code (128 = 80h) means that there was a timeout when the BIOS was sending the data to the SSD disk. 
This error is surprising especially that that we were able to write a large number of data before. Moreover, the current code already retries the write operation 5 times in case of failure so this does not help with the timeout issue. I suspect that it has to do with failure of BIOS to handle writing 512 bytes sectors on disks that operate natively on 4096 bytes sectors.
It is difficult to fix such problems because they are more related to the BIOS compatibility with the SSD drive and VeraCrypt has no hand in it. That being said, I have implemented a workaround by writing 4096 bytes of data at one go instead of the 512 bytes needed as you can see in commit  https://github.com/veracrypt/VeraCrypt/commit/6abc59acd204ce59f53b218cafc01ced955695cd.

I have uploaded the installer for version 1.24-Beta0 which contains the workaround for the SSD issue to https://sourceforge.net/projects/veracrypt/files/VeraCrypt%20Nightly%20Builds/.

Thank you in advance for your feedback on testing with this new version.
