### ISSUE TITLE
VeraCrypt should probably ship HTML documentation (instead of PDF)

### ISSUE THREAD

**Issue by pmjdebruijn** [veracrypt/VeraCrypt#4]
Currently the VeraCrypt installer ships the PDF version of the documentation, which has a couple of downsides.

Most versions of Windows for example don't ship with a PDF reader by default, and require installation of Adobe Reader (which has had it's fair share of security issues).

Pretty much every desktop operation system does ship however with a browser. So HTML documentation would be universally accessible without requiring third party software installation.

HTML documentation has other benefits like dynamically reflowing text based on screen resolution, and/or preferred font size.

Also currently the VeraCrypt binary seems to launch a browser to online URLs for help, which effectively means it's leaking information to the web that it's user is potentially trying to install VeraCrypt. Preferably VeraCrypt should launch a browser to a local version of the HTML documentation.

These issues aren't particularly important, but should be fairly easy to ammend.

**Comment by idrassi** [comment]
I agree. Having an HTML based documentation is a must-have and it will solve the issues you described.
Today, the documentation is edited twice: once for the word documentation from which the PDF is generated, and once for the online documentation present in Codeplex using Codeplex HTML editor.

For the next release, I would like to put in place a single documentation source written in Markdown, so that it can be converted to an HTML that can be included in VeraCrypt installer and at the same time it can be posted to Github/Codeplex/Sourceforge as is to serve as online document with no effort since they all understand Markdown.

**Comment by idrassi** [comment]
This has been implemented and now VeraCrypt ships with HTML documentation (it can be found in https://github.com/veracrypt/VeraCrypt/tree/master/doc/html).
On Windows, we also ship a CHM file that is build from the HTML documentation.
