### ISSUE TITLE
Favorite is mounted too late during windows boot

### ISSUE THREAD

**Issue by floxch** [veracrypt/VeraCrypt#408]
Hey,

I've recently exchanged my HDD with an SSD and therefore decrypted the HDD, cloned it to the SSD and then encrypted the SSD again. I'm using a dock application that displays various program icons. With the HDD, the dock would display all program's icons correctly after boot and I would not notice my HDD being mounted (this drive is not the system drive). 

Now, with the SSD, VeraCrypt displays a "Please wait" window after logging in and after the dock was started, so it mounts the drive after other programs have been started. This leads to the dock not displaying all program's icons (the programs are installed on the second drive).

Unfortunately, I can't remember how I set everything up so the behaviour was the way it was with the HDD. I've tried changing some settings but nothing helped. Could someone please point me to the right settings? Thanks!

**Comment by idrassi** [comment]
If you are using system encryption, then you should add the SSD as a System Favorite in order to for it to be mounted at boot time before the user session starts. If it is configured as normal Favorite, then indeed it will be mounted after the user session starts which too late on your case.

If you are using system encryption, then I don’t see why there would be a difference between the HDD and the SSD. In this case, maybe more information about your setup could help understand better (e.g. use of keyfiles, options checked...)

**Comment by floxch** [comment]
That worked, fantastic! Thank you! The difference wasn't clear to me.
