### ISSUE TITLE
About MacOS Installer Package

### ISSUE THREAD

**Issue by leochou0729** [veracrypt/VeraCrypt#422]
Hello,
  I'm wondering how you can show this sheet on the Summary page. I can't see any special setting in the Packages project file. Thanks!

![image](https://user-images.githubusercontent.com/13413417/52899360-3a4f5580-3224-11e9-9816-28ea5a88a2aa.png)

**Comment by idrassi** [comment]
This is a standard behavior of OSX install manager and it is not linked to any special setting in the Package project file, at least we don’t anything special for it.
The same behavior can be seen with other installers like the one of OSXFuse.

**Comment by leochou0729** [comment]
I always use Packages to create installer package for my project, but this sheet never shows up. Very strange!

**Comment by andreas-becker** [comment]
Hey @leochou0729 , as @idrassi mentioned, it is a standard behavior on mac os since Sierra.
On [Stackoverflow](https://stackoverflow.com/questions/96882/how-do-i-create-a-nice-looking-dmg-for-mac-os-x-using-command-line-tools) is a post with multiple ways/tools to create a nice looking installer.

So can this issue be closed?
