### ISSUE TITLE
Is VeraCrypt somehow using/trusting my motherboard's hardware/firmware?

### ISSUE THREAD

**Issue by EAFSC** [veracrypt/VeraCrypt#448]
(This is like the third time over a year that I had to re-post this because it disappeared into the next page with zero replies, thus ensuring that nobody would ever see it. Please answer if you have any idea. I feel worried every single day before I can get this straightened out.)

For ages, I used TrueCrypt. Although I had many ultra-annoying frustrations with that related to new (forced) versions of Windows that required me to decrypt the entire system disk, install the update, and then re-encrypt it (a massive PITA and obvious security risk for 24+ hours), one good thing about it was that it always used a nice, DOS-like password prompt screen, where it at least felt like I was inputting the password "for TrueCrypt only".

Since TrueCrypt died, I eventually switched to VeraCrypt, which I've now used for quite some time. My issue is that VeraCrypt doesn't seem to use this "custom" password screen/program/prompt, but instead (somehow) asks me for the decryption password while the HP logo/BIOS stuff is still showing! I'm sure that this is "by design", but I can't help but get freaked out over this.

Sure, you may say that if I don't trust my computer's BIOS/UEFI/whatever, then I might as well not use it as all, since it controls everything, but that's the thing... I don't trust HP (or any other consumer hardware company) for a second, and the psychological feeling of inputting my decryption password into this "close-to-hardware" mechanism makes me feel as if the motherboard is probably storing my latest successful input in some chip/memory unit, in plaintext, so that "law enforcement" can just stick a little thing onto it and nab it.

Basically: is there any way to make VeraCrypt use its own screen instead of relying on the extreme incompetence and malice of HP/whoever? And if there is, should I switch to that, or is this better in some way? Perhaps this is what avoids having to decrypt/re-encrypt for the frequent (hellish) Windows updates?

I've been trying to ask people about this for a long time, but (like most questions) nobody seems to even understand what I'm saying, and couldn't care less. I hope that you will be able to tell me something useful/enlightening about this.

If it's not possible, don't you consider this a major security issue?

PS: I'm not talking about a "BIOS password" that you can set up in the BIOS settings! That is completely separate from this and obviously does no encryption. Just to be perfectly clear and avoid confusion.

**Comment by GH-Rake** [comment]
I have been using Veracrypt for 3 years and through all the updates have never had this issue.  My motherboard POSTS, I see the BIOS screen, then that screen disappears and then the Veracrypt screen appears.  I don't know anything about how it works at that level but I think your issue of seeing the password prompt and your BIOS logo/information is unique.

If you haven't upgraded to the latest version, it's fantastic with lots of updates/fixes.  Most notable is the ability to use the ReflectDrivers technique of painlessly upgrading Windows 10.  When it's time to do the big upgrades such as 1809 and 1903, download the Windows Media Creator, create an iso, mount it follow this guide: https://sourceforge.net/p/veracrypt/discussion/general/thread/431df6e5/#22cb

It's so simple now, no need to decrypt

**Comment by EAFSC** [comment]
"your BIOS logo/information is unique"

How can you say this so confidently? I have a standard brand PC and have no exotic/special settings. This is what VeraCrypt does...

**Comment by GH-Rake** [comment]
"I think your issue of seeing the password prompt and your BIOS logo/information is unique."

I'm referring to your issue being unique.

**Comment by EAFSC** [comment]
I know you were referring to that. I was as well. And I can't tell why it doesn't do it on your computers. Maybe they are all old. Maybe they are all noname ones that don't feature a BIOS and/or the hardware necessary for this feature to kick in. I'm not running some special version of VeraCrypt, or an old one either.

**Comment by GH-Rake** [comment]
These are my 3 computers FYI:
Acer Laptop with 4th gen i5, unknown mobo
Dell E7440 with 4th gen i5, dell mobo
Custom Desktop with 3rd gen i5, ASRock mobo

I am booting all drives in Legacy mode, are you using Legacy or UEFI?

**Comment by EAFSC** [comment]
Hmm. Couldn't tell you without having to again reboot this machine I'm typing on. But I've changed around those countless settings numerous times in the past, seemingly with no difference.

I mean, this kind of thing doesn't just happen automatically. There must be some understanding in the VeraCrypt source code about this...

The machine is from 2016. HP "ENVY".

What bothers me about this is that nobody has any clue it even can happen. Then again, you are the only one here who even has replied for all this time. It feels surreal to be using this highly sensitive security software while having no idea what it's actually doing and how/why it's somehow hooking into my BIOS/UEFI stuff.

**Comment by GH-Rake** [comment]
I noticed this issue tracker could use some love so I thought I would do my best to help out.  You may want to post your issue @ https://sourceforge.net/p/veracrypt/tickets/ for better visibility, seems that tracker is updated more regularly.

May want to post a picture of the password prompt screen as well just to make sure people understand the issue better.

**Comment by EAFSC** [comment]
@GH-Rake Alright... I will try to make an account there and deal with all that BS... Sigh. Here are the requested (yet ultimately pointless) photos:

Top-left part of the screen: ![1 (1)](https://user-images.githubusercontent.com/46956843/58387654-aa832980-8012-11e9-82c2-66078e9fe4d1.jpg)
Full view of the screen: ![1 (2)](https://user-images.githubusercontent.com/46956843/58387655-aa832980-8012-11e9-8986-8f2024795dca.jpg)
After entering the VeraCrypt password and pressing Enter twice: ![1 (3)](https://user-images.githubusercontent.com/46956843/58387656-ab1bc000-8012-11e9-8c3e-01fe88e07620.jpg)

**Comment by EAFSC** [comment]
@GH-Rake After wasting tons of time filling in the SourceForge registration form, all I got was a retarded "System Error [Client IP address you are attempting the registration from is blocked.]" message... AFTER filling in everything. Not using that site ever again.

**Comment by GH-Rake** [comment]
My password prompt looks like this (except I don't have 1.2)
![](https://guidedhacking.com/gh/sshots/firefox_2019-05-27_14-27-09.png)

I assume the reason is because I'm using legacy and you're using UEFI.  I use legacy mode on all my computers with Veracrypt and they all look like this.

**Comment by EAFSC** [comment]
@GH-Rake Hmm! Interesting, and a mild relief that others have the same screen... or at least similar. It's not identical. Certainly seems to be done by the motherboard... and I don't trust them whatsoever. :/
Can you explain (if you know) why/how the UEFI/BIOS/motherboard "takes over" VeraCrypt's job like this? And is it good or bad? Doesn't seem good to me... And I don't think it used the "legacy" (actual) screen when I used "legacy" options in the BIOS...

**Comment by EAFSC** [comment]
Regarding "not identical": Note that mine says "Password:" but the screen you showed says: "Enter Password:"...

**Comment by GH-Rake** [comment]
here is the difference between the two methods:
![](https://configurationmanagerblog.files.wordpress.com/2017/03/uefi-vs-bios.png)

That's all I know :(

**Comment by ideaman924** [comment]
This is because the manufacturer shows the UEFI logo during boot. You can confirm this with computers from different manufacturers and see how Windows boots up. On computers with UEFI enabled and with manufacturer/OEM branding, the OEM branding will show up in the center of the screen (most likely) as Samsung, Asus, etc, and the spinny loading icon will show below. Laptops usually have these logos, as will desktops - I had the same screen on my Asus desktop, and my Samsung laptop. Some motherboards ship with options in the BIOS to disable this behavior (Boot Logo option in the "Boot" menu, usually. May have different naming) but laptops usually don't have this.

To test if this is true yourself, try booting from a bootable Windows Installer USB stick. On most machines, the spinny logo should show without the OEM logo on top.

So no, it has nothing to do with Veracrypt "trusting" your MB's firmware or hardware - it's just how the UEFI spec works.

**Comment by EAFSC** [comment]
Hmm... Call me stupid, but I still don't understand how the UEFI "takes over" this from VeraCrypt, entirely disabling its own "Bootloader screen" with the password input which I got so familiar to with TrueCrypt for years... But it must be a "feature" which is in some way "good"? I guess? I don't want to sound rude because you took the time to answer, but the answer is rather fuzzy to me and doesn't seem to directly address what I was wondering.

Also, why do they output a bunch of numbers and crap in the end, as seen on the third image of mine? This whole thing just smells fishy to me.

**Comment by ideaman924** [comment]
UEFI doesn't "take over", rather, it just loads Veracrypt from the EFI partition on the hard disk (or solid state drive). The 400MB or so FAT partition at the start of the disk is the EFI partition, and there are loaders created by Microsoft/Veracrypt in there.

More information on this: https://www.reddit.com/r/Windows10/comments/79fqy9/asus_logo_instead_of_windows_10_logo_during_boot/

I'm not an expert on EFI, but what I understand is the UEFI does the major work of communicating with hardware, and the loader concentrates on communicating with the UEFI portion of the motherboard to get everything up and running. Before when we had BIOSes, the software vendor (in this case, Microsoft) would have to write a bootloader that loaded the kernel and the rest of the operating system. This was rather kludgy because you didn't have access to drivers in this pre-boot stage, which meant that a lot of advanced features and security things were not possible (such as native GPU resolution booting, for example).

To solve this (or rather, try and solve it; we're pretty terrible with standardizing things) the UEFI extension was created. The "loader", or the dot EFI files inside the standard EFI partition, would initialize the kernel and OS. But the loader isn't a bootloader, in a traditional sense. Rather, it's a set of "instructions" the UEFI portion follows to initialize everything. This is great because the UEFI implementation, while bad, still has hooks for video cards to get into, to get that native resolution during boot, and have advanced security features like Microsoft's Secure Boot.

Therefore, because the bootloader equals UEFI, manufacturers have free rein over what they can do with their implementations, resulting in what you see above. You could disable this feature on desktop motherboards (see the Reddit link) but laptops usually don't have them because of branding issues.

As for the random numbers, I can only presume they're memory addresses - maybe for loading Microsoft's loader or some other program to initialize the operating system based on the unencrypted disk.

**Comment by VA1DER** [comment]
This is not correct.  UEFI passes control to the code of the bootloader just like BIOS used to pass control to the code of the master boot record.  UEFI provides a bit more modern interface, a bit more modern method of loadign the bootloader (it doesn't have to be a 512 byte single sector worth of code any more that chains to multiple successive stages to work), but in essence it is the exact same thing.  UEFI and BIOS are both firmware that:

1. Initializes the hardware
2. Looks for a bootloader in a specific special place
3. Loads the bootloader code
4. Provides the bootloader code with interface functions to be able to access hardware

What graphic happens to be on the screen when the bootloader gets control is irrelevant.  It is the bootloaders code that is executing.  That being said, a preboot authentication system is impossible to write that takes and retains complete control.  At some point UEFI firmware API calls will have to be made because this is how a bootloader interfaces with hardware.  If you think that your UEFI firmware is spying on keypresses, there is nothing a bootloader can do.  Sure, it could try and access the keyboard hardware directly rather than using keyboard input routines proved by UEFI API functions, but the firmware could still be spying on keypresses.

Please review [this page](https://wiki.osdev.org/UEFI) for more details on how it all works.

Now, that all being said, we should talk about some politeness here:

> (This is like the third time over a year that I had to re-post this because it disappeared into the next page with zero replies, thus ensuring that nobody would ever see it. Please answer if you have any idea. I feel worried every single day before I can get this straightened out.)

The author has set up a forum for this kind of discussion.  This is not that place.  Creating a trouble ticket multiple times just to get your personal queries answered is rude and selfish.  Please stop.  This makes the whole issue tracker useless to the developer.

> After wasting tons of time filling in the SourceForge registration form, all I got was a retarded "System Error [Client IP address you are attempting the registration from is blocked.]" message... AFTER filling in everything. Not using that site ever again.

This is, of course, a personal choice.  But that is where the forum for this type of question is.  Use it, don't use it, that's up to you.  Just stop using issue reporting as a way of getting people's attention because you can't be bothered to get your account working in the correct place.

**Comment by EAFSC** [comment]
@VA1DER You talk about "politeness" while grossly insulting me... That's odd.

How is it a "personal choice" that the broken site doesn't let me create an account, *after* I spent all the effort of filling in their stupid form? What kind of twisted brain could possibly turn this around on *me*?! Seriously.

"Use it, don't use it, that's up to you."
That's the whole point: it's NOT up to me. Didn't we establish that the site in question is broken and doesn't let me register?

"you can't be bothered to get your account working in the correct place."
If your arrogance and ignorance displayed here is reflected in VeraCrypt's code, I fear even more now than before for my security.

**Comment by VA1DER** [comment]
>  You talk about "politeness" while grossly insulting me...

I did not _insult_ you.  I pointed out your _actions_ were selfish.  There is a big difference.

> How is it a "personal choice" that the broken site doesn't let me create an account, after I spent all the effort of filling in their stupid form? What kind of twisted brain could possibly turn this around on me?! Seriously.

> If your arrogance ...

That's a bit rich.  SourceForge is used by millions of people.  I am not the one being arrogant here.  Your assumption that because _you_ have encountered a problem there it means that _their_ site is broken is where the arrogance lies.  More likely the issue is with your browser or is a simple PEBCAK.  Jumping from "I had troubles with it" to "the site is broken" is the same behaviour you displayed when you didn't get the answer you wanted here to a technical question, and then proceeded to enter multiple issues in a place intended for bug reports because your curiosity wasn't being satisfied.

Sort out your account on SourceForge.  Use the forum there.  There are people, including myself, who will be happy to help you there.  Stop taking up developer time here with background questions.  This place is for issue reporting.

**Comment by EAFSC** [comment]
@VA1DER "SourceForge is used by millions of people."
Windows is used by billions of people, so it must be the optimal operating system...

"Your assumption that because you have encountered a problem there it means that their site is broken is where the arrogance lies."
Yeah, it's totally crazy that I think their site is broken for not allowing registrations with a nonsensical "error" that is only shown *after* filling it in and submitting. Of course.

"a simple PEBCAK."
Let's hear you explain how this is my fault. You keep claiming this, but provide zero reasoning behind it. This is a pure insult.

"a place intended for bug reports"
For all I knew, this *was*/is a bug, but apparently not. And it doesn't matter how "off-topic" it is *when it's the only place where I'm allowed to ask anything* (and not even that is true, apparently).

I'm really annoyed by people who act stupid and "refuse to understand" things.

"Sort out your account on SourceForge."
I didn't code their broken site. I have no idea what you mean by "sort out", but I don't control them in any way.

**Comment by thewriteway** [comment]
This is behaviour seemingly unrelated to issue with Veracrypt code. Recommended closure.

**Comment by alt3r-3go** [comment]
@idrassi, I'd second the closure suggestion.

The question was pretty much addressed in full by @VA1DER in his [comment](https://github.com/veracrypt/VeraCrypt/issues/448#issuecomment-509021525) and the rest is irrelevant.

@EAFSC, just to sum it up in one sentence - the logo and VeraCrypt's prompt being visible at once is not a sign of any security problems or that UEFI (the "HP" part) "takes over" VeraCrypt. They both just interact in a perfectly expected way, per the UEFI spec which is outlined in the wiki article linked by @VA1DER.

If you have any further technical problems or longer questions/considerations - please feel free to post a GitHub "issue" for the former and start a forum thread for the latter (hopefully SourceForge would work for you this time). If SF still refuses to cooperate :smiley:, post here and I'll look into that.
