### ISSUE TITLE
Encrypt the whole drive greyed out

### ISSUE THREAD

**Issue by ThatWeirdAndrew** [veracrypt/VeraCrypt#451]
When I try to encrypt my drive, I noticed that Encrypt the whole drive is encrypted. Does anyone know why this is happening? I am running version 1.24-Beta 5 but it also happened on 1.23. I have Windows 10 x64 Build 18362

**Comment by Kadilov** [comment]
I have the same issue. I reported it on Sourceforge today:

> If I go "System" in menu bar, "Encrypt System Partition/Drive..." , "Normal": "Encrypt the whole drive" is greyed out.
> I have updated Windows 10, SSD with GPT, standart partitions made by Windows installer plus some unallocated space.
> I tried 1.23 Hotfix-2 with Secure Boot enabled, 1.24 Beta-5 with Secure Boot enabled and disabled.
> Also it is an Acer laptop if it means something.

https://sourceforge.net/p/veracrypt/discussion/technical/thread/08c604bdf7/

**Comment by Kadilov** [comment]
I got an answer on Sourceforge and realised that you can not encrypt "the whole drive" with GPT as Windows needs an unencrypted partition to start boot process. You can still encrypt the main Windows partition on GPT disk. I am not sure if original poster had MBR or GPT, but I have no issues with VeraCrypt at the moment.

**Comment by worldsdream** [comment]
@kadilov gave the perfect answer. Thats right.

**Comment by ThatWeirdAndrew** [comment]
Thanks for the help @Kadilov

**Comment by StanDog** [comment]
> I got an answer on Sourceforge and realised that you can not encrypt "the whole drive" with GPT as Windows needs an unencrypted partition to start boot process. You can still encrypt the main Windows partition on GPT disk. I am not sure if original poster had MBR or GPT, but I have no issues with VeraCrypt at the moment.

I don't understand. Isn't VeryCrypt running in background and decrypting the starting partition too? And why does such a big corporation like Microsoft defines such an insecure concept (the mandatory to start from an unencrypted partition)? :o Also, their own encryption program (Windows BitLocker) is encrypting the entire drive too (afaik) and Windows can still start from it. This is very disappointing.. :(

**Comment by GH-Rake** [comment]
> 
> 
> > I got an answer on Sourceforge and realised that you can not encrypt "the whole drive" with GPT as Windows needs an unencrypted partition to start boot process. You can still encrypt the main Windows partition on GPT disk. I am not sure if original poster had MBR or GPT, but I have no issues with VeraCrypt at the moment.
> 
> I don't understand. Isn't VeryCrypt running in background and decrypting the starting partition too? And why does such a big corporation like Microsoft defines such an insecure concept (the mandatory to start from an unencrypted partition)? :o Also, their own encryption program (Windows BitLocker) is encrypting the entire drive too (afaik) and Windows can still start from it. This is very disappointing.. :(

How would BIOS find the master boot record if the disc is encrypted?  The Veracrypt boot loader is started by referencing the master boot record, if it's encrypted BIOS can't start the boot loader.  If you wanted the MBR to be encrypted you would need a VeraCrypt bios, which is outside the scope of this project.  Especially when you take into account the need for compatibility with so much hardware.

One of the absolute best guides to the process is available at: https://neosmart.net/wiki/mbr-boot-process/

**Comment by Kadilov** [comment]
> How would BIOS find the master boot record if the disc is encrypted? 
I suppose this thread was devoted to discussing VeraCrypt working with GPT disks, because in my experience this situation with a checkbox ("Encrypt the whole drive greyed out") happens with GPT, not MBR.
In both cases, there must be some unencrypted data on a hard disk to start the booting process, whether it is MBR record or EFI partiotion in case of GPT. The only way to overcome it is to use the second storage for this data, i.e. a thumb drive. Bitlocker works in the same way, see Microsoft FAQ: "Why are two partitions required? Why does the system drive have to be so large?" 
https://docs.microsoft.com/pt-pt/windows/security/information-protection/bitlocker/bitlocker-overview-and-requirements-faq#why-are-two-partitions-required-why-does-the-system-drive-have-to-be-so-large
It's the same in Linux, though encryption on GPT disks is a bit more convenient there because multiple partitions can be joined in a single LVM volume and encrypted all together, so a user may have an EFI partition to boot and an encrypted logical volume with multiple physical partitions inside of it.
