### ISSUE TITLE
No tray icon on Ubuntu 18.04

### ISSUE THREAD

**Issue by djalilhebal** [veracrypt/VeraCrypt#461]
Unlike the Windows version, VeraCrypt does not appear on tray not even when closed (as opposite to "exited").
To do any action (mounting/unmounting/etc.), I now have to rerun the program which gives me this annoying warning: "VeraCrypt is already running."
![linux-already-running](https://user-images.githubusercontent.com/32184973/58860385-e9b11a80-86a3-11e9-9888-6ed004b0a93f.png)

This must be an error because there is no problem with other apps like Telegram as you can see:
![linux-tray](https://user-images.githubusercontent.com/32184973/58860406-f2a1ec00-86a3-11e9-80a3-c00a974d2df0.png)

**VeraCrypt version:** 1.23

**OS:** Ubuntu 18.04 x64

**Installed/Activated extensions:**
- Ubuntu dock
- Ubuntu appindicators
- User themes
- Add username to top panel
- Places status indicator

**Related/same(?) issue:** #211

**Comment by unit193** [comment]
Howdy,

This happens because VeraCrypt only has a tray icon, and GNOME has dropped support for that (as well as appindicators, but since you use Ubuntu you get those back by default.)  If you want the tray icon back, you have several options:

1. Use a DE that supports them, literally any other desktop will do.
2. Use an extension such as TopIcons Plus to add the system tray back.
3. Use a patch such as [this](https://salsa.debian.org/debian-edu-pkg-team/veracrypt/blob/master/debian/patches/002-indicator-support.diff), install one of the development headers and recompile VeraCrypt.  This converts VeraCrypt to appindicators.

Hope one of these helps!

~Unit 193

**Comment by he7d3r** [comment]
This also happens on Ubuntu 20.10.

**Comment by idrassi** [comment]
For the related "already running" dialog mentioned here, the Linux second-instance behavior has been improved on master: https://github.com/veracrypt/VeraCrypt/commit/fc2efd0b8f55f3539c02de7e9fb70a71f73c8fa2

When relaunching VeraCrypt successfully hands off to the running instance, the modal `VeraCrypt is already running` dialog is no longer shown.
