### ISSUE TITLE
Cannot paste password from clipboard on Mac OS

### ISSUE THREAD

**Issue by Joncom** [veracrypt/VeraCrypt#463]
Apparently, password managers are a good security practice these days. However, this means that passwords are typically long, strong, random, and hard to remember/type. That's fine because we can just copy paste passwords. But there's a problem with VeraCrypt: it won't let passwords be pasted, while mounting any drive. Actually, that's only half true. Passwords can be pasted, if you first check the "show password" checkbox. But that obviously poses a security risk (cameras, or people looking over your shoulder). Why can't passwords just be pasted normally? Running VeraCrypt 1.16.

**Comment by jonathancross** [comment]
@Joncom Please try with the latest version 1.23.  If it still doesn't work, you should specify what exact version of MacOS you are running, any extensions, etc which might be blocking things, etc.

**FWIW:** In MacOS Mojave, I am able to copy/paste passwords, but cannot have KeepassXC write the password directly into the password field.  (direct writing works fine in Truecrypt)

Instead, the password is always written into the file location field in the window underneath.

I noticed that tabbing between apps makes the password field lose focus in Veracrypt, but not in Truecrypt, so that may get us a little closer to debugging.  I would strongly prefer to have the password written directly into the field than have it sitting on my clipboard for other processes to access (or accidental paste somewhere).

**Comment by Joncom** [comment]
Version 1.23 doesn't have the issue.
