### ISSUE TITLE
Causes crash on xorg-x11-server-Xwayland on Linux (OsLookupColor(): Segmentation fault)

### ISSUE THREAD

**Issue by rugk** [veracrypt/VeraCrypt#477]
for the crash report see https://bugzilla.redhat.com/show_bug.cgi?id=1729200#c14

VeraCrypt 1.22
Fedora 30
GNOME 3.32
Wayland/XWayland

**Comment by alt3r-3go** [comment]
Thanks for reporting, but looking at the RedHat Bugzilla entry, this doesn't seem to be specific to VeraCrypt - other programs reported there as well. Moreover, a root cause has also seemingly been found and fixed: https://bugzilla.redhat.com/show_bug.cgi?id=1729200#c9:

> “glamor_get_modifiers+0x767” is xwl_glamor_gbm_create_pixmap() so this is the same as bug 1729925 fixed upstream with https://gitlab.freedesktop.org/xorg/xserver/merge_requests/242

So looks like we just need to wait until it makes it into the Wayland release.
