### ISSUE TITLE
Abnormally Low Performance on Ryzen Zen 2

### ISSUE THREAD

**Issue by gashtal** [veracrypt/VeraCrypt#478]
Techpowerup's test results show abnormally low performance for AES encryption using Veracrypt on the latest Ryzen Zen 2 CPUs, even lower than previous-generations Ryzen CPUs:

https://www.techpowerup.com/review/amd-ryzen-9-3900x/12.html

Is there something inherently wrong with these CPUs that is causing this problem, or does Veracrypt need to be updated to be able to utilize the full performance of these CPUs?

**Comment by Schweineschwarte** [comment]
Which operating system do you use?
It looks like the same problem I have: https://github.com/veracrypt/VeraCrypt/issues/474
But I have the problems with an Intel Core i3-2350M and an AMD Ryzen 5 2600 (Zen+).

**Comment by idrassi** [comment]
Just in case, can you please check that VeraCrypt detects AES-NI correctly with this CPU? It is displayed when you open the benchmark dialog. In my opinion it is correctly detected.

Thus, there must be an issue with this CPU and its AES-NI capability because the VeraCrypt code that handles AES-NI is implemented in a generic way that should work on all modern CPU that support pipelining.

The implementation is simple: we process 15 AES blocks at a time in 64-bit mode by issuing 15 calls to AES-NI instructions and the CPU will pipeline these calls in order to process the 15 blocks in parallel using all available AES-NI cells.
The code that do this is here: https://github.com/veracrypt/VeraCrypt/blob/master/src/Crypto/Aes_hw_cpu.asm#L151

To me it looks like this new CPU has an issue with pipelining AES-NI calls. It would be interesting to see how it will react if we reduce the size of the pipeline (for example to 7 like in 32-bit mode) or if we make it larger.

I don’t have access to such CPU to check this hypothesis but I will try to develop a tool that allows to set pipeline size for AES-NI benchmark to that others can verify.

Anyway, it’s clear to me that this CPU has an issue with AES-NI feature.

**Comment by gashtal** [comment]
Sorry for late reply, I had totally forgotten about this issue.

Anyway, I do not actually have a Ryzen CPU right now, but since I might consider upgrading to one in future, and I use Veracrypt on a daily basis, low veracrypt performance would be a dealbreaker for me. This is why I opened this ticket so that the issue could be looked at by the developer of Veracrypt and a fix could be provided if possible, which would benefit all Veracrypt users that use these CPUs.

**Comment by marcenone** [comment]
I can fully confirm problems with proper AES encryption/decryption speed with veracrypt running on windows 10 x64 bit and Ryzen 5 3600. Driver configuration tab and test show speed of encryption/decryption approximately around 6,4 GB/s which is (in theory) 25% faster than the result on previous cpu intel 4690K hitting 4,8 GB/s Problem is that decrypting 120gb ssd on Ryzen took about 1h whereas on intel 30min. Can you provide any solutions Mounir or at least pinpoint where the problem is ?

> 
> 
> Just in case, can you please check that VeraCrypt detects AES-NI correctly with this CPU? It is displayed when you open the benchmark dialog. In my opinion it is correctly detected.
> 
> Thus, there must be an issue with this CPU and its AES-NI capability because the VeraCrypt code that handles AES-NI is implemented in a generic way that should work on all modern CPU that support pipelining.
> 
> The implementation is simple: we process 15 AES blocks at a time in 64-bit mode by issuing 15 calls to AES-NI instructions and the CPU will pipeline these calls in order to process the 15 blocks in parallel using all available AES-NI cells.
> The code that do this is here: https://github.com/veracrypt/VeraCrypt/blob/master/src/Crypto/Aes_hw_cpu.asm#L151
> 
> To me it looks like this new CPU has an issue with pipelining AES-NI calls. It would be interesting to see how it will react if we reduce the size of the pipeline (for example to 7 like in 32-bit mode) or if we make it larger.
> 
> I don’t have access to such CPU to check this hypothesis but I will try to develop a tool that allows to set pipeline size for AES-NI benchmark to that others can verify.
> 
> Anyway, it’s clear to me that this CPU has an issue with AES-NI feature.

**Comment by idrassi** [comment]
@marcenone your feedback seems different from previous ones since in your case VeraCrypt benchmark do show a gain with Ryzen compared to its Intel counterpart but this gain vanish when performing real I/O operations.

I don’t have access to a PC with Ryzen CPU so I’m not able to give any technical analysis. That being said, one possibility is that there is some kind of penalty for Ryzen when there are several context switches between AES-NI and standard CPU operation for I/O.

There is also the possibility that it has to do with I/O performance issue. For that, one need to check the performance of this SSD with Ryzen and with Intel without encryption (for example by perfuming a full format of the SSD on both CPU and see if you have the same I/O speed). Can you do this test? This will help check if it is really an AES issue or just I/O issue.

**Comment by nikkopt** [comment]
Running the included benchmark, i get 14GB/s on my 3700X but running crystaldiskmark on a container stored in my nvme ssd gets me much lower speeds compared to running it directly on the disc itself. Container is using AES. Latest version of VC and Win10.

My "normal" speeds:
![1](https://user-images.githubusercontent.com/2060960/87693227-9d7c4900-c784-11ea-9d14-54630a624e57.PNG)

Speeds of a container on my ssd:
![2](https://user-images.githubusercontent.com/2060960/87693280-b08f1900-c784-11ea-870b-178e19576994.PNG)

Benchmark:
![3](https://user-images.githubusercontent.com/2060960/87693320-bbe24480-c784-11ea-8c2e-151191bf4c8a.PNG)
![4](https://user-images.githubusercontent.com/2060960/87693328-bedd3500-c784-11ea-97ff-d5222ddc6a54.PNG)

**Comment by gashtal** [comment]
Th new Zen 3 desktop CPUs are out and unfortunately, the same performance issue with Veracrypt seems to persist  in the new CPUs. In fact, looking at the benchmark results published by Techpowerup, older Ryzen CPUs perform better than newer ones, and surprisingly enough, Ryzen CPUs with _less_ cores also perform better than ones with more cores!

https://www.techpowerup.com/review/amd-ryzen-9-5900x/13.html

**Comment by nikkopt** [comment]
@gashtal you are still getting 11 gigabytes a second. You will never be able to reach those speeds even with several nvme drives in raid 0, doesn't matter if you have intel or amd. Also, i don't think the lower speeds are a software problem. More like amd's implementation of AES-NI is weaker than intel's.

**Comment by idrassi** [comment]
In order to check the performance of AES-NI in Ryzen Zen2 and Zen3 CPU, I have prepared a benchmark program that computed speed of AES-NI using 3 different implementation approaches: 

- 15-way: process 15 blocks in parallel. This is the method used by VeraCrypt
- 7-way: process 7 blocks in parallel.
- 4-way: process 4 blocks in parallel.

Normally 15-way method should be fast or at least comparable in speed to the other approaches.

I have attached a zip containing the program and its PGP signature using VeraCrypt official PGP key. The exe is also signed using the same code signing certificate as VeraCrypt binaries.

Can someone with access to Ryzen Zen2 or Zen3 CPU post the output of the program? Maybe these CPUs don't like the large number of blocks processed in parallel.
Thanks.

[AesNiBenchmark.zip](https://github.com/veracrypt/VeraCrypt/files/5685883/AesNiBenchmark.zip)

**Comment by nikkopt** [comment]
Greetings,
Ryzen 7 3700X at stock with 3600MHz ram

`64-bit AES-NI Benchmark by Mounir IDRASSI (mounir@idrix.fr)
Version 2020-12-13

CPU has AES-NI extension: YES

AES-NI 4-way: ok (Enc = 6968.35 MB/s, Dec = 6983.54 MB/s)
AES-NI 7-way: ok (Enc = 7696.82 MB/s, Dec = 7704.60 MB/s)
AES-NI 15-way: ok (Enc = 7093.13 MB/s, Dec = 6899.22 MB/s)`

Seems to only use one core. If i benchmark it through veracrypt itself i get almost double the speed and it uses all cores (don't know if it's because it also benchmarks other algorithms that don't have HW acceleration)

**Comment by gashtal** [comment]
Opening this again since it is an important performance issue affecting all Zen-based generations of AMD CPUs.
