### ISSUE TITLE
Legal inquiry regarding the terms and conditions

### ISSUE THREAD

**Issue by Van-Fouran** [veracrypt/VeraCrypt#495]
In Germany, it is mandatory that the terms and conditions must be understandable. The Federal Office of Justice and Consumer Protection writes explicitly: "The terms and conditions must be presented in the language in which the contract negotiations have been conducted, usually, this will be German." (https://www.bmjv.de/DE/Verbraucherportal/KonsumImAlltag/AGB/AGB_node.html)
I have been asked several times that VeraCrypt itself is available in German and therefore also for users with bad English knowledge users, but the terms and conditions within the German version are displayed in English. I am NOT a lawyer, so I can not conclusively say if this approach is a problem in Germany. Does anyone know more?

**Comment by Van-Fouran** [comment]
Can anyone make a statement as to whether this is a problem?

**Comment by idrassi** [comment]
I can't really answer from the legal point.
The current terms and conditions of VeraCrypt are derived from the text that existed on TrueCrypt and they use special legal phrasing and so translating them to another language requires someone with legal training background in the target language.
If someone can provide such translation, I would be happy to include it.
Meanwhile, I hope that there is some exception for open source software like VeraCrypt because I'm not sure that all open source projects can afford translating their terms and conditions to German using legal language and not some automatic translation.
