### ISSUE TITLE
Import keyfile to PKCS#11 token non-interactively

### ISSUE THREAD

**Issue by mtausig** [veracrypt/VeraCrypt#497]
I would like to create a Veracrypt volume with a keyfile on a PKCS#11 token in a completely non-interactive fashion from a script.

The problem is, that the `--import-token-keyfiles` switch ignores the values passed with ``--keyfiles` and `--new-keyfiles` and instead asks for the keyfiles via stdin:

https://github.com/veracrypt/VeraCrypt/blob/2ab57bcf7074449a1088dbffac4e221eadc24631/src/Main/TextUserInterface.cpp#L1059

**Comment by idrassi** [comment]
Thank you for reporting this.
I have pushed a commit that implements non interactive supported for the —import-token-keyfiles switch: https://github.com/veracrypt/VeraCrypt/commit/c8beacbdd70c29f9c4a38c43c52c557b30d37fe2

Now this switch will first look for key files passed using the switch —keyfiles: if it finds it, it will use it otherwise it will check if we are in non interactive mode: if yes, it will throw an error, otherwise it will request keyfiles from command line.
You can build VeraCrypt from source to use it. It will be included in upcoming 1.24 release.
