### ISSUE TITLE
Feature Request: Post-Quantum encryption support

### ISSUE THREAD

**Issue by kratosok** [veracrypt/VeraCrypt#498]
### Summary

Please add Post-Quantum Encryption options.
https://csrc.nist.gov/Projects/Post-Quantum-Cryptography

### Motivation

With the growth of Quantum computing, it would benefit all privacy minded individuals to have encryption options that are resistant to quantum computing attacks. NIST is currently reviewing and refining the the options presented to make quantum resistant advice available.
A number of the lattice based encryption schemes don't have a significant impact on throughput. Some even have existing advice (Kybers-768 combined with say AES)
A number of the the lattice based encryption schemes are already usable in library form:
https://openquantumsafe.org/#liboqs

**Comment by alt3r-3go** [comment]
@kratosok, NIST's PQ project is mainly about public-key crypto, because that's what quantum computers are supposed to break effectively enough. Symmetric crypto, which is the basis for VeraCrypt, stands generally okay - in a nutshell, we'll may be just fine with only longer keys (twice as long for the same classic security level), so if you're using AES-256 and SHA512 as a PRF, you're generally okay for the foreseeable future, at the current level of knowledge. It's the signatures, key establishment and public key encryption that need new algorithms, but VeraCrypt doesn't use any of them.

And in any case, don't expect any standards before ~2023 (my estimate based on watching the PQ Crypto mail list), as there will be a third round and it is supposed to begin only sometime mid-next year. Some folks called for even longer timeframes given that this is a new area and it's only now getting new PhD students' and researchers' attention.

**Comment by Van-Fouran** [comment]
@kratosok I can confirm what @alt3r-3go says.

**Comment by CodingSpiderFox** [comment]
@alt3r-3go just to fill my knowledge gaps - what exactly does key establishment mean? Do you mean session key generation on TLS protocol?

**Comment by alt3r-3go** [comment]
@CodingSpiderFox, yes, that is one good example.
