### ISSUE TITLE
Fix issues of Truecrypt audit part 1

### ISSUE THREAD

**Issue by JHGitty** [veracrypt/VeraCrypt#5]
Are all issues from the Truecrypt audit part 1 fixed?
https://opencryptoaudit.org/reports/iSec_Final_Open_Crypto_Audit_Project_TrueCrypt_Security_Assessment.pdf

**Comment by idrassi** [comment]
The TrueCrypt audit part 1 lists 11 issues.
In VeraCrypt, 8 issues were fixed (1, 3, 4, 5, 6, 8, 9, 10).

Issue number 2 is not realistic since it supposes that the system will page out the stack memory of the mount call. As described in the audit, this would require the attacked to force the system to gave low kernel memory but the atacker has such capability, then he can perform more simpler attacks. On the other hand, the effort to fix this potential issue is high since one must create a single memory array in non-paged memory that will emulate the standard stack. Since there are more important things to implement, this was left till more time is available.

Issue number 7 supposes that an attacker that has a restricted account on a machine will use the mount call of TrueCrypt/VeraCrypt in order to gain information on files visible to the local machine and for which he doesn't have permissions to access. The information he would gain are minimal (presence or not of the file, size smaller or bigger than 4096 bytes and if the file is a TrueCrypt/VeraCrypt volume).
The fact that the attacker must be local to the machine and the fact that the gatherer information are not so sensitve make this issue not a realistic threat. As for the previous issue, the cost of the modification is not negligible and so it was decided to leave it for a future release.

Issue number 11 is the most unrealistic of all. If any failure happens in the low level encryption function, then the whole system is expected to fail and we can't trust any other function to give correct results. Of course, it doesn't harm to add checks to stop in case of unexpected errors but as for the previous two issues, the cost of the modification is very high compared to its gain in real world situations.
