### ISSUE TITLE
VeraCrypt 1.24 Availability for Screen Readers

### ISSUE THREAD

**Issue by Dyaminigo** [veracrypt/VeraCrypt#536]
Because of vision problems, I use a computer with screen readers.
Prior to VeraCrypt 1.24, the program was fully accessible for screen readers (all buttons, context menus, pop-ups, and other elements were fully accessible and understandable). But from version 1.24, the screen reader no longer utters absolutely all contextual and system menus, but at the same time, buttons, drive letters, and various switches are sounded fine. I do not know what this may be connected with, but absolutely all the menus (system menu, ALT menu, context menus) are no longer processed by screen readers.
When I try to navigate through any context menu, my screen reader is silent and doesn't say anything to me. Prior to version 1.24 with VeraCrypt, everything was fine. I beg you, restore VeraCrypt to screen readers. My friends and I really like this program and the opportunities that it provides for protecting personal data, and we would very much like to use it further.

P.S. Sorry for my English. The message was typed through Google translator.

**Comment by idrassi** [comment]
Thank you for reporting this issue and giving these details. I will try to see where this regression comes from.

Can you please indicate on Which operating system are you having this issue? I suspect it’s either Linux or MacOSX because only on these we changed the UI toolkit used.

**Comment by Dyaminigo** [comment]
The problem appears in Windows 10 Pro 1809 and 1903, and exclusively in VeraCrypt 1.24. VeraCrypt 1.23HF2 and later are fully available for screen readers.
The strangest thing is how the problem manifests itself. All buttons, switches, fields for editing are still spoken by screen readers, but all context menus in all, even distant places of the program, completely stopped being processed by screen readers.

**Comment by idrassi** [comment]
This is indeed strange. The only change in UI done in Windows version is located in Volume Creation Wizard so the cause is something else.

There is a change in version 1.24 where we added a security mechanism that prohibits non-admin processes from accessing VeraCrypt application memory. This was done to protect again attacks by malicious software that tries to read sensitive data form VeraCrypt memory.
Maybe the screen reader application is actually accessing VeraCrypt memory in order to get access to some UI elements and this change is blocking it in this case.

In order to test this theory, I can share with your a test version where this protection is disabled so you can test it and see if it fixes the problem.
If yes, then I will add an option to disable this security feature.
Is this OK for you?

**Comment by Dyaminigo** [comment]
Yes OK. Let's try the test version.

**Comment by idrassi** [comment]
Thank you for accepting to test.
Here is a zip file containing a modified VeraCrypt.exe file: 
[VeraCrypt_Test_ScreenReader.zip](https://github.com/veracrypt/VeraCrypt/files/3799834/VeraCrypt_Test_ScreenReader.zip)

In order to test, make sure to exit the current running VeraCrypt process (using context menu in system tray) and then replace the file "`C:\Program Files\VeraCrypt\VeraCrypt.exe`" by the one in the zip (of course backup first the original version first to restore after test).

This modified VeraCrypt.exe is signed using the same code signing certificate as official VeraCrypt binaires and its SHA256 is `806D13F189A0367D7C7DA6FDF7C0DCD46DF75F50CA313C67CED5A46188C01043`.

**Comment by Dyaminigo** [comment]
You were right, the problem is a new security feature. The test version is superbly available for screen readers. It’s a pity that I will not be able to take advantage of the additional protection provided by VeraCrypt user interface protection from third-party processes, but there is nothing to be done.
Please tell me, can I use this test version so far until you have made a release that will have a switch that disables user interface protection?

**Comment by idrassi** [comment]
Thank you for the confirmation.
Yes you can use this test version since it a built using the same source code as the official one except for the protection mechanism part.
I will implement a configuration option for this security mechanism and I will update this issue when it is done.

**Comment by Dyaminigo** [comment]
Thank you for your prompt answers and help in finding the problem. So far I will close this issue, but I will look forward to updates.

**Comment by Dyaminigo** [comment]
Dear @idrassi, I wanted to remind you of the problem. I didn't find the customization switch you promised to make in VeraCrypt 1.24 Update2. That's why this version is also not available for screen readers. :(

**Comment by idrassi** [comment]
@Dyaminigo I apologize for the missing feature. Indeed I was not able to find a way to implement a switch to disable the memory protection mechanism without reducing the overall security of this mechanism.

So, here is a link to get an official build of VeraCrypt.exe with the memory protection disabled like what I did before:
[VeraCrypt_1.24-Update2_ScreenReader.zip](https://github.com/veracrypt/VeraCrypt/files/3978559/VeraCrypt_1.24-Update2_ScreenReader.zip)

It is not an easy task as I was thinking before. As a last resort, I can make this protection dependent on a flag stored on Window Local Machine registry but I wanted to avoid this and use the usual XML file to store it so that it can be portable.

**Comment by Dyaminigo** [comment]
@idrassi It is sad that you cannot find an elegant solution to implement this setting in VeraCrypt. I hope that sooner or later you will be able to find an acceptable option that would not reduce the overall security mechanism. Thank you very much for the assembly with the functionality disabled and for remembering the problem and trying to solve it. I respect your work and its result - VeraCrypt!

**Comment by Dyaminigo** [comment]
Dear @idrassi, thank you very much for restoring screen reader support in Update 4!
