### ISSUE TITLE
Linux and Mac: Benchmark error on Hash Algorithm in debug mode

### ISSUE THREAD

**Issue by yodra** [veracrypt/VeraCrypt#542]
If you run VeraCrypt in debug mode, the algorithm benchmark fails with Hash test. The call of this function is `if_debug (ValidateDigestParameters (buffer));`

No debug mode does not give this error.

It has been tested in VeraCrypt 1.23 and 1.24_Hotfix getting the same error.

<img width="592" alt="Screenshot 2019-11-13 at 11 57 47" src="https://user-images.githubusercontent.com/7188403/68762492-2c413080-060e-11ea-8054-282b37a8fb0b.png">

**Comment by alt3r-3go** [comment]
That's because the benchmark dialog passes a [buffer of size 1024](https://github.com/veracrypt/VeraCrypt/blob/master/src/Main/Forms/BenchmarkDialog.cpp#L321) to all calls of `GetDigest()` and in the debug mode the latter indeed does check for the buffer to have the exact size of the specific hash output.

```cpp
if (buffer.Size() != GetDigestSize ())
	throw ParameterIncorrect (SRC_POS);
```

@idrassi, do you think it would be better to check for `>=` condition instead? Essentially we care about it being indeed not smaller than the hash output only. I can prepare a PR for fixing this.

**Comment by idrassi** [comment]
@yodra Thank you for reporting this.

@alt3r-3go : I agree with your analysis. A PR to fix the check would be helpful, thank you.

**Comment by alt3r-3go** [comment]
Will do, thanks!
