### ISSUE TITLE
"Evil maid" attack warning after updating to 1.24 Hotfix1

### ISSUE THREAD

**Issue by zeffy** [veracrypt/VeraCrypt#547]
Alright so I'd appreciate some guidance here, if possible. 

- A couple days ago, I updated to 1.24 Hotfix1 and did not restart immediately.
- Today, I shut my PC down for the first time since installing the update, before leaving it unattended for several hours. 
- During this time, persons I don't explicitly trust *did* have physical access to my machine.
- I returned to my machine and booted it up, and received this warning message:

![Untitled](https://user-images.githubusercontent.com/10877719/68986949-6b44d100-081c-11ea-824a-d20407e6397d.png)

I followed the directions immediately. 

But before I make assumptions/accusations about this "evil maid", I need to be absolutely sure, is there a chance something else could have caused this? E.g. something in the hotfix update, a faulty RAM module, hard drive, something facilitated from the software side (rather than physical access), or *anything* else I can look at?

Any ideas? Thank you for your time.

Edit: Here's some more relevant information:

- No FlexNet licensing software installed.
- First version of VC I encrypted my drives with on this machine was 1.23-Hotfix2.
- No hidden volumes.
- No custom bootloader message.
- AES/SHA-512.

**Comment by idrassi** [comment]
Thank you for sharing all these details.
Indeed there has been in the past reports of false positives regarding Evil Maid attacks detection but you don’t seem to be in this case since you didn’t have this problem with 1.23-Hotfix-2 and I’m not aware of any regression in 1.24-Hotfix1 that would cause this error to appear.

Did you receive a message before Evil Maid one about a mismatch of bootloader version or the Evil Maid message was the first to pop up?

If the issue was caused by faulty hardware or the side effect of an other software, then the Evil Maid message should show up again after some reboots even if no body accessed the machine. 

Just in case, I will do an upgrade test from 1.23-Hotfix-2 to 1.24-Hotfix1 to see if I can reproduce even if I doubt it.

**Comment by zeffy** [comment]
>Did you receive a message before Evil Maid one about a mismatch of bootloader version or the Evil Maid message was the first to pop up?

Evil Maid was the first to pop up, followed by one simply asking if I wanted to read the change log for the new version.

>If the issue was caused by faulty hardware or the side effect of an other software, then the Evil Maid message should show up again after some reboots even if no body accessed the machine.

I've restarted several times, after resetting the bootloader and it hasn't reappeared, but I will try running software I've used over the past few days and see what comes up.

> Just in case, I will do an upgrade test from 1.23-Hotfix-2 to 1.24-Hotfix1 to see if I can reproduce even if I doubt it.

To be completely specific, my upgrade path was 1.23-Hotfix 2 -> 1.24 -> 1.24-Hotfix 1, if that matters.

Thanks though, I really appreciate all your help. It's unfortunate I can't rule out a real evil maid attack 100%, although it is unlikely. In the future, I'll definitely avoid this specific scenario of shutting down after an update and leaving PC unattended. 😛

**Comment by idrassi** [comment]
@zeffy After doing many tests, I think I understand what caused the Evil Maid error issue: you have "Fast Startup" mode enabled in your Windows and so when you shutdown your PC, it didn’t shutdown but rather it was put in a special hibernate mode.
So, after starting it, you are still running the old version of VeraCrypt driver and that’s why it displays the Evil Maid error message.

It is important to restart the machine after updating VeraCrypt in order for the new driver to load. "Fast Startup" mode of Windows makes shutdown fake so you really need to reboot.

So, this was certainly a false positive caused by the fact that you shutdown the PC with "Fast Startup" instead of rebooting it.

Do you confirm that you have "Fast Startup" enabled in Windows?

I advise to disable "Fast Startup" because it can create many issues. There are many links on internet explaining how to disable it.

**Comment by zeffy** [comment]
Bingo! You are right, "fast startup" was turned on, and I've now disabled it. I see now there's a lot of issues regarding this feature. I updated to Windows 10 very recently, so I wasn't even aware of it.

Thanks again for all your help and taking the time to figure this out.
