### ISSUE TITLE
ParameterIncorrect at VeraCrypt::CoreUnix::MountVolume:477

### ISSUE THREAD

**Issue by zmiimz** [veracrypt/VeraCrypt#552]
Some years ago I created a whole disk encrypted drive with the latest working Truecrypt 7.1a using Seagate Barracuda 3Tb SATA HDD in its own (factory-manufactured) external USB3 enclosure "Seagate expansion desktop drive" in Linux.  The USB controller of the external enclosure is broken now and this SATA drive is not detected by the system in this enclosure.  I have another identical enclosure and after inserting the SATA drive into the new one  I can mount the encrypted drive with Veracrypt 1.23 successfully.   To make a backup of this drive I bought simple Yottamaster USB 3.0 Docking Station https://www.amazon.de/gp/product/B0722Z5C4J/ and tried to mount the same encrypted SATA disk using this docking station.  Unfortunately, I got an error
> ParameterIncorrect at VeraCrypt::CoreUnix::MountVolume:477

from Veracrypt in Linux.
In dmesg log I see  one interesting warning for attached drive: 

> [68597.715727] sd 6:0:0:0: Attached scsi generic sg2 type 0
> [68597.716756] sd 6:0:0:0: [sdc] 5860533168 512-byte logical blocks: (3.00 TB/2.73 TiB)
> [68597.716762] sd 6:0:0:0: [sdc] 4096-byte physical blocks
> [68597.717123] sd 6:0:0:0: [sdc] Write Protect is off
> [68597.717128] sd 6:0:0:0: [sdc] Mode Sense: 5f 00 00 08
> [68597.717662] sd 6:0:0:0: [sdc] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
> **[68597.718112] sd 6:0:0:0: [sdc] Optimal transfer size 33553920 bytes not a multiple of physical block size (4096 bytes)**
> [68597.739981] sd 6:0:0:0: [sdc] Attached SCSI disk

If I understand that info correctly, Linux kernel assigns now a different block size for this drive? Was original block size encrypted within Truecrypt header? Is this a bug of docking station/ Linux kernel or do we have a problem within Veracrypt code? Should I return this docking station? I mounted another small  500 Gb SATA SSD without problems using this docking station.

**Comment by alt3r-3go** [comment]
This error comes from [here](https://github.com/veracrypt/VeraCrypt/blob/master/src/Core/Unix/CoreUnix.cpp#L476-L477) and AFAIU that check verifies that the physical block size reported by the OS for the drive is the same as the one recorded in the VC volume header. So looks like they don't match when using that new USB docking station and no, VC itself rather has nothing to do with that.

That warning you highlighted should be irrelevant here as it doesn't affect the block size reporting (per my quick glance at the Linux sources for the code around it).

You can try getting the physical vs. logical volume sizes for both working and non-working adapters using different tools and comparing them for any inconsistencies. See e.g. [this post](https://unix.stackexchange.com/questions/403919/harddrive-with-4096-physical-sector-size-reported-as-512-behind-usb-bridge) for something similar, with command examples.

**Comment by zmiimz** [comment]
@alt3r-3go 
thanks for explanation and good links, docking station goes into return now.

Indeed, with hdd in original Seagate enclosure:

Disk /dev/sdc: 2.75 TiB, 3000592977920 bytes, 732566645 sectors
Disk model: Expansion Desk  
Units: sectors of 1 * 4096 = 4096 bytes
Sector size (logical/physical): 4096 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

hdd in docking station:

Disk /dev/sdc: 2.75 TiB, 3000592982016 bytes, 5860533168 sectors
Disk model: nal USB 3.0     
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

IMHO, would be nice to have a better error message in Veracrypt for this case.

**Comment by alt3r-3go** [comment]
Glad to help and thanks for reporting back! Indeed the Seagate one reports the logical sector size of 4K, same as physcial, and the 3rd-party one reports sort of a standard 512/4K translation, but the VC volume was created with 4K instead of 512 already, so the check fails. I guess the error message in this case could indeed be more verbose. @idrassi, is there any specific reason it isn't and do you think it would be worth it to elaborate? I could do that.

**Comment by idrassi** [comment]
@alt3r-3go I agree that a specific error message is better than the generic incorrect parameter one. The best way to do that is to create a new exception class (for example `DeviceSectorSizeMismatch`) that inherits from `Exception` (this must be done in the file [src/Platform/Exception.h](https://github.com/veracrypt/VeraCrypt/blob/master/src/Platform/Exception.h) using the macro `TC_EXCEPTION`) and then throw this class instead of `ParameterIncorrect`.

Adding new exception class requires modifying the methods `WaitDialog::ThrowException` and `UserInterface::ThrowException` in order to allow it to pass through threads.

A PR with this will be welcomed, thank you.

**Comment by alt3r-3go** [comment]
Got it, thanks for the hints! I'll prepare a PR.
