### ISSUE TITLE
Guideline downgrade back to truecrypt?

### ISSUE THREAD

**Issue by membersound** [veracrypt/VeraCrypt#556]
Hello guys,

could you offer a guideline how to downgrade from veracrypt back to truecrypt?
I have huge cpu (i5 M520) performance issues with veracrypt, and would like to return to truecrypt by now.

What would I have to do in order to not crash my volumes and losing data?

Or would I have to decrypt entirely, and then encrypt again with tc?

**Comment by idrassi** [comment]
The performance issues you are seeing are certainly not coming from VeraCrypt but rather from other Windows issue (mounting takes 2 seconds at most on recent CPUs).

You can achieve the same mount speed as with TrueCrypt but using a PIM value équipe to 1: just use the change password menu and set PIM to 1 for new password (you can keep the same password). With PIM set to 1, mounting takes less than a second on modern CPU.

I suspect that the mount is slow for you because of some other Windows components that may block the mounting of volume (e.g. Windows Defender check).
One way to verify this hypothesis is to check the mount option "Only create virtual device without mounting on selected drive letter" in password dialog before mounting. This way only VeraCrypt process will be performed and no call to Windows Mount Manager will be made. So, if it is quicker this way, this will prove that the slowness issue comes from Windows Mount Manager and not VeraCrypt.

**Comment by vstoykovbg** [comment]
Weakening the key stretching is not a good idea.

**Comment by membersound** [comment]
Mounting without drive letter takes approx 15s, mounting with driveletter 90s.
So my win7 mount manager is the problem? If so, how could I speed things up? Or is the only option then to downgrade to tc? (I would not want to use PIM values).

**Comment by vstoykovbg** [comment]
I think that 15 seconds is reasonable or even too fast. For sensitive information I would use slower key stretching. For example, over 10 minutes. Or even over several hours if the information is very sensitive (you write the passphrase before going to bed and in the morning it's open).

See https://github.com/veracrypt/VeraCrypt/issues/127

If you wait for 15 seconds to open the container, this means that the hypothetical adversary is also waiting 15 seconds while trying for every bruteforce attempt (if using the same hardware; if he is using 1000x faster hardware - 0.015 seconds per attempt).

Did you tried to set the PIM to 1? Maybe it will open the container faster with this option.

**Comment by nikkopt** [comment]
OP is having this problem because when the password prompt appears, he leaves the PKCS-5 PRF in auto detection. If he chooses the specific KD he used when he made the volume (default is SHA512 on veracrypt if i'm not mistaken) then it will only take him a couple of seconds. 
In auto detection, it also takes me around 13 seconds for the volume to open. I'm guessing that veracrypt actually tries to open the volume with all of the options but doesn't start with SHA512

**Comment by membersound** [comment]
I migrated from truecrypt, and the drive encryption shows `AES`. During migration, I left the PKCS on "unchanged". How can I now know which PKCS to use during mount (as AES is not available)?

**Comment by nikkopt** [comment]
AES isn't on the list because it's not used as a key derivation algorithm but for encrypting the data.
You can see the KD algorithm by going to "Volumes" and then "Volume Properties", or by right clicking it on the list and then "Properties".
If you are using volumes made in truecrypt, ticking the "Truecrypt Mode" option is enough because no matter the algorithm it's using, it will open almost instantaneously.

**Comment by membersound** [comment]
Ok, so as I left the PKCS in auto mode during migration from tc to veracrypt, the default algorithm seems to be `HMAC-RIPEMD-160`.

But choosing this before mounting did not reduce the time.
Is there a algorithm that would speed up the process?

**Comment by nikkopt** [comment]
RIPEMD-160 means you are still using truecrypt volumes. They should mount almost instantaneously. The problem isn't veracrypt, like others have said. There is something else slowing down the process. Try installing truecrypt again to see if it's also affected (AFAIK you can have both installed on your system)

**Comment by membersound** [comment]
No, I followed the migration guide from tc to vc. I tested it, the volumes are not mountable by tc anymore.

**Comment by nikkopt** [comment]
My fault, Since veracrypt doesn't allow creating new volumes with RIPEMD-160, i thought it would change it too when you converted a truecrypt volume to a veracrypt one.

**Comment by membersound** [comment]
Ok, but back to my question: it's probably not worth switching the algorithm to get a speed improvement? Or which algo should I use if I'd want to stick with the auto detection feature of VC?
