### ISSUE TITLE
Failed to crate Volume under Debian in Terminal

### ISSUE THREAD

**Issue by Go2Device** [veracrypt/VeraCrypt#57]
Hello,
i get the folowing error if i try to encrypt an external harddrive under Debian 7

`Error: ParameterIncorrect at VeraCrypt::Pkcs5Kdf::ValidateParameters:77`

root@hostname:/tmp# veracrypt -c

```
Volume type:
 1) Normal
 2) Hidden
Select [1]: 1

Enter volume path: /dev/sdb1

Encryption Algorithm:
 1) AES
 2) Serpent
 3) Twofish
 4) AES(Twofish)
 5) AES(Twofish(Serpent))
 6) Serpent(AES)
 7) Serpent(Twofish(AES))
 8) Twofish(Serpent)
Select [1]: 5

Hash algorithm:
 1) SHA-512
 2) Whirlpool
 3) SHA-256
Select [1]: 1

Filesystem:
 1) None
 2) FAT
 3) Linux Ext2
 4) Linux Ext3
 5) Linux Ext4
 6) NTFS
 7) exFAT
Select [2]: 5

Enter password:
Re-enter password:
Passowrd

Enter PIM: 1234567

Enter keyfile path [none]: /tmp/keys/
Enter keyfile path [finish]:

Please type at least 320 randomly chosen characters and then press Enter:
A1bCdE...
Error: ParameterIncorrect at VeraCrypt::Pkcs5Kdf::ValidateParameters:77
```

fdisk /dev/sdb:

```
Command (m for help): p

Disk /dev/sdb: 1000.2 GB, 1000204886016 bytes
81 heads, 63 sectors/track, 382818 cylinders, total 1953525168 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk identifier: 0x2a609ae9

   Device Boot      Start         End      Blocks   Id  System
/dev/sdb1            2048  1953525167   976761560   83  Linux
```

uname -a:
`Linux hostname 3.2.0-4-amd64 #1 SMP Debian 3.2.78-1 x86_64 GNU/Linux`

**Comment by idrassi** [comment]
First of all, a PIM value of 1234567 is too big and it will lead to huge mounting times. As explained in [the documentation](https://veracrypt.codeplex.com/wikipage?title=Personal%20Iterations%20Multiplier%20%28PIM%29), the default PIM value is 484, so a value of 1234567 will lead to mount that is 2545 times slower than the default...

I tried the same parameters as you with an external and I don't have the issue.

The error occurred at the [following code](https://github.com/veracrypt/VeraCrypt/blob/master/src/Volume/Pkcs5Kdf.cpp#L74):
```
	void Pkcs5Kdf::ValidateParameters (const BufferPtr &key, const VolumePassword &password, const ConstBufferPtr &salt, int iterationCount) const
	{
		if (key.Size() < 1 || password.Size() < 1 || salt.Size() < 1 || iterationCount < 1)
			throw ParameterIncorrect (SRC_POS);
	}
```

Because of the context of the call, the only possibility is that `iterationCount `is negative when we arrive here.

Here is how  `iterationCount ` is computed from PIM ([this is described in the documentation](https://veracrypt.codeplex.com/wikipage?title=Personal%20Iterations%20Multiplier%20%28PIM%29)):

```
virtual int GetIterationCount (int pim) const
{
    return m_truecryptMode? 1000 : (pim <= 0 ? 500000 : (15000 + (pim * 1000)));
}
```

So, `iterationCount `can be negative if the result of the PIM formula exceeds 0x7fffffff. This in turn means that the maximum value for the PIM to avoid having a negative result for the formula is **2147468**.

From this, I deduce that you used a PIM value that is bigger than 2147468 and not 1234567 as you wrote in your post. Maybe you typed 12345678 which indeed bigger than 2147468 and this causes the error that was displayed.

As I said in the begining, using big PIM values will leads to an insane number of iterations and many hours for a single mount operations. That's why it was not expected for users to enter such values.

Anyway, I will fix **2147468** as a maximum value for the PIM in order to display a more clear error message instead of the current generic ParameterIncorrect error.

**Comment by Go2Device** [comment]
Thank you. I tray it again without a PIM, but stil the same error. Can it be that the password not be escaped correct? I use special characters like $#;:, £_₩÷@"*()/^

**Comment by andreas-becker** [comment]
@Go2Device do you still have this issue in the current version or can it be closed?
