### ISSUE TITLE
Providing third party binaries for ARM (Raspbian)

### ISSUE THREAD

**Issue by prilr** [veracrypt/VeraCrypt#580]
I've noticed that releases from v1.22 onward don't provide ARM builds.
I've seen an old Armv7 build listed in "Contributed Resources" over at veracrypt.fr.
After some poking around I managed to compile v1.24-Update3 on Raspbian Buster (armv7l).

Would Veracrypt 1.24-Update3 console/GUI builds for ARM be of use, and if so, how would I go about providing them?

**Comment by unit193** [comment]
Hello,

I was just experimenting with the openSUSE build service in order to provide packages for Debian as well as Raspbian.  They seem to build and it looks good so far, but I haven't tested them as I don't have a Raspberry Pi set up.

My testing grounds are https://build.opensuse.org/project/show/home:unit193:veracrypt  If you (or anyone else) does end up testing, it could be interesting to hear feedback.

~Unit 193
Unit193 @ freenode
Unit193 @ OFTC

**Comment by prilr** [comment]
Hi, sorry for taking so long to respond.

I've taken a look at the armv7l build for Raspbian.
Existing volumes seem to be mounting normally, but I'm seeing the following messages while mounting or dismounting:

```
(process:1463): GLib-GObject-WARNING **: 00:15:57.554: invalid (NULL) pointer instance

(process:1463): GLib-GObject-CRITICAL **: 00:15:57.556: g_signal_handlers_disconnect_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(process:1463): GLib-GObject-WARNING **: 00:15:57.556: invalid (NULL) pointer instance

(process:1463): GLib-GObject-CRITICAL **: 00:15:57.557: g_signal_handlers_disconnect_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
```

These messages are new, Update3 build from source didn't have them. Can't tell what causes them yet.
Will update once I've tested the rest of functionality.

**Comment by unit193** [comment]
Howdy,

Glad it seems to be working for you!  Yeah those errors aren't something to be concerned about, but they stem from [this](https://salsa.debian.org/debian-edu-pkg-team/veracrypt/-/blob/master/debian/patches/001-indicator-support.patch) patch we use for Indicator support.

~Unit 193
Unit193 @ freenode
Unit193 @ OFTC
