### ISSUE TITLE
Disabling 'preserve modification timestamp of file containers'

### ISSUE THREAD

**Issue by President38** [veracrypt/VeraCrypt#59]
I just started using CrashPlan as an automatic cloud backup service.

I know from reading here about VeraCrypt, as well as on the CrashPlan support site about TrueCrypt, that in order for the back-up service to recognize changes to an encrypted container and then proceed to automatically back it up, you must disable: 'preserve modification timestamp of file containers' in the  settings>preferences.

I am wondering if there are any security considerations to doing this? In other words, if the timestamp is updated on the encrypted container, would this not let people know when you last accessed the encrypted container? Or is it completely irrelevant? 

Also, I am wondering if the back-up service will back up the entire encrypted container file each time you add files to it or make changes, or should it only back up the portion where files were added and changes made? In other words, if my encrypted container is 100GB, will the back-up service upload the entire 100GB file everytime, or will it just upload a portion of the encrypted file (to where changes were made, files added, etc)?

Thanks for letting me know :)

**Comment by davidfoerster** [comment]
Is this supposed to be an issue report?

**Comment by medvedev125** [comment]
It's issue.
I also run into it.
Steps to reproduce:
0. Turn off the "PreserveTimestamps" option.
So: There is in the config file "Configuration.xml":
...
<config key="PreserveTimestamps">0</config>
...
1. Create VeraCrypt a volume AES, SHA512, FAT:  "test_volume.hc"
2. Remeber a modification time of the file "test_volume.hc"
2. mount the volume
3. Create a file on the volume: "test.txt"
Content of the test.txt is "bla bla bla test bla bla bla "
4. unmount the volume
5.
  Result:       modification time of the file "test_volume.hc" is not changed
   Expected: modification time of the file "test_volume.hc" is changed

**Comment by sir106** [comment]
I also had an Issue (data loss) with that - since I use automated data synchronisation, all changes has been replaced with an old container ;(

**Comment by andreas-becker** [comment]
@President38 is this issue still present in the current version or can it be closed?

**Comment by rishanb** [comment]
I believe it's still an issue. To state it more clearly, cloud services do not know when to sync a vault (i.e. when changes inside have been made) if we preserve the timestamp.

The issue with changing the timestamp every time it's open is that if you have a biggish vault say on Dropbox and synced locally to two pcs (pc1 and pc2), if you make a modification to a file on pc1, you have to wait for pc1 to upload the entire vault AND 2nd PC to down that entire vault before making changes...otherwise you run the risk of losing the changes made on pc1, since the timestamp on PC2 will be later even if you opened it later but didn't make any chances and was working on a non-current version.

My stopgap solutions have been:
1. Keep my vaults as tiny as possible, when I started off years ago, I'd make them at least 50gb+, no a days they are smaller and more specialized so the risk described above is significantly reduced.
2. Use another software that solves this problem, albeit with what looks like weaker encryption - would love to share just not sure of the etiquette on github since I'm fairly new.

**Comment by alt3r-3go** [comment]
In order for this issue record to be actionable - if any action is expected - let's define exactly what the issue is and what the expectations are. I've just read through the whole thread and it's actually discussing many things at once, some of which are just questions, some - intended behavior, which is seemingly not understood and some are ramblings about cloud sync software, which has nothing to do with VC.

As for the timestamp preservation on file containers - there's a dedicated option for that under Settings -> Preferences -> "Windows" section, called "Preserve modification timestamp of file containers", which does exactly what it says on the tin. If anyone participating in the thread (or reading it) has any troubles using this feature - please report here with specific reproduction instructions, or better yet - open a new issue, as this one became a bit hard to read.
