### ISSUE TITLE
Win10 - Encrypting a partition is stopped as "write protected"

### ISSUE THREAD

**Issue by amprantino** [veracrypt/VeraCrypt#598]
Hello all,

I have a similar case with this: https://github.com/veracrypt/VeraCrypt/issues/524

After a recent laptop upgrade (Dell 5400), I split the hard disk. My plan is to use 50GB as an encrypted partition.

While encryption is starting through VeraCrypt, it stops after a few seconds and I get this error:

<img width="232" alt="error1" src="https://user-images.githubusercontent.com/1978223/77231641-04a63a00-6ba5-11ea-844a-d7ddf40de68e.PNG">

Then the disk is detected like that:

<img width="664" alt="error2" src="https://user-images.githubusercontent.com/1978223/77231655-1982cd80-6ba5-11ea-97e8-35ce80776bb7.PNG">

Any idea how to fix that?
I am **not** using Bitlocker and I am **not** trying to double encrypt the hard disk.

**Comment by amprantino** [comment]
I have disabled BitLocker service and everything seems OK now

![disable-bitlocker-windows-services-2](https://user-images.githubusercontent.com/1978223/77232180-21903c80-6ba8-11ea-9d03-14c5e3216fa4.png)

**Comment by BoffinBrain** [comment]
For people who find this thread in the future, I recently had the exact same issue with a new Windows 11 installation. It turned out that the encryption process would not complete because Bitlocker was protecting it.

The following steps worked for me:

1. If you already started encrypting, decrypt the drive via Resume Interrupted Process
2. Disable Bitlocker in Settings and wait for it to complete
3. Restart
4. Begin the encryption process again

I didn't have to disable the Bitlocker service, but perhaps restarting Windows negated the need for that, or the disk had not been completely decrypted at the time of taking the first screenshot.
