### ISSUE TITLE
Error: Dismount Failed.

### ISSUE THREAD

**Issue by flyingrub** [veracrypt/VeraCrypt#6]
While creating a veracrypt hidden partition (from nothing), when it finished to create the outer partition it asked me to put some file on it. Then i clicked by inadvertence on open the cd reader. It dismounted automatically the partition that was just created (i had a notification explaining it). 

But now when i press next it do this : 
![1](http://pix.toile-libre.org/upload/original/1421441454.png)
![2](http://pix.toile-libre.org/upload/original/1421441464.png)
and i can't continue...

**Comment by idrassi** [comment]
The code doesn't expect the outer volume to be dismounted by someone else. Moreover, we want to ensure that the user has copied some sensitive-looking data into the outer volume before we start calculating the maximum size of the hidden volume.

In your case, since the outer volume was dismounted inadvertently, you'll have to mount it manually using the same drive letter attributed to it by VeraCrypt (from your screenshots, it's Z:). Just open VeraCrypt main window, go to the menu "Volumes -> Select File", choose the container file you were creating, select the drive Z in VeraCrypt list of drives, click on mount and type the password of the outer volume (you can choose the PRF to accelerate the mounting). Once the outer volume is mounted in Z:, go back to the VeraCrypt Volume Creation Wizard and there you can click Next but I advise you to copy some data to the outer volume before proceeding with the hidden volume step.

I will see how to detect this special case and display an appropriate error message.

**Comment by flyingrub** [comment]
i canceled the installation and started jsut the hidden one, and it worked well ;)
but i don't understand why we must copy some data before creating the hidden partition?
i didn't copied anything and just set manually a number of data.

**Comment by idrassi** [comment]
As explained in the documentation, in case But if the outer volume is empty, the adversary will be suspicious and he most certainly force you to give the hidden volume password.
By putting sensitive-looking files in the outer volume and updating them regularly, the adversary will be inclined to believe that there is no hidden volume.

Also, the maximum size of the hidden volume is calculated using the size of the data already copied to the outer volume. So, during the life time of the container, the size of the data present on the outer volume should remain almost the same to avoid overwriting the hidden volume part.

I encourage you to read the documentation explaining all these details:
https://veracrypt.codeplex.com/wikipage?title=Hidden%20Volume
https://veracrypt.codeplex.com/wikipage?title=Protection%20of%20Hidden%20Volumes
https://veracrypt.codeplex.com/wikipage?title=Security%20Requirements%20for%20Hidden%20Volumes
