### ISSUE TITLE
Changing the file system and using quick formatting for the external partition when creating a hidden partition. (Linux)

### ISSUE THREAD

**Issue by XZVB12** [veracrypt/VeraCrypt#602]
Hello, I had the following question: why can’t I choose a file system and use quick formatting for external partition when creating a normal / hidden section pair? (formatting starts immediately after entering a password) 
How difficult is this to implement? Can I ask you to “fix” this?
I read the following [note](https://github.com/veracrypt/VeraCrypt/issues/137), but I would like to use gui.
I am using linux and version veracrypt 1.24 update 4 and update 6 (compiled by me from source) (if this is important)
Thank you for your attention and sorry for the trouble.

**Comment by andreas-becker** [comment]
Hello @XZVB12, thank you for your issue.

Unfortunately we have too few developers for the many tasks, so it will certainly take some time before your problem can be solved.

I hope you appreciate that.

Kind regards,
Andreas

**Comment by XZVB12** [comment]
Hi, thanks for the answer, no problem.
I understand the complexities of developing free software and appreciate your work.
I just did not find statements about this "flaw" and decided to write.
I'm sorry I can not offer you help with this.

**Comment by alt3r-3go** [comment]
@XZVB12, this behavior is a feature, not a bug. If quick format was applied to the outer volume, that could have compromised the plausible deniability w.r.t. the hidden volume. See https://www.veracrypt.fr/en/Hidden%20Volume.html (a piece right after the picture) and https://www.veracrypt.fr/en/Security%20Requirements%20for%20Hidden%20Volumes.html for details.

**Comment by XZVB12** [comment]
@alt3r-3go Hello, I will definitely read the documentation that you sent. But if this is an idea why, when performing similar actions on windows, I can use fast formatting without problems?
Thanks.

**Comment by alt3r-3go** [comment]
Okay, I've looked a bit more and looks like on Windows (which is a whole separate code path) the quick format option is indeed exposed, but on Linux it was [explicitly disabled](https://github.com/veracrypt/VeraCrypt/commit/515895342820a9d0a35391ec4d316c3782a75768#diff-ff7f63018684825eeffbcf6cbbd3b48cR767-R770), together with unconditionally setting the FAT as the outer volume filesystem type, so the respective Wizard page piece where you'd normally see the Quick Format checkbox is never shown.

@idrassi, the commit was related to PIM and this particular piece doesn't seem to be directly related to that, it quotes some "free space problems" unless FAT is used. Do you think the Quick Format option could be introduced for Linux, in principle (I could work further on that), or there are some caveats that would prevent that?

**Comment by idrassi** [comment]
@alt3r-3go The fact that FAT is forced for outer volume on Linux alongside disabling of quick format option is something that always existed in the UI and the commit you mentioned was just for adding the same check in PIM related UI.

The reason behind forcing FAT for outer volume is that under Linux and MacOSX, VeraCrypt doesn't know how to scan the cluster bitmap of filesystems other than FAT in order to find the real value of maximum available space for the hidden volume to be created (so that it stays outside the range of clusters associated with outer volume). Without knowing the correct value, the UI can not propose a safe value to use.

In command line mode, we allow the user to specify any size he wants since VeraCrypt in this case doesn't guide the creation process. In UI mode, it is a guided process and so VeraCrypt must be able to propose safe parameters.

Concerning Quick Format option, it is always disabled for outer volume on a disk because of its security implications but I agree that the option should be shown to the user so that he can select it if he accepts the risks (we will display a warning in this case. For file containers, quick format can not be enabled because there is no way to tell Linux to create a file of a certain size quickly without being it a sparse file (there is no equivalent to Windows function `SetFileValidData`).

Based on this, I have decided to implement the following changes:

- Allow enabling Quick Format for Outer volume in case it resides in a disk and not file container.
- Enable choosing filesystems other than FAT for Outer volume and if the user selected a filesystem different from FAT, then VeraCrypt will display a warning about the risk of error in estimating the maximum size of hidden volume and the estimation will be computed as follows:  `maximumAllowedHiddenVolumeSize = (AvailableFreeSpaceOuterVolume * 4) / 5`

I will let you knwo when I push this modification so you can give your opinion on it.
