### ISSUE TITLE
[CLI] Cannot create large volume: "Error: Bad file descriptor"

### ISSUE THREAD

**Issue by arnegroskurth** [veracrypt/VeraCrypt#606]
I'm currently trying to create a new volume using the CLI on linux but the process has now failed for the second time with the same problem:

```
$ veracrypt --text --create container.crypt --keyfiles container.key --filesystem ExFAT --quick --size 3500G --random-source=/dev/urandom
Volume type:
 1) Normal
 2) Hidden
Select [1]:

Encryption Algorithm:
 1) AES
 2) Serpent
 3) Twofish
 4) Camellia
 5) Kuznyechik
 6) AES(Twofish)
 7) AES(Twofish(Serpent))  
 8) Camellia(Kuznyechik)   
 9) Camellia(Serpent)
 10) Kuznyechik(AES)
 11) Kuznyechik(Serpent(Camellia))
 12) Kuznyechik(Twofish)   
 13) Serpent(AES)
 14) Serpent(Twofish(AES)) 
 15) Twofish(Serpent)
Select [1]:

Hash algorithm:
 1) SHA-512
 2) Whirlpool
 3) SHA-256
 4) Streebog
Select [1]:

Enter password:

Enter PIM:

Done: 100.000%  Speed: 145 MiB/s  Left: 0 s

Enter your user password or administrator password:
Warning: Failed to obtain administrator privileges: [sudo] password for ***:
Enter your user password or administrator password:
Enter your user password or administrator password:
Error: Bad file descriptor

VeraCrypt::CoreService::StartElevated:567
```

The operation creates the `container.crypt` volume file with the correct size but it is not mountable:

```
$ sudo veracrypt --text --non-interactive -k container.key --mount container.crypt dir
Error: NTFS signature is missing.
Failed to mount '/dev/mapper/veracrypt2': Invalid argument
The device '/dev/mapper/veracrypt2' doesn't seem to have a valid NTFS.
Maybe the wrong device is used? Or the whole disk instead of a
partition (e.g. /dev/sda, not /dev/sda1)? Or the other way around?
```

Hints:
- I'm running the creation process in a screen-session which is required as I only have remote ssh access to the machine and don't want to risk an abortion of the ~6 hour run due to a bad wifi signal.
- Creating a small 1G volume works (also in the screen session) but I'm not asked for a password there
- My guess is that the question for the password within the screen session causes the problem. (Why do I need to enter the password anyway for that?)

Thank you very much,
Arne

Edit:
I'm using version 1.24-Update4 on an Ubuntu 18.04 LTS.

**Comment by alt3r-3go** [comment]
The volume size doesn't matter for the password request - that's requested in order to perform the mount, when testing the created volume during creation.

I've just tried this under `screen` (though on Fedora 31, so not identical) when working through SSH and it does work fine for me, the password gets through without problems.

A couple of things I'd suggest you to try:
1. Authenticate to `sudo` before running VC, so that it doesn't need to ask for a password (`sudo` by default has certain caching period). Use e.g. `sudo -l`, followed by `sudo -n uptime` to make sure the sudo cache is active. Then run the volume creation command - it shouldn't ask you for the user/admin password. You can invalidate the cache with `sudo -k`.
1. If the above does rule the password passthrough out, it may also be the filesystem type you use. VC passes it to `mount`, so if it doesn't know about `ExFAT` (which is possible - exFAT has some troubled history with Linux support + that name it's case-sensitive, I think, so maybe the spelling is incorrect), there may be an error underneath, which is simply not displayed properly and looks like a password entry error (and then some VC enhancement/fix would be in order). You should be able to check that by using e.g. `--filesystem ext3` instead, that is certainly supported on Ubuntu out of the box.

**Comment by arnegroskurth** [comment]
@alt3r-3go Thank you for your help.

Running the creation as root solved the problem for me - so I guess the filesystem name `ExFAT` is correct. (The volume must be formatted in exfat for intercompatibility within our setup).

**Comment by alt3r-3go** [comment]
Thanks, that's good to know. So that's probably something with the password being passed, but as I couldn't reproduce this in my quick test, it may be hard to nail down. maybe you could try this without the `screen` session? As I mentioned before, the volume size doesn't actually matter, so you could try e.g. 10MB via plain SSH session and see how it goes in your setup. Just make sure you have `sudo` cache invalidated, so that it asks for a password.
