### ISSUE TITLE
Will there be >2TB GPT FDE support soon?!

### ISSUE THREAD

**Issue by hydrogenpi** [veracrypt/VeraCrypt#622]
Will there be >2TB GPT FDE support soon?!

**Comment by andreas-becker** [comment]
Actually there's a lack of developers, therefore i assume that your issue won't be implemented soon. If you're able to integrate it, provide a PR and it might get integrated more quickly.

**Comment by alt3r-3go** [comment]
I'm not aware of such limitation (though I haven't tried, just based on docs). Are you sure it'snot supported?

Quoting https://www.veracrypt.fr/en/VeraCrypt%20Volume%20Format%20Specification.html:
> The maximum possible VeraCrypt volume size is 263 bytes (8,589,934,592 GB). However, due to security reasons (with respect to the 128-bit block size used by the encryption algorithms), the maximum allowed volume size is 1 PB (1,048,576 GB).

**Comment by NightmareJoker2** [comment]
I know that this is working just fine for mounted volumes. I've been using volumes larger than 2TB with TrueCrypt back when the first 3TB drives came out, and continue to use them to this day with VeraCrypt without issues.
The only situation where it might not work, is if you encrypt the whole disk, that is, including the first sector with the boot sector and the partition table (but I doubt that). However that's a bad idea anyway, because this means operating systems will think the disk is blank and might overwrite the first sector (that's not so bad because there's a backup encryption header at the end, but still) or even if they don't repeatedly ask you to initialize the drive with a partition table whenever you reboot or plug it in (what specifically happens depends on the operating system).
You should be creating a partition table, using one large partition, and encrypt that partition instead. If you do that, it doesn't matter what partition table type you are using, apart from the Intel/MBR variant only supporting larger than 2TB partitions, if the drive has native sectors that are more than 512 bytes in size or there's some sector size translation going on between operating system and disk drive.
I do not know about the situation with boot drives, but it has been quite a while since I last wanted to have a boot drive larger than 2TB in size... the last time was when I had a 3-disk RAID5 of 1TB drives and added a 4th drive in the mix to then discover I could no longer boot. Not long after that came affordable and fast SSDs, and me putting all my files on a separate RAID volume due to their small size, alleviating the need. Haven't looked back since.
If what you need is an encrypted bootable drive that is larger than 2TB, and this is not supported (seems doubtful at this point, tho) you may want to try BitLocker (Windows) or LUKS (Linux/BSD) for encryption instead, which I know work fine, even in hacky hybrid MBR systems. Though, this may expose what operating system you are using to someone with access to your disk, via the EFI loader in the ESP, and system or kernel files in the boot partition, and doesn't award you the ability to use a hidden partition (though, using one of those is hardly useful in practice, because the alternate system is difficult to keep in a state that looks recently and actively used).

**Comment by idrassi** [comment]
There is 2TB limitation for GPT drives, either non-system or system.
@hydrogenpi  I will close this issue but feel free to reopen if you have specific issue when trying to use a GPT driver larger than 2TB.
