### ISSUE TITLE
Feature Request: double click *.hc/*.tc file to mount it and open the folder of mount-point

### ISSUE THREAD

**Issue by stevenleeS0ht** [veracrypt/VeraCrypt#624]
Since the default file extension of veracrypt is `*.tc` and `*.hc`, it would be nice to integrate veracrypt to Linux system, when double click the vera volume, veracrypt can popup a password dialog, after input password. It can automatically mount the volume and open the mount-point via default file manager.

**Comment by dhammel** [comment]
I dont know how forseeable this would be in linux natively as it would have to integrate it in your desktop environment.

Which desktop environment do you use?
If you use kde plasma, you can actually set this up. Ive never done it as I dont want it, but you can do so in System Settings->Associations I believe. Telling it which extension to perform actions with, setting a custom photo that appears for all files with said extension, setting an application to launch it with when ran...

I personally dont use tc, or hc extension. I just set it as an img extension to fit in with my other images which are unencrypted.

If you use plasma, you can try it that way.

Due to many different desktop environments such as gnome, plasma, xfce... it could be difficult to have this built in, already hard enough to manage packages between several linux disteibutions.

Should point out, I am not the developer of VeraCrypt.

If it could be introduced at some point, if feasable it would be good for users like yourself that could benefit from it.

**Comment by kangarooo** [comment]
Can this be made? How to open just with double clicking?
