### ISSUE TITLE
Old full encrypted C:/ Drive to new computer

### ISSUE THREAD

**Issue by BlumeCoding** [veracrypt/VeraCrypt#636]
I know the password of the old HDD Drive from my laptop but now its broke

got new pc so how do i Decrypt the old hard drive to use it on the new one?

i cant figure it out

**Comment by RA-Kooi** [comment]
What exactly is broken, your laptop or the drive?

**Comment by BlumeCoding** [comment]
laptop

Rafaël Kooi <notifications@github.com> schrieb am Di. 30. Juni 2020 um
18:51:

**Comment by RA-Kooi** [comment]
Do you still have your Veracrypt Rescue Disk?

**Comment by junpeikyu** [comment]
You should be able to connect the HDD to the new computer. It doesn't matter if via USB or directly on SATA.
It should be possible to tell Veracrypt to select the entire drive and mount it as-is. I'm unsure since I've not tried it out yet, only on a USB Thumbdrive. No-need to fully decrypt. But if you want it should be able to do it in Veracrypt.
Back in the days I just copied all needed files over and Formatted the drive after that.
