### ISSUE TITLE
Fatal build error on Raspberry

### ISSUE THREAD

**Issue by gevvan** [veracrypt/VeraCrypt#642]
First step runs and completes fine without any errors or issues:
make NOGUI=1 WXSTATIC=1 WX_ROOT=/home/notroot/downloadedsource/wxWidgets wxbuild

Second step does not.
Namely, it produces this:
```
notroot@raspberry ~/vercry $ make NOGUI=1 WXSTATIC=1
Linking veracrypt
/usr/bin/ld: /home/notroot/vercry/src/Volume/Volume.a(jitterentropy-base.o0): undefined reference to symbol 'clock_gettime@@GLIBC_2.4'
//lib/arm-linux-gnueabihf/librt.so.1: error adding symbols: DSO missing from command line
collect2: ld returned 1 exit status
Main.make:165: receptet för målet ”veracrypt” misslyckades
make[1]: *** [veracrypt] Fel 1
Makefile:424: receptet för målet ”all” misslyckades
make: *** [all] Fel 2
```

I'm clueless! Since this doesn't seem very "Googable" (not wide-spread) I'm under the impression it's more likely some fault on the system I'm building on (an ARM Raspberry Pi) than the actual Veracrypt. But still, I thought I'd ask what you guys think. 

I'm thinking that my rather old glib6 ("ldd --version" gives me -> v2.13) could be the culprit. Some people claim to have object build issues similar to this one which has fixed itself by simply upgrading glib6 to a more recent version.

However, Since I'm on a very old Raspian system (built on Debian 7.11 wheezy) the official packages stop here, and I'm a bit scared of building manually (outside of what apt-get can do for me) since I'm afraid that it could cause follow-up issues with apt later on. I'm also not interested in a total dist upgrade.

If the old system is the culprit there should be some workaround. People are talking about exporting flags ("-ld" ?) to GCC in before building?

**Comment by idrassi** [comment]
Indeed, the following link indicates that for glibc versions before 2.17 (which is your case), we need to link with `-lrt `when using the function `clock_gettime`: https://linux.die.net/man/2/clock_gettime

So, to fix your issue, just edit the file [src/Makefile](https://github.com/veracrypt/VeraCrypt/blob/master/src/Makefile#L50) at line 50 in order to set `LFLAGS` to `-lrt`. Line 50 should look like:

`export LFLAGS := -lrt`

Let me know if you still have an issue despite this.

I will if I can implement an automatic detection mechanism for old glibc version in order to add this switch if needed.
