### ISSUE TITLE
Wrong error information

### ISSUE THREAD

**Issue by RTS007** [veracrypt/VeraCrypt#644]
I was mounting today the exfat disk on my openSUSE Tumbleweed and I didn't notice, that there is no file system implementation installed (fuse-exfat, exfat-utils). The error that was reported by VeraCrypt (v1.24-Update1 and 1.24-Update7) is:

> mount(2) system call failed: Cannot allocate memory.

I started browsing google for answers. It turns out that the memory allocation error is number 12, which completely did not match the error that occurred. '2' led me to the information that this may be due to incorrect recognition of the filesystem, which consequently led me to the problem of lack of file system implementation. I don't know if this is due to an openSUSE error or a problem with error interpretation, I haven't had a chance to check it on other systems.

**Comment by idrassi** [comment]
Thank you for reporting this issue.
The error message displayed comes directly from Linux `mount` command so we have no control over it and we can't what is the real reason behind `mount` error if this message is wrong.

So, since this is an openSUSE issue and not VeraCrypt one, I will close this issue.
