### ISSUE TITLE
Command line "Silent" argument does not work in "VeraCrypt Format.exe"

### ISSUE THREAD

**Issue by itsho** [veracrypt/VeraCrypt#648]
Hi.

according to the "[Command Line Usage](https://www.veracrypt.fr/code/VeraCrypt/plain/doc/html/Command%20Line%20Usage.html?id=4a7ed6926b276cf88c2485ea2a5e95b7f91e4ac1)" I've added `/silent` to the `VeraCrypt Format.exe /create` command, but the following screen appeared:
![VeraCrypt-Loading](https://user-images.githubusercontent.com/1774797/85940567-dc597480-b925-11ea-9b5a-ce23760fecd6.png)

I've tested with both `VeraCrypt Format.exe` and `VeraCrypt Format-x64.exe` and both produced the same issue.

Just an FYI - This is different behavior than the other exe (`VeraCrypt.exe`) where `/silent` does work as expected.

Thanks.

**Comment by idrassi** [comment]
Thank you for finding and reporting this issue.
I analyzed the code and the problem is in the function `TCFormatVolume` in file Format.c : at line, 771, we call `MountVolume` without setting correctly the `quiet` parameter and so we end up calling `MountVolume` with quiet set to `FALSE` and that's why the waiting dialog is always displayed.

So, line 771 of Format.c should be changed as follows:

`	if (MountVolume (volParams->hwndDlg, driveNo, volParams->volumePath, volParams->password, volParams->pkcs5, volParams->pim, FALSE, FALSE, FALSE, TRUE, &mountOptions, Silent, TRUE) < 1)`

Can you please create a new pull request for this fix? I can do it but since it is you who found the issue and you already started working on the fix, it is better that you get credit for it.

**Comment by itsho** [comment]
Thank you for this, it is **highly** appreciated!
You found the actual fix, no need to credit me.

Thank you.
