### ISSUE TITLE
ERROR: clusers bitmap is not found

### ISSUE THREAD

**Issue by kidburglar** [veracrypt/VeraCrypt#662]
Hello,

I had a input/output error on a hidden volume and when I unmount/remount it like I do most of time I have now "ERROR: custers bitmap is not found".

I have the same result with the latest veracrypt version for Linux.
Is there something I can do to try to repair it?

The outer volume look still "openable".

Cheers.

**Comment by idrassi** [comment]
This error is returned by the operating system and not VeraCrypt. It means that there was a corruption of the filesystem.
repairing this depends on the filesystem used and the OS you are running.
I don't have a recommendation for such issues since it is outside of VeraCrypt scope but on Windows you could try using chkdsk.

I close this issue since it is not related specifically to VeraCrypt. Feel free to reopen if you have elements indicating that it is an issue in VeraCrypt.

**Comment by kidburglar** [comment]
Hello @idrassi 

Thanks for your answer, just to be sure how I can repair the filesystem because I guess it's the filesystem of the hidden volume? I'm using Linux and the filesystem is exfat.

I not ask for a process just to know if I need to try to repair the hidden volume how I can act on it without having the error because it not let me "mount" the hidden volume at all.

**Comment by idrassi** [comment]
You first need to tell VeraCrypt to mount the volume without mounting the filesystem. To do so, click on the "Options" button and then check "Do no mount" under Filesystem as indicated in the screenshot below.

Then, after the mount is successfully, open Terminal and type the folliowing command:

`sudo fsck -t exfat /dev/mapper/veracryptX`

after replacing X by the slot number you choose in the list for mounting the volume. For example, if you choose slot 1, you will type `sudo fsck -t exfat /dev/mapper/veracrypt1`

`fsck` has other options for repairing and you should read its documentation to find how to use it.

![VeraCrypt_NoMountFilesystem_Linux](https://user-images.githubusercontent.com/4698669/89395407-90ac9e80-d70d-11ea-9109-cc44bb4eaa20.png)
