### ISSUE TITLE
Is there a way to set return code to 0 for the following use cases?

### ISSUE THREAD

**Issue by sunknudsen** [veracrypt/VeraCrypt#680]
I use a script with `set -e` to automate backups and given the following commands return code 1, the script exits.

```console
$ veracrypt --text --mount --pim 0 --keyfiles "" --protect-hidden no "/Volumes/foo/bar" /Volumes/bar
The volume "/Volumes/foo/bar" is already mounted.

$ veracrypt --text --dismount "/Volumes/foo/bar"
Error: No such volume is mounted.
```

**Comment by Neirpyc** [comment]
In both case, and error occurred, and I believe this is a normal behavior to return 1.

I think your problem is not a VeraCrypt issue, and you should use some shell return value negation as described on [StackOverflow](https://stackoverflow.com/questions/367069/how-can-i-negate-the-return-value-of-a-process)
