### ISSUE TITLE
Is there a built-in way to add authentication and integrity checks to encrypted volumes?

### ISSUE THREAD

**Issue by sunknudsen** [veracrypt/VeraCrypt#681]
I like the idea of using rsync and VeraCrypt for backups, but currently I have no way of knowing is a container has been tampered with or if its integrity is OK.

I am trying to write a script to add authentication and integrity checks, but handling this outside of VeraCrypt leads to a whole bunch of problems.

Bellow is a bad* proof of concept to illustrate what I am trying to accomplish.

*The password is visible in the process list and if a user kills the script once files have been written to the container, the integrity check fails.

Wish there was a built-in way to solve this problem such as an `--hmac` argument that used key derivation to generate two keys, one to write an HMAC alongside the container file and another for encryption. That being said, I can imagine this could lead to similar timing issues.

Perhaps I am not looking at the problem through the right lens or the problem is not a problem in the first place?

```shell
#! /bin/sh

red=$'\e[1;31m'
end=$'\e[0m'

set -e

printf "Please enter password: "

read -s p

if [ -f "/Volumes/Samsung BAR/bar.hmac" ]; then
  printf "\n%s" "Checking integrity..."
  if [ "$(openssl dgst -sha512 -hmac "$p" "/Volumes/Samsung BAR/bar")" != "$(<"/Volumes/Samsung BAR/bar.hmac")" ]; then
    printf "\n%s" "${red}Check failed${end}"
    exit 1
  fi
fi

printf "\n%s\n" "Unlocking VeraCrypt volume..."

veracrypt --text --non-interactive --mount --pim 0 --keyfiles "" --protect-hidden no --password "$p" "/Volumes/Samsung BAR/bar" /Volumes/Backup

declare -a files=(
  "/Users/sunknudsen/.gnupg"
  "/Users/sunknudsen/.ssh"
  "/Users/sunknudsen/Library/Keychains"
)

for file in "${files[@]}"; do
  rsync -axRS --delete "$file" /Volumes/Backup
done

open /Volumes/Backup

printf "${red}Inspect backup and press enter${end}"

read -r answer

veracrypt --text --dismount "/Volumes/Samsung BAR/bar"

echo "Saving HMAC..."

openssl dgst -sha512 -hmac "$p" "/Volumes/Samsung BAR/bar" > "/Volumes/Samsung BAR/bar.hmac"

echo "Done"
```

**Comment by idrassi** [comment]
Adding integrity check to encryption is not an easy problem to solve in the disk of disk encryption software like VeraCrypt.
There are many known ways to accomplish this but they all come with drawbacks that make them difficult to accept for end users.

In case of VeraCrypt, and disk encryption software in general, we deal with disk sector without any knowledge about the filesystem users. And so, adding integrity checks requires to add a kind of checksum for each sector and this in turn requires extra storage to store these checksum values. Moreover, computing checksum of each sector will make encryption/decryption much slower.

Technically, we can implement integrity checks for sectors if users would accept the two main drawback:

- Loose available space for data in order to have a place to store sectors checksums
- Loose read/write speed (by a factor of 3 to 2)

Luckily, there exists solutions at filesystem level that can handle integrity checks at runtime and I'm thinking particularly about [Btrfs](https://en.wikipedia.org/wiki/Btrfs) filesystem which is now supported by VeraCrypt.It has, among other things, builtin checksum for data and metadata. This could be a solution for integrity of data.

**Comment by sunknudsen** [comment]
Thanks for the detailed follow-up @idrassi. Very appreciated.

I understand adding integrity checks in the context of full disk encryption would add significant overhead which would lower available disk space and I/O performance.

I was referring to some kind of built-in HMAC using the same password (with key derivation) in the context of encrypted volumes which (when not mounted) are essentially a chunk of data that we could run through a hashing algorithm.

The result would be a volume and its HMAC... perhaps both chunks of data could be encapsulate in the final output file.

Btw, I am a privacy advocate and content creator... just recommended doing something similar in my latest privacy guide.

See https://www.youtube.com/watch?v=1cz_ViFB6eE and https://www.youtube.com/watch?v=qPAOMczcuZw (a behind-the-scenes episode in which I suggest using SHA-512 for integrity checks).

Reference material: https://sunknudsen.com/privacy-guides/how-to-backup-and-encrypt-data-privately-and-securely-using-rsync-and-veracrypt-on-macos.

As a sidenote, it would be amazing if you could [peer review and sign](https://sunknudsen.com/privacy-guides/docs#how-to-peer-review-and-sign-a-guide) the above privacy guide.

Clearly no one knows VeraCrypt better than you.

Thanks for your work!

**Comment by idrassi** [comment]
Thank you for the explanations, the need is cleared now and I understand the context.
Basically, the idea would be that VeraCrypt will compute a HMAC (using a key derived from volume password) of the volume after it is dismounted and it will store it either externally or embedded. And then when mounting the volume, VeraCrypt will first verify the HMAC value before mounting the volume and in case of error it will warn the user that file container has been tampered with.

This will add non negligible time for mount/dismount, especially if the file container is large (e.g. 1TiB), but I guess it will be acceptable for those who need it.

I will have a look on how to implement this because it is interesting.

Thank you for sharing your links, they are all interesting. I checked only the link for rsync/veracrypt and it looks good. I will have a look to the others privacy guides before deciding about signing the repository.

**Comment by Serpent27** [comment]
Using BLAKE3 could allow maintaining a valid hash in the case of partial transfers (I've been talking to Sun Knudsen about this and he raised that as a concern)

**Comment by sunknudsen** [comment]
Thanks for the feedback @Serpent27. @idrassi, Alex and I have been bouncing ideas in the context of the privacy guides. He’s the one who suggested using HMACs so glad he joined the conversation.
