### ISSUE TITLE
Mount a VC container with no cache / buffer / but immediate sync to disk

### ISSUE THREAD

**Issue by josephernest** [veracrypt/VeraCrypt#709]
Hi,
I did a test: write a 500MB file in a VC container on a USB2 external HDD: it was done in 1 second. This is impossible since my USB2 HDD has only < 30 MB/sec transfer. So this means the file was still in a Windows RAM buffer / memory cache, but not written to disk yet.
This is confirmed: when I unmounted the volume, I had to wait a long time (the flush was done at this time).

Question: how to mount a VC container volume with no buffering? (i.e. all has to be written to disk immediately)

If not implemented yet, can we add this feature in the "Mount options", it's probably just a few `fsync()` [calls](https://stackoverflow.com/questions/259355/how-can-you-flush-a-write-using-a-file-descriptor/3173139#3173139)?

PS: feel free to delete the same question I posted on Sourceforge forum (I don't use this forum).

**Comment by dhammel** [comment]
Hello,

On linux, i've diaabled write cache for my external devices which then writes data immediately to the device rather tham cache it.

I dknt use Windows, but I did find this guide with a search:
 https://winbuzzer.com/2020/07/31/windows-10-how-to-disable-or-enable-disk-write-caching-xcxwbt/

to disable write cache, an os (not vc) feature.

To mention, I wouldnt disable write cache for any internal hdd, unless you know a reason to do so and are ok with higher write throughput.

Did this answer your question?

**Comment by josephernest** [comment]
Hi @dhammel 

Yes I wouldn't disable cache for an internal HDD, I only want to do it for an external USB HDD, to minimize data loss in the case the HDD is unplugged too early (of course I always avoid this).

Let's say the host disk is `H:\`, the container file is `H:\myVCcontainer.bin` and, once mounted, its `I:\`.

Cache is *already* disabled for `H:\`:

![image](https://user-images.githubusercontent.com/6168083/101878965-cb798400-3b90-11eb-9bbf-c4bf11bfa5e1.png)

But still, disk writes on `I:\` are cached.

The key point is that there are *no* entry in Device Manager or in this dialog for the new "virtual" disk `I:\`:

![image](https://user-images.githubusercontent.com/6168083/101879268-5bb7c900-3b91-11eb-867d-951a5be9f93a.png)

So we can only change the cache policy for `H:\`, but **not** for `I:\` in Windows.

I redid my test, and I confirm:

    I:\ written 1 files of 488.281 MB: 608.0 MB/s
    I:\ written 5000 files of 0.098 MB: 349.3 MB/s

This is impossible on my external HDD (USB2 only, and not SSD), so caching is on.

So I think the only option on Windows would be:

* to have an option in "Default mount options" -> `Disable caching`
* to use `fsync()` system calls rather often in this case

I think this is an important feature if we want to prevent potential data loss for people using VC on Windows with an external HDD. It would increase reliability, and reduce risks.
What do you think @idrassi?

**Comment by alt3r-3go** [comment]
@josephernest I think what you need is the below option ("Mount volumes as removable media"):

![image](https://user-images.githubusercontent.com/45139988/101992081-f955ea00-3cb0-11eb-9f4a-4ff1509de395.png)

Please give it a try.

**Comment by josephernest** [comment]
@alt3r-3go I already tried, I hoped indeed than doing this would set to "non caching" by default, but in fact it does not.

**Comment by alt3r-3go** [comment]
That's quite strange, because that's exactly what that option does. Can you try that speed test you posted earlier, with that option enabled and post the result here?

**Comment by josephernest** [comment]
@alt3r-3go Here is my report:

* Windows 7 x64, Veracrypt 1.24-Update7 
* `H:\` NTFS partition on USB external HDD, caching off (in Hardware settings)
* `H:\mycontainer.bin` mounted as `I:\` with Veracrypt, with option `Mount volumes as removable media` enabled.

When I run this Python code:

```
import os, time
BLOCKS = [os.urandom(100*1024) for _ in range(5000)]  # 5000 blocks of 100 KB
t0 = time.time()
with open('I:\\test.bin', 'wb') as f:
    for block in BLOCKS:
        f.write(block)
print('1 files of 500 MB: %.1f MB/s' % (500/(time.time() - t0)))
```

I get this:

    1 files of 500 MB: 1960.7 MB/s

I have done as well with 5000 files of 100KB, and it's similar.

So this confirms caching is still on.

**Comment by alt3r-3go** [comment]
After looking more into this, it turns out to be not as straightforward as I thought. When testing on a USB stick, indeed when the files are stored directly - it's slow, when it goes through a file-hosted volume (container is on the stick as well) - it's really fast (apparently writing into the cache) and I can see the periodical buffer flushing going on for a while after that.

Looking at the VC code, while it actually *does* set the "removable" flag in all seemingly proper places when that option is checked, that's apparently not enough for Windows to disable the caching and turn to that "expect surprise removal" policy. 

It seems like setting the proper hotplug-related flags would rather be needed (as per https://docs.microsoft.com/en-us/windows/win32/api/winioctl/ns-winioctl-storage_hotplug_info) and I guess it should be done here: https://github.com/veracrypt/VeraCrypt/blob/master/src/Driver/Ntdriver.c#L1573-L1575.

@idrassi, that "removable"-related code seems to be inherited from TC, so I guess it may be outdated or something? Do you know by any chance why only the "removable" flag is set, but not the hotplug ones? It looks like the third bullet from the docs on that (https://www.veracrypt.fr/en/Removable%20Medium%20Volume.html) does not fully work as expected.

Unless there's a specific reason behind that, I can test my proposal out, as I think making Windows set the "expect surprise removal" policy (i.e. disable caching) is what many (all?) people would expect when setting that "mount volumes as removable media" option (as you see I myself got caught :smile:).

**Comment by alt3r-3go** [comment]
Just one more thing, it looks like this old Vista-era document (http://download.microsoft.com/download/9/c/5/9c5b2167-8017-4bae-9fde-d599bac8184a/remstorperms.doc) may have some hints about this as well:

![image](https://user-images.githubusercontent.com/45139988/102019346-5023f800-3d73-11eb-8b7a-8a907902fdd7.png)

That last line may be what we observe right now - VC reports it as "removable", but the `MediaHotplug` member is set to FALSE, which translates to 0, which in turn translates into "media *is* lockable" according to the Win32 docs I linked earlier - so Windows enables the "LazyWrites", i.e. caching. It's Vista, of course, but probably not much changed in this logic since then and it anyway correlates with @josephernest's and my observations here.

**Comment by josephernest** [comment]
Great finding! I think you're right, we could try to modify these
parameters.

I haven't built VC executable yet and I might be slow to install all the
prerequisites  (the right MS VC++ version etc.), so if you have a test .exe
with what you suggested, could you post a link here?

So I'll try if it works and I'll post my observations.

Thanks!

**Comment by josephernest** [comment]
@alt3r-3go Have you been able to test this further? See you!

**Comment by alt3r-3go** [comment]
@josephernest, I haven't yet, that's [hopefully] the plan for the Christmas break :)

**Comment by nerai** [comment]
I'm still observing this behavior in version 1.26.7.

**Comment by RalMay** [comment]
> I'm still observing this behavior in version 1.26.7. Could you kindly have a look if it is supposed to be fixed?

+1
VC 1.26,7 x64 on Microsoft Windows x64 [Version 10.0.19045.3031], especially bad when encrypted volume is in slooow SD cards (my slowest writes 5 MB/s)
