### ISSUE TITLE
Why I have to hit Enter key twice?

### ISSUE THREAD

**Issue by qasmoke** [veracrypt/VeraCrypt#71]
Settings - system encryption
a. using custom message 'something'
b. Password only, No PIN used

When I start my PC, it shows something and
I enter password and press enter ... nothing happens
I enter password and press enter twice ... OK

So, please add
[X] Don't ask PIN

if the user check it, VC will warn

Make sure your system encryption use only password.
If you're using PIN, do not use it!

**Comment by idrassi** [comment]
A commit has been pushed on April 20th 2016 that implements an option to avoid having PIM prompt at boot: https://github.com/veracrypt/VeraCrypt/commit/1396269d573256248bece97e1e291ef0c08e513f

A warning is displayed when this option is checked since the information about PIM will be stored unencrypted on disk (see [this discussion](https://github.com/veracrypt/VeraCrypt/issues/62#issuecomment-219156328) for this)

You can get the latest 1.18-BETA that includes this option from https://sourceforge.net/projects/veracrypt/files/VeraCrypt%20Nightly%20Builds/

I'm closing this issue. Please feel free to add any comments you may have.

![VeraCryptPimBootOption](https://i.imgur.com/SthC4rR.png)

**Comment by frank-dittrich** [comment]
1.
The option "Do not show any texts in the pre-boot authentication..." isn't the first option any more.
So you either need to move the "Do not request PIM in the pre-boot authentication screen..." option further down, or you need to adjust the "Note:..."

2.
Is it possible to adjust the "Do not request PIM ..." setting for an already encrypted system partition without decrypting it?

**Comment by idrassi** [comment]
1. Thank you for this remark. I have pushed [a commit](https://github.com/veracrypt/VeraCrypt/commit/a7056a6ac3c6ed0ea4f12a02a8bc4a0c9bbdbeb3) to put the PIM checkbox at the bottom. It will be included in the upcoming 1.18 (should be release very soon).
2. Yes, it is possible to adjust if PIM is displayed or not at Pre-Boot for an already encrypted system. This is the objective of this option.
