### ISSUE TITLE
When DDM (Default Display Manager) is down

### ISSUE THREAD

**Issue by vexaroniter** [veracrypt/VeraCrypt#715]
If there is a problem with the **DDM**, the partition is **not automatically dismount**, thus the **key remains in memory** and the partition can be mounted upon the next restart of the manager. Without entering the appropriate password. Whereas the GUI section as such is absent, thus a memory leak occurs. When you enter the password from ROOT, you can mount this partition without entering volume password.

**Comment by alt3r-3go** [comment]
Hey @vexaroniter, as for this piece:

> If there is a problem with the DDM, the partition is not automatically dismount <...>

Why would you expect the partition to unmount automatically in this situation in the first place?

**Comment by vexaroniter** [comment]
> Why would you expect the partition to unmount automatically in this situation in the first place?

I don't know, maybe it's safer.
I already tried to recompile the project, and realized that DDM crashes due to Veracrypt. This is the main problem.

**Comment by alt3r-3go** [comment]
> I don't know, maybe it's safer.
Well, in general, creating that kind of dependency/checking at the application (that VC is) level is kind of unusual. I'd argue it's not VC's job to monitor other [system] processes.

> I already tried to recompile the project, and realized that DDM crashes due to Veracrypt. This is the main problem.
That would be a very different thing than what's described in the issue outline. I guess you'd want to modify it then, so that's its more understandable. Also, providing specific error messages that DDM/VC emit when DDM crashes would be helpful.

**Comment by idrassi** [comment]
I agree with @alt3r-3go that it's not VC job to monitor DDM state. If one wants to handle such cases, it is always possible to implement a service to do this and which will call VC with appropriate command line parameters to dismount volumes.

Concerning DDM crashes, VC only uses wxWidgets which in turn use GTK so such crash means that there is an issue in GTK or one of the GTK themes. So, this is something that VC can't control.

Closing this issue since it doesn't seem to be applicable.
