### ISSUE TITLE
VeryaCrypt Bootloader: password is always incorrect after pressing ESC

### ISSUE THREAD

**Issue by jumoog** [veracrypt/VeraCrypt#72]
If you press ESC in the first Menu and VeraCrypt ask for the Passwort and PIM it's always incorrect.

To fixed that issue i had to reboot.

If i enter my Passwort normaly it boots perfect

**Comment by frank-dittrich** [comment]
I used to have a laptop with a Truecrypt encrypted Windows 7 and a LUKS encrypted Fedora (boot loader installed into a Linux partition instead of MBR).
When I wanted to boot Linux instead of Windows, I had to press ESC on the truecrypt password prompt, to get into booting Linux (and being asked to the LUKS passphrase).

So may be pressing ESC to abort the attempt to encrypt the system partition should be considered a feature.

**Comment by andreas-becker** [comment]
@jumoog, is this still an issue?

**Comment by jumoog** [comment]
I don't use VeraCrypt anymore so i can't test right now

**Comment by andreas-becker** [comment]
Maybe @frank-dittrich can help?

**Comment by frank-dittrich** [comment]
I now have a dual-boot system with VeraCrypt encrypted Windows 10 and LUKS encrypted Fedora on a separate SSD. With VeraCrypt 1.23(?) it was possible to use the Windows SSD as default boot device and press escape on the VeraCrypt password prompt to boot Fedora from the 2nd SSD.
An upgrade to 1.24-Hotfix1 broke that feature, so I have to select the boot device via BIOS.
(Apparently, the system tries to boot Windows when pressing escape on the password prompt, which (of course) fails. That's why for now I just switch boot devices via BIOS if needed.)

Currently I'll not have time to install and test Latest Stable Release - 1.24-Update4 (Thursday January 23, 2020).
When I have time to install and test the latest stable release, I'll report back.

**Comment by andreas-becker** [comment]
@frank-dittrich any updates on this issue?
