### ISSUE TITLE
AOMEI backup image ruined by system encryption

### ISSUE THREAD

**Issue by Arson31** [veracrypt/VeraCrypt#835]
Hi,

I made a standard image backup of my system OS and saved it offsite. I did not decrypt the system drive before I made the image. Which I should have. I removed all my partitions from the drive to install a Linux OS. I decided to restore the image back to Windows (how it was when I made the image). I received the Veracrypt boot login and typed in the password but it said incorrect password. So I booted into the rescue disk and restored the keys. I restarted the PC, showed the Veracrypt boot login, typed the password and I was able to get through but it showed the Windows recovery screen (0xc000000f). I looked up the documentation and it said to decrypt the OS drive and boot into windows to fix the boot files. It took a half a day to decrypt the drive and the next day it still shows a login prompt. I typed in the password, got in and same problem. I booted from the windows installation media to fix the startup files for Windows. When it finished it rebooted and the Veracrypt boot login showed up again. This time I hit escape, booted into windows and it showed the Windows recovery screen again. I've tried just about all the options on the recovery disk and I can't fix the Windows boot files to boot normally.

**Comment by thelele** [comment]
Hi,

I use Acronis True Image.

When I do a live (while Windows is running) backup of my system, the image is uncrypted (I can mount it with Acronis as a virtual drive and access all the files). However the non-os drive are encrypted (my data hdd).

It has been years since I've done it. But what I remember is : restore the os image with Acronis. => you will have an uncrypted OS + the veracrypt bootloader.
Then I don't remember if I just bypass the veracrypt bootloader with escape, or if I had a MBR/bootloader from Windows before I encrypted it, which I restored or if I use a recovery/tools to "recreate" the MBR of the windows.
Once done I re-encrypted everything.

I hope that it can helps you a bit.
From what I understand the OS image backup you have done is encrypted?
I guess you alreadu tried this solution? https://www.diskpart.com/help/rebuilt-mbr.html
