### ISSUE TITLE
can't create a travis-ci linux build

### ISSUE THREAD

**Issue by ka7** [veracrypt/VeraCrypt#85]
hi,
i tried "for fun" to create a travis-ci.
https://github.com/ka7/VeraCrypt/blob/travis_build/.travis.yml

unfortunately, the build aborts with ...

> In file included from /home/travis/build/ka7/VeraCrypt/src/Crypto/cpu.h:133:0,
>                  from Cipher.cpp:22:
> /usr/lib/gcc/x86_64-linux-gnu/4.8/include/wmmintrin.h:34:3: error: #error "AES/PCLMUL instructions not enabled"
>  # error "AES/PCLMUL
> instructions not enabled"

(full log can be viewed here)
https://travis-ci.org/ka7/VeraCrypt/builds/150265890

any idea how to solve ?
( i know, this would "just" cover linux, maybe osX cli-builds - not windows; but i like the idea of a 2nd opinion "my patch does not break stuff"  )

**Comment by idrassi** [comment]
This is strange...after some digging, it looks like this is a know issue in GCC that will not be fixed any time soon: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=56298
Basically, GCC disables AES intrinsic if the machine that builds the code doesn't have AES-NI...very weird approach.

Is it possible for your to add "-maes" to gcc command line in order to force use of AES intrinsic?

**Comment by idrassi** [comment]
I have pushed a commit that add the "-maes" switch to VeraCrypt Makefile when gcc >= 4.4 is detected: https://github.com/veracrypt/VeraCrypt/commit/3fb2eedab8ef586cd2686efba0b668a5070fd0af

This should solve this issue. Can you please confirm that it is OK now?

Thanks.

**Comment by ka7** [comment]
yes, this did the trick.
log of a working one: https://travis-ci.org/ka7/VeraCrypt/builds/150724811 as a result.
compiles source, install the make-self-installer. ( the installer asks some interactive questions .. )

**Comment by idrassi** [comment]
Thanks for the feedback.
VeraCrypt installer is interactive (accepting license agreement is mandatory), so it can't be executed in the background. 
Instead of testing the installer, it would be better to test the veracrypt binary itself. The simplest test is "veracrypt -t --test" that performs internal self tests.

**Comment by andreas-becker** [comment]
Seems like this one got fixed. Please close @ka7 or @idrassi
