### ISSUE TITLE
Changing TC_APP_NAME causes "Loader Damaged!"

### ISSUE THREAD

**Issue by fauxlefam** [veracrypt/VeraCrypt#881]
For the past couple of months I've been working on a clone of VeraCrypt that I've modifying to my liking. I'm pretty much done coding but I would like to rename/rebrand the application. however I am unable to do so.

whenever I change the definition of TC_APP_NAME from VeraCrypt to lets say VeraCryptX and make all minor adjustments. everything compiles just fine. the application works just fine. no exception being raised. no errors. all is well.
The problem arises when a full disk encryption is completed and I restart my computer.

to my surprise I am being greeted with a message saying:
" VeraCrypt Boot Loader"
"Loader damaged! Repair with Rescue Disk"

Naturally my first go to thing is to search for the file that is responsible for this error and trace back. I believe BootSector.asm is where I should be looking at. 
unfortunately whenever I change the message (for testing) within this file (e.g. VeraCryptX Boot Loader) it won't reflect on a live system. it does appear to be changing the BootSector.bin files and I do see it back in the msi setup file in a hex format but somehow, someway it shows me the original message.

I believe BootSector.bin is the culprit but I am unsure how to tackle this issue.
Does someone have an idea what's happening here? 

I'm using Windows 10 with legacy BIOS.
UEFI appears to be working fine. 
Building order: First WIN32 then X64 on ALL.

**Comment by idrassi** [comment]
Indeed, this error happens if the checksum of the bootloader computed by BootSector.bin is different from the value stored on the boot sector.
You can debug to see the value computed during system encryption process (method BootEncryption::CreateBootLoaderInMemory) and compare it with the value written to the disk. At some point, a mismatch happens and you need to find when.
One idea I just had: can try using a value for TC_APP_NAME that has the same length as "VeraCrypt" (8 characters)? for example "MyCryptXY". I don't see how it could affect this but it is worth trying.

**Comment by fauxlefam** [comment]
Very Interesting... these are things I haven't quite looked into yet. but it looks promising. I will play around with the code some more tonight.  appreciate your feedback!
