### ISSUE TITLE
inconsistent release source tarball signature

### ISSUE THREAD

**Issue by anthraxx** [veracrypt/VeraCrypt#92]
Hey,

I'm a package maintainer for a distro and currently the source release tarballs are overall inconsistent.
In the past all sourced were distributed on sourceforge including the sources and a signature from the veracrypt team key:
https://sourceforge.net/projects/veracrypt/files/VeraCrypt%201.18/

However the sources over there are missing for 1.18a (but 1.18 is there) only the bundles are available.
I'm aware that inside the bundles there is the source tarball, however that does not play well with packaging scripts to build it, the source should be a separated tarball just containing the sources.

I would highly appreciate if you can separately distribute the 1.18a source files including a detatched signature from the team signing key (like you always did). This would make it more convenient to build VeraCrypt and release an update for my distro.

cheers,
Levente

**Comment by idrassi** [comment]
Hi Levente,

1.18a is identical to 18 except for the Windows installer which includes 1.18 Windows driver counter-signed by Microsoft to allow it to run on Windows 10 Anniversary Edition. All binaries have version 1.18 except the Windows installer.

I understand that this is confusing and the choice I made may not have been the best one but it was an emergency release because early Windows 10 users were blocked.

So, you can safely use 1.18 source code.

**Comment by anthraxx** [comment]
@idrassi Ah thanks for clarification, I understand :smile: Well, then I will just roll out 1.18 if there is no difference for Linux users :smile_cat: 
Thanks a lot for the fast response, closing this
