### ISSUE TITLE
Can't open file selection dialog box

### ISSUE THREAD

**Issue by Isnubi** [veracrypt/VeraCrypt#969]
# Expected behavior
Select a file to mount a volume or select location to create volume.

# Observed behavior
I can't open the file selection dialog box in Veracrypt when I try to create a volume or select a volume to mount.

# Steps to reproduce
1. Open Veracrypt
2. Click on "file" button on volume category
3. Veracrypt will load and it will be in "not respond".

# Screenshots
![image](https://user-images.githubusercontent.com/40593456/188882305-8674f685-37a6-4256-a3bc-133b8be16fc3.png)

# Your Environment

Please tell us more about your environment

**VeraCrypt version:** 1.25.9 (64 bits)

**Operating system and version:** Windows 11 22H2 (build 22622.590)

**System type:** 64 bits

**Comment by JoyZzzzz** [comment]
Similar problem.
The problem appeared after updating Windows 11 to version 22H2

**Comment by Isnubi** [comment]
The problem seems to be caused by Windows, and not Veracrypt.
I'm currently under build 22623.875 and the file selection dialog box work

**Comment by JoyZzzzz** [comment]
Windows 11 22621.675 and 22621.755 (latest) have similar behavior.
In the old TrueCrypt, everything opens fine.

**Comment by Isnubi** [comment]
So it's not caused by Veracrypt, just by Windows 11 insider build.

**Comment by li99yangg** [comment]
## Related current finding / 相关的新线索

**中文：**当前的 #1836 记录了相近的文件选择路径静默退出。我确认搜狗拼音 16.8 可以触发：点击卷路径框或 **Select File** 会退出，拖放文件正常。

临时解决办法是在打开 VeraCrypt 前切换为系统自带的中文或英文输入法（例如微软拼音或英语美式键盘），不要使用搜狗输入法，然后完全退出并重新启动 VeraCrypt。详细环境、对照结果和修复请求已集中在 #1836。

**English:** The current #1836 tracks a related silent exit in the file-selection path. I confirmed Sogou Pinyin 16.8 as a trigger: clicking the volume-path field or **Select File** exits, while drag-and-drop works.

A temporary workaround is to switch to a built-in Chinese or English input method (for example, Microsoft Pinyin or the US English keyboard) instead of Sogou before launching VeraCrypt, then fully exit and relaunch VeraCrypt. Full environment details, A/B results, and the fix request are centralized in #1836.
