### ISSUE TITLE
Access Decrypted disk via Administration share (e$)

### ISSUE THREAD

**Issue by wildenius** [veracrypt/VeraCrypt#97]
Using latest VeraCrypt (1.18) on Server 2012r2. Encrypted a Volume. Now I cant access the Administration share (\192.168.1.5\e$). If I share the Disk it works fine. But the sharing disappear every time I reboot the server or dismount the volume. 

Is this working as intended?  Or... How do I get around this so it will always be shared when mounted?

**Comment by Tharn** [comment]
To share automatically, you need to either

- Have system encryption so you can set the extra volume as a system favourite, which does auto mount early in Windows startup. In this case shares are remembered.

- Instead of mounting manually, use a batch file similar to this one. It includes setting a share. `"c:\Program Files\VeraCrypt\VeraCrypt.exe" /q /v \Device\Harddisk0\Partition4 /l V /nowaitdlg /c n /h n /m label=Crypt
sleep 1
net share Crypt=V: /GRANT:Everyone,FULL /CACHE:None`
